// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: vinbero/v1/bgp_route.proto

package vinberov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/takehaya/vinbero/api/vinbero/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BgpRouteServiceName is the fully-qualified name of the BgpRouteService service.
	BgpRouteServiceName = "vinbero.v1.BgpRouteService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BgpRouteServiceBgpAdvertiseVpnProcedure is the fully-qualified name of the BgpRouteService's
	// BgpAdvertiseVpn RPC.
	BgpRouteServiceBgpAdvertiseVpnProcedure = "/vinbero.v1.BgpRouteService/BgpAdvertiseVpn"
	// BgpRouteServiceBgpAdvertiseUnicastProcedure is the fully-qualified name of the BgpRouteService's
	// BgpAdvertiseUnicast RPC.
	BgpRouteServiceBgpAdvertiseUnicastProcedure = "/vinbero.v1.BgpRouteService/BgpAdvertiseUnicast"
	// BgpRouteServiceBgpWithdrawProcedure is the fully-qualified name of the BgpRouteService's
	// BgpWithdraw RPC.
	BgpRouteServiceBgpWithdrawProcedure = "/vinbero.v1.BgpRouteService/BgpWithdraw"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	bgpRouteServiceServiceDescriptor                   = v1.File_vinbero_v1_bgp_route_proto.Services().ByName("BgpRouteService")
	bgpRouteServiceBgpAdvertiseVpnMethodDescriptor     = bgpRouteServiceServiceDescriptor.Methods().ByName("BgpAdvertiseVpn")
	bgpRouteServiceBgpAdvertiseUnicastMethodDescriptor = bgpRouteServiceServiceDescriptor.Methods().ByName("BgpAdvertiseUnicast")
	bgpRouteServiceBgpWithdrawMethodDescriptor         = bgpRouteServiceServiceDescriptor.Methods().ByName("BgpWithdraw")
)

// BgpRouteServiceClient is a client for the vinbero.v1.BgpRouteService service.
type BgpRouteServiceClient interface {
	BgpAdvertiseVpn(context.Context, *connect.Request[v1.BgpAdvertiseVpnRequest]) (*connect.Response[v1.BgpAdvertiseVpnResponse], error)
	BgpAdvertiseUnicast(context.Context, *connect.Request[v1.BgpAdvertiseUnicastRequest]) (*connect.Response[v1.BgpAdvertiseUnicastResponse], error)
	BgpWithdraw(context.Context, *connect.Request[v1.BgpWithdrawRequest]) (*connect.Response[v1.BgpWithdrawResponse], error)
}

// NewBgpRouteServiceClient constructs a client for the vinbero.v1.BgpRouteService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBgpRouteServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BgpRouteServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &bgpRouteServiceClient{
		bgpAdvertiseVpn: connect.NewClient[v1.BgpAdvertiseVpnRequest, v1.BgpAdvertiseVpnResponse](
			httpClient,
			baseURL+BgpRouteServiceBgpAdvertiseVpnProcedure,
			connect.WithSchema(bgpRouteServiceBgpAdvertiseVpnMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		bgpAdvertiseUnicast: connect.NewClient[v1.BgpAdvertiseUnicastRequest, v1.BgpAdvertiseUnicastResponse](
			httpClient,
			baseURL+BgpRouteServiceBgpAdvertiseUnicastProcedure,
			connect.WithSchema(bgpRouteServiceBgpAdvertiseUnicastMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		bgpWithdraw: connect.NewClient[v1.BgpWithdrawRequest, v1.BgpWithdrawResponse](
			httpClient,
			baseURL+BgpRouteServiceBgpWithdrawProcedure,
			connect.WithSchema(bgpRouteServiceBgpWithdrawMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// bgpRouteServiceClient implements BgpRouteServiceClient.
type bgpRouteServiceClient struct {
	bgpAdvertiseVpn     *connect.Client[v1.BgpAdvertiseVpnRequest, v1.BgpAdvertiseVpnResponse]
	bgpAdvertiseUnicast *connect.Client[v1.BgpAdvertiseUnicastRequest, v1.BgpAdvertiseUnicastResponse]
	bgpWithdraw         *connect.Client[v1.BgpWithdrawRequest, v1.BgpWithdrawResponse]
}

// BgpAdvertiseVpn calls vinbero.v1.BgpRouteService.BgpAdvertiseVpn.
func (c *bgpRouteServiceClient) BgpAdvertiseVpn(ctx context.Context, req *connect.Request[v1.BgpAdvertiseVpnRequest]) (*connect.Response[v1.BgpAdvertiseVpnResponse], error) {
	return c.bgpAdvertiseVpn.CallUnary(ctx, req)
}

// BgpAdvertiseUnicast calls vinbero.v1.BgpRouteService.BgpAdvertiseUnicast.
func (c *bgpRouteServiceClient) BgpAdvertiseUnicast(ctx context.Context, req *connect.Request[v1.BgpAdvertiseUnicastRequest]) (*connect.Response[v1.BgpAdvertiseUnicastResponse], error) {
	return c.bgpAdvertiseUnicast.CallUnary(ctx, req)
}

// BgpWithdraw calls vinbero.v1.BgpRouteService.BgpWithdraw.
func (c *bgpRouteServiceClient) BgpWithdraw(ctx context.Context, req *connect.Request[v1.BgpWithdrawRequest]) (*connect.Response[v1.BgpWithdrawResponse], error) {
	return c.bgpWithdraw.CallUnary(ctx, req)
}

// BgpRouteServiceHandler is an implementation of the vinbero.v1.BgpRouteService service.
type BgpRouteServiceHandler interface {
	BgpAdvertiseVpn(context.Context, *connect.Request[v1.BgpAdvertiseVpnRequest]) (*connect.Response[v1.BgpAdvertiseVpnResponse], error)
	BgpAdvertiseUnicast(context.Context, *connect.Request[v1.BgpAdvertiseUnicastRequest]) (*connect.Response[v1.BgpAdvertiseUnicastResponse], error)
	BgpWithdraw(context.Context, *connect.Request[v1.BgpWithdrawRequest]) (*connect.Response[v1.BgpWithdrawResponse], error)
}

// NewBgpRouteServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBgpRouteServiceHandler(svc BgpRouteServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	bgpRouteServiceBgpAdvertiseVpnHandler := connect.NewUnaryHandler(
		BgpRouteServiceBgpAdvertiseVpnProcedure,
		svc.BgpAdvertiseVpn,
		connect.WithSchema(bgpRouteServiceBgpAdvertiseVpnMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	bgpRouteServiceBgpAdvertiseUnicastHandler := connect.NewUnaryHandler(
		BgpRouteServiceBgpAdvertiseUnicastProcedure,
		svc.BgpAdvertiseUnicast,
		connect.WithSchema(bgpRouteServiceBgpAdvertiseUnicastMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	bgpRouteServiceBgpWithdrawHandler := connect.NewUnaryHandler(
		BgpRouteServiceBgpWithdrawProcedure,
		svc.BgpWithdraw,
		connect.WithSchema(bgpRouteServiceBgpWithdrawMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vinbero.v1.BgpRouteService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BgpRouteServiceBgpAdvertiseVpnProcedure:
			bgpRouteServiceBgpAdvertiseVpnHandler.ServeHTTP(w, r)
		case BgpRouteServiceBgpAdvertiseUnicastProcedure:
			bgpRouteServiceBgpAdvertiseUnicastHandler.ServeHTTP(w, r)
		case BgpRouteServiceBgpWithdrawProcedure:
			bgpRouteServiceBgpWithdrawHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBgpRouteServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBgpRouteServiceHandler struct{}

func (UnimplementedBgpRouteServiceHandler) BgpAdvertiseVpn(context.Context, *connect.Request[v1.BgpAdvertiseVpnRequest]) (*connect.Response[v1.BgpAdvertiseVpnResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.BgpRouteService.BgpAdvertiseVpn is not implemented"))
}

func (UnimplementedBgpRouteServiceHandler) BgpAdvertiseUnicast(context.Context, *connect.Request[v1.BgpAdvertiseUnicastRequest]) (*connect.Response[v1.BgpAdvertiseUnicastResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.BgpRouteService.BgpAdvertiseUnicast is not implemented"))
}

func (UnimplementedBgpRouteServiceHandler) BgpWithdraw(context.Context, *connect.Request[v1.BgpWithdrawRequest]) (*connect.Response[v1.BgpWithdrawResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.BgpRouteService.BgpWithdraw is not implemented"))
}
