// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: vinbero/v1/plugin.proto

package vinberov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/takehaya/vinbero/api/vinbero/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PluginServiceName is the fully-qualified name of the PluginService service.
	PluginServiceName = "vinbero.v1.PluginService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PluginServicePluginRegisterProcedure is the fully-qualified name of the PluginService's
	// PluginRegister RPC.
	PluginServicePluginRegisterProcedure = "/vinbero.v1.PluginService/PluginRegister"
	// PluginServicePluginUnregisterProcedure is the fully-qualified name of the PluginService's
	// PluginUnregister RPC.
	PluginServicePluginUnregisterProcedure = "/vinbero.v1.PluginService/PluginUnregister"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	pluginServiceServiceDescriptor                = v1.File_vinbero_v1_plugin_proto.Services().ByName("PluginService")
	pluginServicePluginRegisterMethodDescriptor   = pluginServiceServiceDescriptor.Methods().ByName("PluginRegister")
	pluginServicePluginUnregisterMethodDescriptor = pluginServiceServiceDescriptor.Methods().ByName("PluginUnregister")
)

// PluginServiceClient is a client for the vinbero.v1.PluginService service.
type PluginServiceClient interface {
	PluginRegister(context.Context, *connect.Request[v1.PluginRegisterRequest]) (*connect.Response[v1.PluginRegisterResponse], error)
	PluginUnregister(context.Context, *connect.Request[v1.PluginUnregisterRequest]) (*connect.Response[v1.PluginUnregisterResponse], error)
}

// NewPluginServiceClient constructs a client for the vinbero.v1.PluginService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPluginServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PluginServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &pluginServiceClient{
		pluginRegister: connect.NewClient[v1.PluginRegisterRequest, v1.PluginRegisterResponse](
			httpClient,
			baseURL+PluginServicePluginRegisterProcedure,
			connect.WithSchema(pluginServicePluginRegisterMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		pluginUnregister: connect.NewClient[v1.PluginUnregisterRequest, v1.PluginUnregisterResponse](
			httpClient,
			baseURL+PluginServicePluginUnregisterProcedure,
			connect.WithSchema(pluginServicePluginUnregisterMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// pluginServiceClient implements PluginServiceClient.
type pluginServiceClient struct {
	pluginRegister   *connect.Client[v1.PluginRegisterRequest, v1.PluginRegisterResponse]
	pluginUnregister *connect.Client[v1.PluginUnregisterRequest, v1.PluginUnregisterResponse]
}

// PluginRegister calls vinbero.v1.PluginService.PluginRegister.
func (c *pluginServiceClient) PluginRegister(ctx context.Context, req *connect.Request[v1.PluginRegisterRequest]) (*connect.Response[v1.PluginRegisterResponse], error) {
	return c.pluginRegister.CallUnary(ctx, req)
}

// PluginUnregister calls vinbero.v1.PluginService.PluginUnregister.
func (c *pluginServiceClient) PluginUnregister(ctx context.Context, req *connect.Request[v1.PluginUnregisterRequest]) (*connect.Response[v1.PluginUnregisterResponse], error) {
	return c.pluginUnregister.CallUnary(ctx, req)
}

// PluginServiceHandler is an implementation of the vinbero.v1.PluginService service.
type PluginServiceHandler interface {
	PluginRegister(context.Context, *connect.Request[v1.PluginRegisterRequest]) (*connect.Response[v1.PluginRegisterResponse], error)
	PluginUnregister(context.Context, *connect.Request[v1.PluginUnregisterRequest]) (*connect.Response[v1.PluginUnregisterResponse], error)
}

// NewPluginServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPluginServiceHandler(svc PluginServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pluginServicePluginRegisterHandler := connect.NewUnaryHandler(
		PluginServicePluginRegisterProcedure,
		svc.PluginRegister,
		connect.WithSchema(pluginServicePluginRegisterMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	pluginServicePluginUnregisterHandler := connect.NewUnaryHandler(
		PluginServicePluginUnregisterProcedure,
		svc.PluginUnregister,
		connect.WithSchema(pluginServicePluginUnregisterMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vinbero.v1.PluginService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PluginServicePluginRegisterProcedure:
			pluginServicePluginRegisterHandler.ServeHTTP(w, r)
		case PluginServicePluginUnregisterProcedure:
			pluginServicePluginUnregisterHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPluginServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPluginServiceHandler struct{}

func (UnimplementedPluginServiceHandler) PluginRegister(context.Context, *connect.Request[v1.PluginRegisterRequest]) (*connect.Response[v1.PluginRegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.PluginService.PluginRegister is not implemented"))
}

func (UnimplementedPluginServiceHandler) PluginUnregister(context.Context, *connect.Request[v1.PluginUnregisterRequest]) (*connect.Response[v1.PluginUnregisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.PluginService.PluginUnregister is not implemented"))
}
