// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: vinbero/v1/vinbero.proto

package vinberov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/takehaya/vinbero/api/vinbero/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SidFunctionServiceName is the fully-qualified name of the SidFunctionService service.
	SidFunctionServiceName = "vinbero.v1.SidFunctionService"
	// Transitv4ServiceName is the fully-qualified name of the Transitv4Service service.
	Transitv4ServiceName = "vinbero.v1.Transitv4Service"
	// Transitv6ServiceName is the fully-qualified name of the Transitv6Service service.
	Transitv6ServiceName = "vinbero.v1.Transitv6Service"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SidFunctionServiceSidFunctionCreateProcedure is the fully-qualified name of the
	// SidFunctionService's SidFunctionCreate RPC.
	SidFunctionServiceSidFunctionCreateProcedure = "/vinbero.v1.SidFunctionService/SidFunctionCreate"
	// SidFunctionServiceSidFunctionDeleteProcedure is the fully-qualified name of the
	// SidFunctionService's SidFunctionDelete RPC.
	SidFunctionServiceSidFunctionDeleteProcedure = "/vinbero.v1.SidFunctionService/SidFunctionDelete"
	// SidFunctionServiceSidFunctionListProcedure is the fully-qualified name of the
	// SidFunctionService's SidFunctionList RPC.
	SidFunctionServiceSidFunctionListProcedure = "/vinbero.v1.SidFunctionService/SidFunctionList"
	// SidFunctionServiceSidFunctionGetProcedure is the fully-qualified name of the SidFunctionService's
	// SidFunctionGet RPC.
	SidFunctionServiceSidFunctionGetProcedure = "/vinbero.v1.SidFunctionService/SidFunctionGet"
	// Transitv4ServiceTransitv4CreateProcedure is the fully-qualified name of the Transitv4Service's
	// Transitv4Create RPC.
	Transitv4ServiceTransitv4CreateProcedure = "/vinbero.v1.Transitv4Service/Transitv4Create"
	// Transitv4ServiceTransitv4DeleteProcedure is the fully-qualified name of the Transitv4Service's
	// Transitv4Delete RPC.
	Transitv4ServiceTransitv4DeleteProcedure = "/vinbero.v1.Transitv4Service/Transitv4Delete"
	// Transitv4ServiceTransitv4ListProcedure is the fully-qualified name of the Transitv4Service's
	// Transitv4List RPC.
	Transitv4ServiceTransitv4ListProcedure = "/vinbero.v1.Transitv4Service/Transitv4List"
	// Transitv4ServiceTransitv4GetProcedure is the fully-qualified name of the Transitv4Service's
	// Transitv4Get RPC.
	Transitv4ServiceTransitv4GetProcedure = "/vinbero.v1.Transitv4Service/Transitv4Get"
	// Transitv6ServiceTransitv6CreateProcedure is the fully-qualified name of the Transitv6Service's
	// Transitv6Create RPC.
	Transitv6ServiceTransitv6CreateProcedure = "/vinbero.v1.Transitv6Service/Transitv6Create"
	// Transitv6ServiceTransitv6DeleteProcedure is the fully-qualified name of the Transitv6Service's
	// Transitv6Delete RPC.
	Transitv6ServiceTransitv6DeleteProcedure = "/vinbero.v1.Transitv6Service/Transitv6Delete"
	// Transitv6ServiceTransitv6ListProcedure is the fully-qualified name of the Transitv6Service's
	// Transitv6List RPC.
	Transitv6ServiceTransitv6ListProcedure = "/vinbero.v1.Transitv6Service/Transitv6List"
	// Transitv6ServiceTransitv6GetProcedure is the fully-qualified name of the Transitv6Service's
	// Transitv6Get RPC.
	Transitv6ServiceTransitv6GetProcedure = "/vinbero.v1.Transitv6Service/Transitv6Get"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	sidFunctionServiceServiceDescriptor                 = v1.File_vinbero_v1_vinbero_proto.Services().ByName("SidFunctionService")
	sidFunctionServiceSidFunctionCreateMethodDescriptor = sidFunctionServiceServiceDescriptor.Methods().ByName("SidFunctionCreate")
	sidFunctionServiceSidFunctionDeleteMethodDescriptor = sidFunctionServiceServiceDescriptor.Methods().ByName("SidFunctionDelete")
	sidFunctionServiceSidFunctionListMethodDescriptor   = sidFunctionServiceServiceDescriptor.Methods().ByName("SidFunctionList")
	sidFunctionServiceSidFunctionGetMethodDescriptor    = sidFunctionServiceServiceDescriptor.Methods().ByName("SidFunctionGet")
	transitv4ServiceServiceDescriptor                   = v1.File_vinbero_v1_vinbero_proto.Services().ByName("Transitv4Service")
	transitv4ServiceTransitv4CreateMethodDescriptor     = transitv4ServiceServiceDescriptor.Methods().ByName("Transitv4Create")
	transitv4ServiceTransitv4DeleteMethodDescriptor     = transitv4ServiceServiceDescriptor.Methods().ByName("Transitv4Delete")
	transitv4ServiceTransitv4ListMethodDescriptor       = transitv4ServiceServiceDescriptor.Methods().ByName("Transitv4List")
	transitv4ServiceTransitv4GetMethodDescriptor        = transitv4ServiceServiceDescriptor.Methods().ByName("Transitv4Get")
	transitv6ServiceServiceDescriptor                   = v1.File_vinbero_v1_vinbero_proto.Services().ByName("Transitv6Service")
	transitv6ServiceTransitv6CreateMethodDescriptor     = transitv6ServiceServiceDescriptor.Methods().ByName("Transitv6Create")
	transitv6ServiceTransitv6DeleteMethodDescriptor     = transitv6ServiceServiceDescriptor.Methods().ByName("Transitv6Delete")
	transitv6ServiceTransitv6ListMethodDescriptor       = transitv6ServiceServiceDescriptor.Methods().ByName("Transitv6List")
	transitv6ServiceTransitv6GetMethodDescriptor        = transitv6ServiceServiceDescriptor.Methods().ByName("Transitv6Get")
)

// SidFunctionServiceClient is a client for the vinbero.v1.SidFunctionService service.
type SidFunctionServiceClient interface {
	SidFunctionCreate(context.Context, *connect.Request[v1.SidFunctionCreateRequest]) (*connect.Response[v1.SidFunctionCreateResponse], error)
	SidFunctionDelete(context.Context, *connect.Request[v1.SidFunctionDeleteRequest]) (*connect.Response[v1.SidFunctionDeleteResponse], error)
	SidFunctionList(context.Context, *connect.Request[v1.SidFunctionListRequest]) (*connect.Response[v1.SidFunctionListResponse], error)
	SidFunctionGet(context.Context, *connect.Request[v1.SidFunctionGetRequest]) (*connect.Response[v1.SidFunctionGetResponse], error)
}

// NewSidFunctionServiceClient constructs a client for the vinbero.v1.SidFunctionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSidFunctionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SidFunctionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &sidFunctionServiceClient{
		sidFunctionCreate: connect.NewClient[v1.SidFunctionCreateRequest, v1.SidFunctionCreateResponse](
			httpClient,
			baseURL+SidFunctionServiceSidFunctionCreateProcedure,
			connect.WithSchema(sidFunctionServiceSidFunctionCreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		sidFunctionDelete: connect.NewClient[v1.SidFunctionDeleteRequest, v1.SidFunctionDeleteResponse](
			httpClient,
			baseURL+SidFunctionServiceSidFunctionDeleteProcedure,
			connect.WithSchema(sidFunctionServiceSidFunctionDeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		sidFunctionList: connect.NewClient[v1.SidFunctionListRequest, v1.SidFunctionListResponse](
			httpClient,
			baseURL+SidFunctionServiceSidFunctionListProcedure,
			connect.WithSchema(sidFunctionServiceSidFunctionListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		sidFunctionGet: connect.NewClient[v1.SidFunctionGetRequest, v1.SidFunctionGetResponse](
			httpClient,
			baseURL+SidFunctionServiceSidFunctionGetProcedure,
			connect.WithSchema(sidFunctionServiceSidFunctionGetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// sidFunctionServiceClient implements SidFunctionServiceClient.
type sidFunctionServiceClient struct {
	sidFunctionCreate *connect.Client[v1.SidFunctionCreateRequest, v1.SidFunctionCreateResponse]
	sidFunctionDelete *connect.Client[v1.SidFunctionDeleteRequest, v1.SidFunctionDeleteResponse]
	sidFunctionList   *connect.Client[v1.SidFunctionListRequest, v1.SidFunctionListResponse]
	sidFunctionGet    *connect.Client[v1.SidFunctionGetRequest, v1.SidFunctionGetResponse]
}

// SidFunctionCreate calls vinbero.v1.SidFunctionService.SidFunctionCreate.
func (c *sidFunctionServiceClient) SidFunctionCreate(ctx context.Context, req *connect.Request[v1.SidFunctionCreateRequest]) (*connect.Response[v1.SidFunctionCreateResponse], error) {
	return c.sidFunctionCreate.CallUnary(ctx, req)
}

// SidFunctionDelete calls vinbero.v1.SidFunctionService.SidFunctionDelete.
func (c *sidFunctionServiceClient) SidFunctionDelete(ctx context.Context, req *connect.Request[v1.SidFunctionDeleteRequest]) (*connect.Response[v1.SidFunctionDeleteResponse], error) {
	return c.sidFunctionDelete.CallUnary(ctx, req)
}

// SidFunctionList calls vinbero.v1.SidFunctionService.SidFunctionList.
func (c *sidFunctionServiceClient) SidFunctionList(ctx context.Context, req *connect.Request[v1.SidFunctionListRequest]) (*connect.Response[v1.SidFunctionListResponse], error) {
	return c.sidFunctionList.CallUnary(ctx, req)
}

// SidFunctionGet calls vinbero.v1.SidFunctionService.SidFunctionGet.
func (c *sidFunctionServiceClient) SidFunctionGet(ctx context.Context, req *connect.Request[v1.SidFunctionGetRequest]) (*connect.Response[v1.SidFunctionGetResponse], error) {
	return c.sidFunctionGet.CallUnary(ctx, req)
}

// SidFunctionServiceHandler is an implementation of the vinbero.v1.SidFunctionService service.
type SidFunctionServiceHandler interface {
	SidFunctionCreate(context.Context, *connect.Request[v1.SidFunctionCreateRequest]) (*connect.Response[v1.SidFunctionCreateResponse], error)
	SidFunctionDelete(context.Context, *connect.Request[v1.SidFunctionDeleteRequest]) (*connect.Response[v1.SidFunctionDeleteResponse], error)
	SidFunctionList(context.Context, *connect.Request[v1.SidFunctionListRequest]) (*connect.Response[v1.SidFunctionListResponse], error)
	SidFunctionGet(context.Context, *connect.Request[v1.SidFunctionGetRequest]) (*connect.Response[v1.SidFunctionGetResponse], error)
}

// NewSidFunctionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSidFunctionServiceHandler(svc SidFunctionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sidFunctionServiceSidFunctionCreateHandler := connect.NewUnaryHandler(
		SidFunctionServiceSidFunctionCreateProcedure,
		svc.SidFunctionCreate,
		connect.WithSchema(sidFunctionServiceSidFunctionCreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sidFunctionServiceSidFunctionDeleteHandler := connect.NewUnaryHandler(
		SidFunctionServiceSidFunctionDeleteProcedure,
		svc.SidFunctionDelete,
		connect.WithSchema(sidFunctionServiceSidFunctionDeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sidFunctionServiceSidFunctionListHandler := connect.NewUnaryHandler(
		SidFunctionServiceSidFunctionListProcedure,
		svc.SidFunctionList,
		connect.WithSchema(sidFunctionServiceSidFunctionListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sidFunctionServiceSidFunctionGetHandler := connect.NewUnaryHandler(
		SidFunctionServiceSidFunctionGetProcedure,
		svc.SidFunctionGet,
		connect.WithSchema(sidFunctionServiceSidFunctionGetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vinbero.v1.SidFunctionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SidFunctionServiceSidFunctionCreateProcedure:
			sidFunctionServiceSidFunctionCreateHandler.ServeHTTP(w, r)
		case SidFunctionServiceSidFunctionDeleteProcedure:
			sidFunctionServiceSidFunctionDeleteHandler.ServeHTTP(w, r)
		case SidFunctionServiceSidFunctionListProcedure:
			sidFunctionServiceSidFunctionListHandler.ServeHTTP(w, r)
		case SidFunctionServiceSidFunctionGetProcedure:
			sidFunctionServiceSidFunctionGetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSidFunctionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSidFunctionServiceHandler struct{}

func (UnimplementedSidFunctionServiceHandler) SidFunctionCreate(context.Context, *connect.Request[v1.SidFunctionCreateRequest]) (*connect.Response[v1.SidFunctionCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.SidFunctionService.SidFunctionCreate is not implemented"))
}

func (UnimplementedSidFunctionServiceHandler) SidFunctionDelete(context.Context, *connect.Request[v1.SidFunctionDeleteRequest]) (*connect.Response[v1.SidFunctionDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.SidFunctionService.SidFunctionDelete is not implemented"))
}

func (UnimplementedSidFunctionServiceHandler) SidFunctionList(context.Context, *connect.Request[v1.SidFunctionListRequest]) (*connect.Response[v1.SidFunctionListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.SidFunctionService.SidFunctionList is not implemented"))
}

func (UnimplementedSidFunctionServiceHandler) SidFunctionGet(context.Context, *connect.Request[v1.SidFunctionGetRequest]) (*connect.Response[v1.SidFunctionGetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.SidFunctionService.SidFunctionGet is not implemented"))
}

// Transitv4ServiceClient is a client for the vinbero.v1.Transitv4Service service.
type Transitv4ServiceClient interface {
	Transitv4Create(context.Context, *connect.Request[v1.Transitv4CreateRequest]) (*connect.Response[v1.Transitv4CreateResponse], error)
	Transitv4Delete(context.Context, *connect.Request[v1.Transitv4DeleteRequest]) (*connect.Response[v1.Transitv4DeleteResponse], error)
	Transitv4List(context.Context, *connect.Request[v1.Transitv4ListRequest]) (*connect.Response[v1.Transitv4ListResponse], error)
	Transitv4Get(context.Context, *connect.Request[v1.Transitv4GetRequest]) (*connect.Response[v1.Transitv4GetResponse], error)
}

// NewTransitv4ServiceClient constructs a client for the vinbero.v1.Transitv4Service service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTransitv4ServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) Transitv4ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &transitv4ServiceClient{
		transitv4Create: connect.NewClient[v1.Transitv4CreateRequest, v1.Transitv4CreateResponse](
			httpClient,
			baseURL+Transitv4ServiceTransitv4CreateProcedure,
			connect.WithSchema(transitv4ServiceTransitv4CreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		transitv4Delete: connect.NewClient[v1.Transitv4DeleteRequest, v1.Transitv4DeleteResponse](
			httpClient,
			baseURL+Transitv4ServiceTransitv4DeleteProcedure,
			connect.WithSchema(transitv4ServiceTransitv4DeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		transitv4List: connect.NewClient[v1.Transitv4ListRequest, v1.Transitv4ListResponse](
			httpClient,
			baseURL+Transitv4ServiceTransitv4ListProcedure,
			connect.WithSchema(transitv4ServiceTransitv4ListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		transitv4Get: connect.NewClient[v1.Transitv4GetRequest, v1.Transitv4GetResponse](
			httpClient,
			baseURL+Transitv4ServiceTransitv4GetProcedure,
			connect.WithSchema(transitv4ServiceTransitv4GetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// transitv4ServiceClient implements Transitv4ServiceClient.
type transitv4ServiceClient struct {
	transitv4Create *connect.Client[v1.Transitv4CreateRequest, v1.Transitv4CreateResponse]
	transitv4Delete *connect.Client[v1.Transitv4DeleteRequest, v1.Transitv4DeleteResponse]
	transitv4List   *connect.Client[v1.Transitv4ListRequest, v1.Transitv4ListResponse]
	transitv4Get    *connect.Client[v1.Transitv4GetRequest, v1.Transitv4GetResponse]
}

// Transitv4Create calls vinbero.v1.Transitv4Service.Transitv4Create.
func (c *transitv4ServiceClient) Transitv4Create(ctx context.Context, req *connect.Request[v1.Transitv4CreateRequest]) (*connect.Response[v1.Transitv4CreateResponse], error) {
	return c.transitv4Create.CallUnary(ctx, req)
}

// Transitv4Delete calls vinbero.v1.Transitv4Service.Transitv4Delete.
func (c *transitv4ServiceClient) Transitv4Delete(ctx context.Context, req *connect.Request[v1.Transitv4DeleteRequest]) (*connect.Response[v1.Transitv4DeleteResponse], error) {
	return c.transitv4Delete.CallUnary(ctx, req)
}

// Transitv4List calls vinbero.v1.Transitv4Service.Transitv4List.
func (c *transitv4ServiceClient) Transitv4List(ctx context.Context, req *connect.Request[v1.Transitv4ListRequest]) (*connect.Response[v1.Transitv4ListResponse], error) {
	return c.transitv4List.CallUnary(ctx, req)
}

// Transitv4Get calls vinbero.v1.Transitv4Service.Transitv4Get.
func (c *transitv4ServiceClient) Transitv4Get(ctx context.Context, req *connect.Request[v1.Transitv4GetRequest]) (*connect.Response[v1.Transitv4GetResponse], error) {
	return c.transitv4Get.CallUnary(ctx, req)
}

// Transitv4ServiceHandler is an implementation of the vinbero.v1.Transitv4Service service.
type Transitv4ServiceHandler interface {
	Transitv4Create(context.Context, *connect.Request[v1.Transitv4CreateRequest]) (*connect.Response[v1.Transitv4CreateResponse], error)
	Transitv4Delete(context.Context, *connect.Request[v1.Transitv4DeleteRequest]) (*connect.Response[v1.Transitv4DeleteResponse], error)
	Transitv4List(context.Context, *connect.Request[v1.Transitv4ListRequest]) (*connect.Response[v1.Transitv4ListResponse], error)
	Transitv4Get(context.Context, *connect.Request[v1.Transitv4GetRequest]) (*connect.Response[v1.Transitv4GetResponse], error)
}

// NewTransitv4ServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTransitv4ServiceHandler(svc Transitv4ServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	transitv4ServiceTransitv4CreateHandler := connect.NewUnaryHandler(
		Transitv4ServiceTransitv4CreateProcedure,
		svc.Transitv4Create,
		connect.WithSchema(transitv4ServiceTransitv4CreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	transitv4ServiceTransitv4DeleteHandler := connect.NewUnaryHandler(
		Transitv4ServiceTransitv4DeleteProcedure,
		svc.Transitv4Delete,
		connect.WithSchema(transitv4ServiceTransitv4DeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	transitv4ServiceTransitv4ListHandler := connect.NewUnaryHandler(
		Transitv4ServiceTransitv4ListProcedure,
		svc.Transitv4List,
		connect.WithSchema(transitv4ServiceTransitv4ListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	transitv4ServiceTransitv4GetHandler := connect.NewUnaryHandler(
		Transitv4ServiceTransitv4GetProcedure,
		svc.Transitv4Get,
		connect.WithSchema(transitv4ServiceTransitv4GetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vinbero.v1.Transitv4Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case Transitv4ServiceTransitv4CreateProcedure:
			transitv4ServiceTransitv4CreateHandler.ServeHTTP(w, r)
		case Transitv4ServiceTransitv4DeleteProcedure:
			transitv4ServiceTransitv4DeleteHandler.ServeHTTP(w, r)
		case Transitv4ServiceTransitv4ListProcedure:
			transitv4ServiceTransitv4ListHandler.ServeHTTP(w, r)
		case Transitv4ServiceTransitv4GetProcedure:
			transitv4ServiceTransitv4GetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTransitv4ServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTransitv4ServiceHandler struct{}

func (UnimplementedTransitv4ServiceHandler) Transitv4Create(context.Context, *connect.Request[v1.Transitv4CreateRequest]) (*connect.Response[v1.Transitv4CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Transitv4Service.Transitv4Create is not implemented"))
}

func (UnimplementedTransitv4ServiceHandler) Transitv4Delete(context.Context, *connect.Request[v1.Transitv4DeleteRequest]) (*connect.Response[v1.Transitv4DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Transitv4Service.Transitv4Delete is not implemented"))
}

func (UnimplementedTransitv4ServiceHandler) Transitv4List(context.Context, *connect.Request[v1.Transitv4ListRequest]) (*connect.Response[v1.Transitv4ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Transitv4Service.Transitv4List is not implemented"))
}

func (UnimplementedTransitv4ServiceHandler) Transitv4Get(context.Context, *connect.Request[v1.Transitv4GetRequest]) (*connect.Response[v1.Transitv4GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Transitv4Service.Transitv4Get is not implemented"))
}

// Transitv6ServiceClient is a client for the vinbero.v1.Transitv6Service service.
type Transitv6ServiceClient interface {
	Transitv6Create(context.Context, *connect.Request[v1.Transitv6CreateRequest]) (*connect.Response[v1.Transitv6CreateResponse], error)
	Transitv6Delete(context.Context, *connect.Request[v1.Transitv6DeleteRequest]) (*connect.Response[v1.Transitv6DeleteResponse], error)
	Transitv6List(context.Context, *connect.Request[v1.Transitv6ListRequest]) (*connect.Response[v1.Transitv6ListResponse], error)
	Transitv6Get(context.Context, *connect.Request[v1.Transitv6GetRequest]) (*connect.Response[v1.Transitv6GetResponse], error)
}

// NewTransitv6ServiceClient constructs a client for the vinbero.v1.Transitv6Service service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTransitv6ServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) Transitv6ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &transitv6ServiceClient{
		transitv6Create: connect.NewClient[v1.Transitv6CreateRequest, v1.Transitv6CreateResponse](
			httpClient,
			baseURL+Transitv6ServiceTransitv6CreateProcedure,
			connect.WithSchema(transitv6ServiceTransitv6CreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		transitv6Delete: connect.NewClient[v1.Transitv6DeleteRequest, v1.Transitv6DeleteResponse](
			httpClient,
			baseURL+Transitv6ServiceTransitv6DeleteProcedure,
			connect.WithSchema(transitv6ServiceTransitv6DeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		transitv6List: connect.NewClient[v1.Transitv6ListRequest, v1.Transitv6ListResponse](
			httpClient,
			baseURL+Transitv6ServiceTransitv6ListProcedure,
			connect.WithSchema(transitv6ServiceTransitv6ListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		transitv6Get: connect.NewClient[v1.Transitv6GetRequest, v1.Transitv6GetResponse](
			httpClient,
			baseURL+Transitv6ServiceTransitv6GetProcedure,
			connect.WithSchema(transitv6ServiceTransitv6GetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// transitv6ServiceClient implements Transitv6ServiceClient.
type transitv6ServiceClient struct {
	transitv6Create *connect.Client[v1.Transitv6CreateRequest, v1.Transitv6CreateResponse]
	transitv6Delete *connect.Client[v1.Transitv6DeleteRequest, v1.Transitv6DeleteResponse]
	transitv6List   *connect.Client[v1.Transitv6ListRequest, v1.Transitv6ListResponse]
	transitv6Get    *connect.Client[v1.Transitv6GetRequest, v1.Transitv6GetResponse]
}

// Transitv6Create calls vinbero.v1.Transitv6Service.Transitv6Create.
func (c *transitv6ServiceClient) Transitv6Create(ctx context.Context, req *connect.Request[v1.Transitv6CreateRequest]) (*connect.Response[v1.Transitv6CreateResponse], error) {
	return c.transitv6Create.CallUnary(ctx, req)
}

// Transitv6Delete calls vinbero.v1.Transitv6Service.Transitv6Delete.
func (c *transitv6ServiceClient) Transitv6Delete(ctx context.Context, req *connect.Request[v1.Transitv6DeleteRequest]) (*connect.Response[v1.Transitv6DeleteResponse], error) {
	return c.transitv6Delete.CallUnary(ctx, req)
}

// Transitv6List calls vinbero.v1.Transitv6Service.Transitv6List.
func (c *transitv6ServiceClient) Transitv6List(ctx context.Context, req *connect.Request[v1.Transitv6ListRequest]) (*connect.Response[v1.Transitv6ListResponse], error) {
	return c.transitv6List.CallUnary(ctx, req)
}

// Transitv6Get calls vinbero.v1.Transitv6Service.Transitv6Get.
func (c *transitv6ServiceClient) Transitv6Get(ctx context.Context, req *connect.Request[v1.Transitv6GetRequest]) (*connect.Response[v1.Transitv6GetResponse], error) {
	return c.transitv6Get.CallUnary(ctx, req)
}

// Transitv6ServiceHandler is an implementation of the vinbero.v1.Transitv6Service service.
type Transitv6ServiceHandler interface {
	Transitv6Create(context.Context, *connect.Request[v1.Transitv6CreateRequest]) (*connect.Response[v1.Transitv6CreateResponse], error)
	Transitv6Delete(context.Context, *connect.Request[v1.Transitv6DeleteRequest]) (*connect.Response[v1.Transitv6DeleteResponse], error)
	Transitv6List(context.Context, *connect.Request[v1.Transitv6ListRequest]) (*connect.Response[v1.Transitv6ListResponse], error)
	Transitv6Get(context.Context, *connect.Request[v1.Transitv6GetRequest]) (*connect.Response[v1.Transitv6GetResponse], error)
}

// NewTransitv6ServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTransitv6ServiceHandler(svc Transitv6ServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	transitv6ServiceTransitv6CreateHandler := connect.NewUnaryHandler(
		Transitv6ServiceTransitv6CreateProcedure,
		svc.Transitv6Create,
		connect.WithSchema(transitv6ServiceTransitv6CreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	transitv6ServiceTransitv6DeleteHandler := connect.NewUnaryHandler(
		Transitv6ServiceTransitv6DeleteProcedure,
		svc.Transitv6Delete,
		connect.WithSchema(transitv6ServiceTransitv6DeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	transitv6ServiceTransitv6ListHandler := connect.NewUnaryHandler(
		Transitv6ServiceTransitv6ListProcedure,
		svc.Transitv6List,
		connect.WithSchema(transitv6ServiceTransitv6ListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	transitv6ServiceTransitv6GetHandler := connect.NewUnaryHandler(
		Transitv6ServiceTransitv6GetProcedure,
		svc.Transitv6Get,
		connect.WithSchema(transitv6ServiceTransitv6GetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vinbero.v1.Transitv6Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case Transitv6ServiceTransitv6CreateProcedure:
			transitv6ServiceTransitv6CreateHandler.ServeHTTP(w, r)
		case Transitv6ServiceTransitv6DeleteProcedure:
			transitv6ServiceTransitv6DeleteHandler.ServeHTTP(w, r)
		case Transitv6ServiceTransitv6ListProcedure:
			transitv6ServiceTransitv6ListHandler.ServeHTTP(w, r)
		case Transitv6ServiceTransitv6GetProcedure:
			transitv6ServiceTransitv6GetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTransitv6ServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTransitv6ServiceHandler struct{}

func (UnimplementedTransitv6ServiceHandler) Transitv6Create(context.Context, *connect.Request[v1.Transitv6CreateRequest]) (*connect.Response[v1.Transitv6CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Transitv6Service.Transitv6Create is not implemented"))
}

func (UnimplementedTransitv6ServiceHandler) Transitv6Delete(context.Context, *connect.Request[v1.Transitv6DeleteRequest]) (*connect.Response[v1.Transitv6DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Transitv6Service.Transitv6Delete is not implemented"))
}

func (UnimplementedTransitv6ServiceHandler) Transitv6List(context.Context, *connect.Request[v1.Transitv6ListRequest]) (*connect.Response[v1.Transitv6ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Transitv6Service.Transitv6List is not implemented"))
}

func (UnimplementedTransitv6ServiceHandler) Transitv6Get(context.Context, *connect.Request[v1.Transitv6GetRequest]) (*connect.Response[v1.Transitv6GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Transitv6Service.Transitv6Get is not implemented"))
}
