// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: vinbero/v1/vinbero.proto

package vinberov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/takehaya/vinbero/api/vinbero/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SidFunctionServiceName is the fully-qualified name of the SidFunctionService service.
	SidFunctionServiceName = "vinbero.v1.SidFunctionService"
	// Headendv4ServiceName is the fully-qualified name of the Headendv4Service service.
	Headendv4ServiceName = "vinbero.v1.Headendv4Service"
	// Headendv6ServiceName is the fully-qualified name of the Headendv6Service service.
	Headendv6ServiceName = "vinbero.v1.Headendv6Service"
	// DmacServiceName is the fully-qualified name of the DmacService service.
	DmacServiceName = "vinbero.v1.DmacService"
	// BdPeerServiceName is the fully-qualified name of the BdPeerService service.
	BdPeerServiceName = "vinbero.v1.BdPeerService"
	// NetworkResourceServiceName is the fully-qualified name of the NetworkResourceService service.
	NetworkResourceServiceName = "vinbero.v1.NetworkResourceService"
	// HeadendL2ServiceName is the fully-qualified name of the HeadendL2Service service.
	HeadendL2ServiceName = "vinbero.v1.HeadendL2Service"
	// StatsServiceName is the fully-qualified name of the StatsService service.
	StatsServiceName = "vinbero.v1.StatsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SidFunctionServiceSidFunctionCreateProcedure is the fully-qualified name of the
	// SidFunctionService's SidFunctionCreate RPC.
	SidFunctionServiceSidFunctionCreateProcedure = "/vinbero.v1.SidFunctionService/SidFunctionCreate"
	// SidFunctionServiceSidFunctionDeleteProcedure is the fully-qualified name of the
	// SidFunctionService's SidFunctionDelete RPC.
	SidFunctionServiceSidFunctionDeleteProcedure = "/vinbero.v1.SidFunctionService/SidFunctionDelete"
	// SidFunctionServiceSidFunctionListProcedure is the fully-qualified name of the
	// SidFunctionService's SidFunctionList RPC.
	SidFunctionServiceSidFunctionListProcedure = "/vinbero.v1.SidFunctionService/SidFunctionList"
	// SidFunctionServiceSidFunctionGetProcedure is the fully-qualified name of the SidFunctionService's
	// SidFunctionGet RPC.
	SidFunctionServiceSidFunctionGetProcedure = "/vinbero.v1.SidFunctionService/SidFunctionGet"
	// Headendv4ServiceHeadendv4CreateProcedure is the fully-qualified name of the Headendv4Service's
	// Headendv4Create RPC.
	Headendv4ServiceHeadendv4CreateProcedure = "/vinbero.v1.Headendv4Service/Headendv4Create"
	// Headendv4ServiceHeadendv4DeleteProcedure is the fully-qualified name of the Headendv4Service's
	// Headendv4Delete RPC.
	Headendv4ServiceHeadendv4DeleteProcedure = "/vinbero.v1.Headendv4Service/Headendv4Delete"
	// Headendv4ServiceHeadendv4ListProcedure is the fully-qualified name of the Headendv4Service's
	// Headendv4List RPC.
	Headendv4ServiceHeadendv4ListProcedure = "/vinbero.v1.Headendv4Service/Headendv4List"
	// Headendv4ServiceHeadendv4GetProcedure is the fully-qualified name of the Headendv4Service's
	// Headendv4Get RPC.
	Headendv4ServiceHeadendv4GetProcedure = "/vinbero.v1.Headendv4Service/Headendv4Get"
	// Headendv6ServiceHeadendv6CreateProcedure is the fully-qualified name of the Headendv6Service's
	// Headendv6Create RPC.
	Headendv6ServiceHeadendv6CreateProcedure = "/vinbero.v1.Headendv6Service/Headendv6Create"
	// Headendv6ServiceHeadendv6DeleteProcedure is the fully-qualified name of the Headendv6Service's
	// Headendv6Delete RPC.
	Headendv6ServiceHeadendv6DeleteProcedure = "/vinbero.v1.Headendv6Service/Headendv6Delete"
	// Headendv6ServiceHeadendv6ListProcedure is the fully-qualified name of the Headendv6Service's
	// Headendv6List RPC.
	Headendv6ServiceHeadendv6ListProcedure = "/vinbero.v1.Headendv6Service/Headendv6List"
	// Headendv6ServiceHeadendv6GetProcedure is the fully-qualified name of the Headendv6Service's
	// Headendv6Get RPC.
	Headendv6ServiceHeadendv6GetProcedure = "/vinbero.v1.Headendv6Service/Headendv6Get"
	// DmacServiceDmacListProcedure is the fully-qualified name of the DmacService's DmacList RPC.
	DmacServiceDmacListProcedure = "/vinbero.v1.DmacService/DmacList"
	// BdPeerServiceBdPeerCreateProcedure is the fully-qualified name of the BdPeerService's
	// BdPeerCreate RPC.
	BdPeerServiceBdPeerCreateProcedure = "/vinbero.v1.BdPeerService/BdPeerCreate"
	// BdPeerServiceBdPeerDeleteProcedure is the fully-qualified name of the BdPeerService's
	// BdPeerDelete RPC.
	BdPeerServiceBdPeerDeleteProcedure = "/vinbero.v1.BdPeerService/BdPeerDelete"
	// BdPeerServiceBdPeerListProcedure is the fully-qualified name of the BdPeerService's BdPeerList
	// RPC.
	BdPeerServiceBdPeerListProcedure = "/vinbero.v1.BdPeerService/BdPeerList"
	// NetworkResourceServiceVrfCreateProcedure is the fully-qualified name of the
	// NetworkResourceService's VrfCreate RPC.
	NetworkResourceServiceVrfCreateProcedure = "/vinbero.v1.NetworkResourceService/VrfCreate"
	// NetworkResourceServiceVrfDeleteProcedure is the fully-qualified name of the
	// NetworkResourceService's VrfDelete RPC.
	NetworkResourceServiceVrfDeleteProcedure = "/vinbero.v1.NetworkResourceService/VrfDelete"
	// NetworkResourceServiceVrfListProcedure is the fully-qualified name of the
	// NetworkResourceService's VrfList RPC.
	NetworkResourceServiceVrfListProcedure = "/vinbero.v1.NetworkResourceService/VrfList"
	// NetworkResourceServiceBridgeCreateProcedure is the fully-qualified name of the
	// NetworkResourceService's BridgeCreate RPC.
	NetworkResourceServiceBridgeCreateProcedure = "/vinbero.v1.NetworkResourceService/BridgeCreate"
	// NetworkResourceServiceBridgeDeleteProcedure is the fully-qualified name of the
	// NetworkResourceService's BridgeDelete RPC.
	NetworkResourceServiceBridgeDeleteProcedure = "/vinbero.v1.NetworkResourceService/BridgeDelete"
	// NetworkResourceServiceBridgeListProcedure is the fully-qualified name of the
	// NetworkResourceService's BridgeList RPC.
	NetworkResourceServiceBridgeListProcedure = "/vinbero.v1.NetworkResourceService/BridgeList"
	// HeadendL2ServiceHeadendL2CreateProcedure is the fully-qualified name of the HeadendL2Service's
	// HeadendL2Create RPC.
	HeadendL2ServiceHeadendL2CreateProcedure = "/vinbero.v1.HeadendL2Service/HeadendL2Create"
	// HeadendL2ServiceHeadendL2DeleteProcedure is the fully-qualified name of the HeadendL2Service's
	// HeadendL2Delete RPC.
	HeadendL2ServiceHeadendL2DeleteProcedure = "/vinbero.v1.HeadendL2Service/HeadendL2Delete"
	// HeadendL2ServiceHeadendL2ListProcedure is the fully-qualified name of the HeadendL2Service's
	// HeadendL2List RPC.
	HeadendL2ServiceHeadendL2ListProcedure = "/vinbero.v1.HeadendL2Service/HeadendL2List"
	// HeadendL2ServiceHeadendL2GetProcedure is the fully-qualified name of the HeadendL2Service's
	// HeadendL2Get RPC.
	HeadendL2ServiceHeadendL2GetProcedure = "/vinbero.v1.HeadendL2Service/HeadendL2Get"
	// StatsServiceStatsShowProcedure is the fully-qualified name of the StatsService's StatsShow RPC.
	StatsServiceStatsShowProcedure = "/vinbero.v1.StatsService/StatsShow"
	// StatsServiceStatsResetProcedure is the fully-qualified name of the StatsService's StatsReset RPC.
	StatsServiceStatsResetProcedure = "/vinbero.v1.StatsService/StatsReset"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	sidFunctionServiceServiceDescriptor                 = v1.File_vinbero_v1_vinbero_proto.Services().ByName("SidFunctionService")
	sidFunctionServiceSidFunctionCreateMethodDescriptor = sidFunctionServiceServiceDescriptor.Methods().ByName("SidFunctionCreate")
	sidFunctionServiceSidFunctionDeleteMethodDescriptor = sidFunctionServiceServiceDescriptor.Methods().ByName("SidFunctionDelete")
	sidFunctionServiceSidFunctionListMethodDescriptor   = sidFunctionServiceServiceDescriptor.Methods().ByName("SidFunctionList")
	sidFunctionServiceSidFunctionGetMethodDescriptor    = sidFunctionServiceServiceDescriptor.Methods().ByName("SidFunctionGet")
	headendv4ServiceServiceDescriptor                   = v1.File_vinbero_v1_vinbero_proto.Services().ByName("Headendv4Service")
	headendv4ServiceHeadendv4CreateMethodDescriptor     = headendv4ServiceServiceDescriptor.Methods().ByName("Headendv4Create")
	headendv4ServiceHeadendv4DeleteMethodDescriptor     = headendv4ServiceServiceDescriptor.Methods().ByName("Headendv4Delete")
	headendv4ServiceHeadendv4ListMethodDescriptor       = headendv4ServiceServiceDescriptor.Methods().ByName("Headendv4List")
	headendv4ServiceHeadendv4GetMethodDescriptor        = headendv4ServiceServiceDescriptor.Methods().ByName("Headendv4Get")
	headendv6ServiceServiceDescriptor                   = v1.File_vinbero_v1_vinbero_proto.Services().ByName("Headendv6Service")
	headendv6ServiceHeadendv6CreateMethodDescriptor     = headendv6ServiceServiceDescriptor.Methods().ByName("Headendv6Create")
	headendv6ServiceHeadendv6DeleteMethodDescriptor     = headendv6ServiceServiceDescriptor.Methods().ByName("Headendv6Delete")
	headendv6ServiceHeadendv6ListMethodDescriptor       = headendv6ServiceServiceDescriptor.Methods().ByName("Headendv6List")
	headendv6ServiceHeadendv6GetMethodDescriptor        = headendv6ServiceServiceDescriptor.Methods().ByName("Headendv6Get")
	dmacServiceServiceDescriptor                        = v1.File_vinbero_v1_vinbero_proto.Services().ByName("DmacService")
	dmacServiceDmacListMethodDescriptor                 = dmacServiceServiceDescriptor.Methods().ByName("DmacList")
	bdPeerServiceServiceDescriptor                      = v1.File_vinbero_v1_vinbero_proto.Services().ByName("BdPeerService")
	bdPeerServiceBdPeerCreateMethodDescriptor           = bdPeerServiceServiceDescriptor.Methods().ByName("BdPeerCreate")
	bdPeerServiceBdPeerDeleteMethodDescriptor           = bdPeerServiceServiceDescriptor.Methods().ByName("BdPeerDelete")
	bdPeerServiceBdPeerListMethodDescriptor             = bdPeerServiceServiceDescriptor.Methods().ByName("BdPeerList")
	networkResourceServiceServiceDescriptor             = v1.File_vinbero_v1_vinbero_proto.Services().ByName("NetworkResourceService")
	networkResourceServiceVrfCreateMethodDescriptor     = networkResourceServiceServiceDescriptor.Methods().ByName("VrfCreate")
	networkResourceServiceVrfDeleteMethodDescriptor     = networkResourceServiceServiceDescriptor.Methods().ByName("VrfDelete")
	networkResourceServiceVrfListMethodDescriptor       = networkResourceServiceServiceDescriptor.Methods().ByName("VrfList")
	networkResourceServiceBridgeCreateMethodDescriptor  = networkResourceServiceServiceDescriptor.Methods().ByName("BridgeCreate")
	networkResourceServiceBridgeDeleteMethodDescriptor  = networkResourceServiceServiceDescriptor.Methods().ByName("BridgeDelete")
	networkResourceServiceBridgeListMethodDescriptor    = networkResourceServiceServiceDescriptor.Methods().ByName("BridgeList")
	headendL2ServiceServiceDescriptor                   = v1.File_vinbero_v1_vinbero_proto.Services().ByName("HeadendL2Service")
	headendL2ServiceHeadendL2CreateMethodDescriptor     = headendL2ServiceServiceDescriptor.Methods().ByName("HeadendL2Create")
	headendL2ServiceHeadendL2DeleteMethodDescriptor     = headendL2ServiceServiceDescriptor.Methods().ByName("HeadendL2Delete")
	headendL2ServiceHeadendL2ListMethodDescriptor       = headendL2ServiceServiceDescriptor.Methods().ByName("HeadendL2List")
	headendL2ServiceHeadendL2GetMethodDescriptor        = headendL2ServiceServiceDescriptor.Methods().ByName("HeadendL2Get")
	statsServiceServiceDescriptor                       = v1.File_vinbero_v1_vinbero_proto.Services().ByName("StatsService")
	statsServiceStatsShowMethodDescriptor               = statsServiceServiceDescriptor.Methods().ByName("StatsShow")
	statsServiceStatsResetMethodDescriptor              = statsServiceServiceDescriptor.Methods().ByName("StatsReset")
)

// SidFunctionServiceClient is a client for the vinbero.v1.SidFunctionService service.
type SidFunctionServiceClient interface {
	SidFunctionCreate(context.Context, *connect.Request[v1.SidFunctionCreateRequest]) (*connect.Response[v1.SidFunctionCreateResponse], error)
	SidFunctionDelete(context.Context, *connect.Request[v1.SidFunctionDeleteRequest]) (*connect.Response[v1.SidFunctionDeleteResponse], error)
	SidFunctionList(context.Context, *connect.Request[v1.SidFunctionListRequest]) (*connect.Response[v1.SidFunctionListResponse], error)
	SidFunctionGet(context.Context, *connect.Request[v1.SidFunctionGetRequest]) (*connect.Response[v1.SidFunctionGetResponse], error)
}

// NewSidFunctionServiceClient constructs a client for the vinbero.v1.SidFunctionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSidFunctionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SidFunctionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &sidFunctionServiceClient{
		sidFunctionCreate: connect.NewClient[v1.SidFunctionCreateRequest, v1.SidFunctionCreateResponse](
			httpClient,
			baseURL+SidFunctionServiceSidFunctionCreateProcedure,
			connect.WithSchema(sidFunctionServiceSidFunctionCreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		sidFunctionDelete: connect.NewClient[v1.SidFunctionDeleteRequest, v1.SidFunctionDeleteResponse](
			httpClient,
			baseURL+SidFunctionServiceSidFunctionDeleteProcedure,
			connect.WithSchema(sidFunctionServiceSidFunctionDeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		sidFunctionList: connect.NewClient[v1.SidFunctionListRequest, v1.SidFunctionListResponse](
			httpClient,
			baseURL+SidFunctionServiceSidFunctionListProcedure,
			connect.WithSchema(sidFunctionServiceSidFunctionListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		sidFunctionGet: connect.NewClient[v1.SidFunctionGetRequest, v1.SidFunctionGetResponse](
			httpClient,
			baseURL+SidFunctionServiceSidFunctionGetProcedure,
			connect.WithSchema(sidFunctionServiceSidFunctionGetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// sidFunctionServiceClient implements SidFunctionServiceClient.
type sidFunctionServiceClient struct {
	sidFunctionCreate *connect.Client[v1.SidFunctionCreateRequest, v1.SidFunctionCreateResponse]
	sidFunctionDelete *connect.Client[v1.SidFunctionDeleteRequest, v1.SidFunctionDeleteResponse]
	sidFunctionList   *connect.Client[v1.SidFunctionListRequest, v1.SidFunctionListResponse]
	sidFunctionGet    *connect.Client[v1.SidFunctionGetRequest, v1.SidFunctionGetResponse]
}

// SidFunctionCreate calls vinbero.v1.SidFunctionService.SidFunctionCreate.
func (c *sidFunctionServiceClient) SidFunctionCreate(ctx context.Context, req *connect.Request[v1.SidFunctionCreateRequest]) (*connect.Response[v1.SidFunctionCreateResponse], error) {
	return c.sidFunctionCreate.CallUnary(ctx, req)
}

// SidFunctionDelete calls vinbero.v1.SidFunctionService.SidFunctionDelete.
func (c *sidFunctionServiceClient) SidFunctionDelete(ctx context.Context, req *connect.Request[v1.SidFunctionDeleteRequest]) (*connect.Response[v1.SidFunctionDeleteResponse], error) {
	return c.sidFunctionDelete.CallUnary(ctx, req)
}

// SidFunctionList calls vinbero.v1.SidFunctionService.SidFunctionList.
func (c *sidFunctionServiceClient) SidFunctionList(ctx context.Context, req *connect.Request[v1.SidFunctionListRequest]) (*connect.Response[v1.SidFunctionListResponse], error) {
	return c.sidFunctionList.CallUnary(ctx, req)
}

// SidFunctionGet calls vinbero.v1.SidFunctionService.SidFunctionGet.
func (c *sidFunctionServiceClient) SidFunctionGet(ctx context.Context, req *connect.Request[v1.SidFunctionGetRequest]) (*connect.Response[v1.SidFunctionGetResponse], error) {
	return c.sidFunctionGet.CallUnary(ctx, req)
}

// SidFunctionServiceHandler is an implementation of the vinbero.v1.SidFunctionService service.
type SidFunctionServiceHandler interface {
	SidFunctionCreate(context.Context, *connect.Request[v1.SidFunctionCreateRequest]) (*connect.Response[v1.SidFunctionCreateResponse], error)
	SidFunctionDelete(context.Context, *connect.Request[v1.SidFunctionDeleteRequest]) (*connect.Response[v1.SidFunctionDeleteResponse], error)
	SidFunctionList(context.Context, *connect.Request[v1.SidFunctionListRequest]) (*connect.Response[v1.SidFunctionListResponse], error)
	SidFunctionGet(context.Context, *connect.Request[v1.SidFunctionGetRequest]) (*connect.Response[v1.SidFunctionGetResponse], error)
}

// NewSidFunctionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSidFunctionServiceHandler(svc SidFunctionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sidFunctionServiceSidFunctionCreateHandler := connect.NewUnaryHandler(
		SidFunctionServiceSidFunctionCreateProcedure,
		svc.SidFunctionCreate,
		connect.WithSchema(sidFunctionServiceSidFunctionCreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sidFunctionServiceSidFunctionDeleteHandler := connect.NewUnaryHandler(
		SidFunctionServiceSidFunctionDeleteProcedure,
		svc.SidFunctionDelete,
		connect.WithSchema(sidFunctionServiceSidFunctionDeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sidFunctionServiceSidFunctionListHandler := connect.NewUnaryHandler(
		SidFunctionServiceSidFunctionListProcedure,
		svc.SidFunctionList,
		connect.WithSchema(sidFunctionServiceSidFunctionListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	sidFunctionServiceSidFunctionGetHandler := connect.NewUnaryHandler(
		SidFunctionServiceSidFunctionGetProcedure,
		svc.SidFunctionGet,
		connect.WithSchema(sidFunctionServiceSidFunctionGetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vinbero.v1.SidFunctionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SidFunctionServiceSidFunctionCreateProcedure:
			sidFunctionServiceSidFunctionCreateHandler.ServeHTTP(w, r)
		case SidFunctionServiceSidFunctionDeleteProcedure:
			sidFunctionServiceSidFunctionDeleteHandler.ServeHTTP(w, r)
		case SidFunctionServiceSidFunctionListProcedure:
			sidFunctionServiceSidFunctionListHandler.ServeHTTP(w, r)
		case SidFunctionServiceSidFunctionGetProcedure:
			sidFunctionServiceSidFunctionGetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSidFunctionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSidFunctionServiceHandler struct{}

func (UnimplementedSidFunctionServiceHandler) SidFunctionCreate(context.Context, *connect.Request[v1.SidFunctionCreateRequest]) (*connect.Response[v1.SidFunctionCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.SidFunctionService.SidFunctionCreate is not implemented"))
}

func (UnimplementedSidFunctionServiceHandler) SidFunctionDelete(context.Context, *connect.Request[v1.SidFunctionDeleteRequest]) (*connect.Response[v1.SidFunctionDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.SidFunctionService.SidFunctionDelete is not implemented"))
}

func (UnimplementedSidFunctionServiceHandler) SidFunctionList(context.Context, *connect.Request[v1.SidFunctionListRequest]) (*connect.Response[v1.SidFunctionListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.SidFunctionService.SidFunctionList is not implemented"))
}

func (UnimplementedSidFunctionServiceHandler) SidFunctionGet(context.Context, *connect.Request[v1.SidFunctionGetRequest]) (*connect.Response[v1.SidFunctionGetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.SidFunctionService.SidFunctionGet is not implemented"))
}

// Headendv4ServiceClient is a client for the vinbero.v1.Headendv4Service service.
type Headendv4ServiceClient interface {
	Headendv4Create(context.Context, *connect.Request[v1.Headendv4CreateRequest]) (*connect.Response[v1.Headendv4CreateResponse], error)
	Headendv4Delete(context.Context, *connect.Request[v1.Headendv4DeleteRequest]) (*connect.Response[v1.Headendv4DeleteResponse], error)
	Headendv4List(context.Context, *connect.Request[v1.Headendv4ListRequest]) (*connect.Response[v1.Headendv4ListResponse], error)
	Headendv4Get(context.Context, *connect.Request[v1.Headendv4GetRequest]) (*connect.Response[v1.Headendv4GetResponse], error)
}

// NewHeadendv4ServiceClient constructs a client for the vinbero.v1.Headendv4Service service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHeadendv4ServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) Headendv4ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &headendv4ServiceClient{
		headendv4Create: connect.NewClient[v1.Headendv4CreateRequest, v1.Headendv4CreateResponse](
			httpClient,
			baseURL+Headendv4ServiceHeadendv4CreateProcedure,
			connect.WithSchema(headendv4ServiceHeadendv4CreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		headendv4Delete: connect.NewClient[v1.Headendv4DeleteRequest, v1.Headendv4DeleteResponse](
			httpClient,
			baseURL+Headendv4ServiceHeadendv4DeleteProcedure,
			connect.WithSchema(headendv4ServiceHeadendv4DeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		headendv4List: connect.NewClient[v1.Headendv4ListRequest, v1.Headendv4ListResponse](
			httpClient,
			baseURL+Headendv4ServiceHeadendv4ListProcedure,
			connect.WithSchema(headendv4ServiceHeadendv4ListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		headendv4Get: connect.NewClient[v1.Headendv4GetRequest, v1.Headendv4GetResponse](
			httpClient,
			baseURL+Headendv4ServiceHeadendv4GetProcedure,
			connect.WithSchema(headendv4ServiceHeadendv4GetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// headendv4ServiceClient implements Headendv4ServiceClient.
type headendv4ServiceClient struct {
	headendv4Create *connect.Client[v1.Headendv4CreateRequest, v1.Headendv4CreateResponse]
	headendv4Delete *connect.Client[v1.Headendv4DeleteRequest, v1.Headendv4DeleteResponse]
	headendv4List   *connect.Client[v1.Headendv4ListRequest, v1.Headendv4ListResponse]
	headendv4Get    *connect.Client[v1.Headendv4GetRequest, v1.Headendv4GetResponse]
}

// Headendv4Create calls vinbero.v1.Headendv4Service.Headendv4Create.
func (c *headendv4ServiceClient) Headendv4Create(ctx context.Context, req *connect.Request[v1.Headendv4CreateRequest]) (*connect.Response[v1.Headendv4CreateResponse], error) {
	return c.headendv4Create.CallUnary(ctx, req)
}

// Headendv4Delete calls vinbero.v1.Headendv4Service.Headendv4Delete.
func (c *headendv4ServiceClient) Headendv4Delete(ctx context.Context, req *connect.Request[v1.Headendv4DeleteRequest]) (*connect.Response[v1.Headendv4DeleteResponse], error) {
	return c.headendv4Delete.CallUnary(ctx, req)
}

// Headendv4List calls vinbero.v1.Headendv4Service.Headendv4List.
func (c *headendv4ServiceClient) Headendv4List(ctx context.Context, req *connect.Request[v1.Headendv4ListRequest]) (*connect.Response[v1.Headendv4ListResponse], error) {
	return c.headendv4List.CallUnary(ctx, req)
}

// Headendv4Get calls vinbero.v1.Headendv4Service.Headendv4Get.
func (c *headendv4ServiceClient) Headendv4Get(ctx context.Context, req *connect.Request[v1.Headendv4GetRequest]) (*connect.Response[v1.Headendv4GetResponse], error) {
	return c.headendv4Get.CallUnary(ctx, req)
}

// Headendv4ServiceHandler is an implementation of the vinbero.v1.Headendv4Service service.
type Headendv4ServiceHandler interface {
	Headendv4Create(context.Context, *connect.Request[v1.Headendv4CreateRequest]) (*connect.Response[v1.Headendv4CreateResponse], error)
	Headendv4Delete(context.Context, *connect.Request[v1.Headendv4DeleteRequest]) (*connect.Response[v1.Headendv4DeleteResponse], error)
	Headendv4List(context.Context, *connect.Request[v1.Headendv4ListRequest]) (*connect.Response[v1.Headendv4ListResponse], error)
	Headendv4Get(context.Context, *connect.Request[v1.Headendv4GetRequest]) (*connect.Response[v1.Headendv4GetResponse], error)
}

// NewHeadendv4ServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHeadendv4ServiceHandler(svc Headendv4ServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	headendv4ServiceHeadendv4CreateHandler := connect.NewUnaryHandler(
		Headendv4ServiceHeadendv4CreateProcedure,
		svc.Headendv4Create,
		connect.WithSchema(headendv4ServiceHeadendv4CreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	headendv4ServiceHeadendv4DeleteHandler := connect.NewUnaryHandler(
		Headendv4ServiceHeadendv4DeleteProcedure,
		svc.Headendv4Delete,
		connect.WithSchema(headendv4ServiceHeadendv4DeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	headendv4ServiceHeadendv4ListHandler := connect.NewUnaryHandler(
		Headendv4ServiceHeadendv4ListProcedure,
		svc.Headendv4List,
		connect.WithSchema(headendv4ServiceHeadendv4ListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	headendv4ServiceHeadendv4GetHandler := connect.NewUnaryHandler(
		Headendv4ServiceHeadendv4GetProcedure,
		svc.Headendv4Get,
		connect.WithSchema(headendv4ServiceHeadendv4GetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vinbero.v1.Headendv4Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case Headendv4ServiceHeadendv4CreateProcedure:
			headendv4ServiceHeadendv4CreateHandler.ServeHTTP(w, r)
		case Headendv4ServiceHeadendv4DeleteProcedure:
			headendv4ServiceHeadendv4DeleteHandler.ServeHTTP(w, r)
		case Headendv4ServiceHeadendv4ListProcedure:
			headendv4ServiceHeadendv4ListHandler.ServeHTTP(w, r)
		case Headendv4ServiceHeadendv4GetProcedure:
			headendv4ServiceHeadendv4GetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHeadendv4ServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHeadendv4ServiceHandler struct{}

func (UnimplementedHeadendv4ServiceHandler) Headendv4Create(context.Context, *connect.Request[v1.Headendv4CreateRequest]) (*connect.Response[v1.Headendv4CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Headendv4Service.Headendv4Create is not implemented"))
}

func (UnimplementedHeadendv4ServiceHandler) Headendv4Delete(context.Context, *connect.Request[v1.Headendv4DeleteRequest]) (*connect.Response[v1.Headendv4DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Headendv4Service.Headendv4Delete is not implemented"))
}

func (UnimplementedHeadendv4ServiceHandler) Headendv4List(context.Context, *connect.Request[v1.Headendv4ListRequest]) (*connect.Response[v1.Headendv4ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Headendv4Service.Headendv4List is not implemented"))
}

func (UnimplementedHeadendv4ServiceHandler) Headendv4Get(context.Context, *connect.Request[v1.Headendv4GetRequest]) (*connect.Response[v1.Headendv4GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Headendv4Service.Headendv4Get is not implemented"))
}

// Headendv6ServiceClient is a client for the vinbero.v1.Headendv6Service service.
type Headendv6ServiceClient interface {
	Headendv6Create(context.Context, *connect.Request[v1.Headendv6CreateRequest]) (*connect.Response[v1.Headendv6CreateResponse], error)
	Headendv6Delete(context.Context, *connect.Request[v1.Headendv6DeleteRequest]) (*connect.Response[v1.Headendv6DeleteResponse], error)
	Headendv6List(context.Context, *connect.Request[v1.Headendv6ListRequest]) (*connect.Response[v1.Headendv6ListResponse], error)
	Headendv6Get(context.Context, *connect.Request[v1.Headendv6GetRequest]) (*connect.Response[v1.Headendv6GetResponse], error)
}

// NewHeadendv6ServiceClient constructs a client for the vinbero.v1.Headendv6Service service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHeadendv6ServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) Headendv6ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &headendv6ServiceClient{
		headendv6Create: connect.NewClient[v1.Headendv6CreateRequest, v1.Headendv6CreateResponse](
			httpClient,
			baseURL+Headendv6ServiceHeadendv6CreateProcedure,
			connect.WithSchema(headendv6ServiceHeadendv6CreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		headendv6Delete: connect.NewClient[v1.Headendv6DeleteRequest, v1.Headendv6DeleteResponse](
			httpClient,
			baseURL+Headendv6ServiceHeadendv6DeleteProcedure,
			connect.WithSchema(headendv6ServiceHeadendv6DeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		headendv6List: connect.NewClient[v1.Headendv6ListRequest, v1.Headendv6ListResponse](
			httpClient,
			baseURL+Headendv6ServiceHeadendv6ListProcedure,
			connect.WithSchema(headendv6ServiceHeadendv6ListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		headendv6Get: connect.NewClient[v1.Headendv6GetRequest, v1.Headendv6GetResponse](
			httpClient,
			baseURL+Headendv6ServiceHeadendv6GetProcedure,
			connect.WithSchema(headendv6ServiceHeadendv6GetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// headendv6ServiceClient implements Headendv6ServiceClient.
type headendv6ServiceClient struct {
	headendv6Create *connect.Client[v1.Headendv6CreateRequest, v1.Headendv6CreateResponse]
	headendv6Delete *connect.Client[v1.Headendv6DeleteRequest, v1.Headendv6DeleteResponse]
	headendv6List   *connect.Client[v1.Headendv6ListRequest, v1.Headendv6ListResponse]
	headendv6Get    *connect.Client[v1.Headendv6GetRequest, v1.Headendv6GetResponse]
}

// Headendv6Create calls vinbero.v1.Headendv6Service.Headendv6Create.
func (c *headendv6ServiceClient) Headendv6Create(ctx context.Context, req *connect.Request[v1.Headendv6CreateRequest]) (*connect.Response[v1.Headendv6CreateResponse], error) {
	return c.headendv6Create.CallUnary(ctx, req)
}

// Headendv6Delete calls vinbero.v1.Headendv6Service.Headendv6Delete.
func (c *headendv6ServiceClient) Headendv6Delete(ctx context.Context, req *connect.Request[v1.Headendv6DeleteRequest]) (*connect.Response[v1.Headendv6DeleteResponse], error) {
	return c.headendv6Delete.CallUnary(ctx, req)
}

// Headendv6List calls vinbero.v1.Headendv6Service.Headendv6List.
func (c *headendv6ServiceClient) Headendv6List(ctx context.Context, req *connect.Request[v1.Headendv6ListRequest]) (*connect.Response[v1.Headendv6ListResponse], error) {
	return c.headendv6List.CallUnary(ctx, req)
}

// Headendv6Get calls vinbero.v1.Headendv6Service.Headendv6Get.
func (c *headendv6ServiceClient) Headendv6Get(ctx context.Context, req *connect.Request[v1.Headendv6GetRequest]) (*connect.Response[v1.Headendv6GetResponse], error) {
	return c.headendv6Get.CallUnary(ctx, req)
}

// Headendv6ServiceHandler is an implementation of the vinbero.v1.Headendv6Service service.
type Headendv6ServiceHandler interface {
	Headendv6Create(context.Context, *connect.Request[v1.Headendv6CreateRequest]) (*connect.Response[v1.Headendv6CreateResponse], error)
	Headendv6Delete(context.Context, *connect.Request[v1.Headendv6DeleteRequest]) (*connect.Response[v1.Headendv6DeleteResponse], error)
	Headendv6List(context.Context, *connect.Request[v1.Headendv6ListRequest]) (*connect.Response[v1.Headendv6ListResponse], error)
	Headendv6Get(context.Context, *connect.Request[v1.Headendv6GetRequest]) (*connect.Response[v1.Headendv6GetResponse], error)
}

// NewHeadendv6ServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHeadendv6ServiceHandler(svc Headendv6ServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	headendv6ServiceHeadendv6CreateHandler := connect.NewUnaryHandler(
		Headendv6ServiceHeadendv6CreateProcedure,
		svc.Headendv6Create,
		connect.WithSchema(headendv6ServiceHeadendv6CreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	headendv6ServiceHeadendv6DeleteHandler := connect.NewUnaryHandler(
		Headendv6ServiceHeadendv6DeleteProcedure,
		svc.Headendv6Delete,
		connect.WithSchema(headendv6ServiceHeadendv6DeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	headendv6ServiceHeadendv6ListHandler := connect.NewUnaryHandler(
		Headendv6ServiceHeadendv6ListProcedure,
		svc.Headendv6List,
		connect.WithSchema(headendv6ServiceHeadendv6ListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	headendv6ServiceHeadendv6GetHandler := connect.NewUnaryHandler(
		Headendv6ServiceHeadendv6GetProcedure,
		svc.Headendv6Get,
		connect.WithSchema(headendv6ServiceHeadendv6GetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vinbero.v1.Headendv6Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case Headendv6ServiceHeadendv6CreateProcedure:
			headendv6ServiceHeadendv6CreateHandler.ServeHTTP(w, r)
		case Headendv6ServiceHeadendv6DeleteProcedure:
			headendv6ServiceHeadendv6DeleteHandler.ServeHTTP(w, r)
		case Headendv6ServiceHeadendv6ListProcedure:
			headendv6ServiceHeadendv6ListHandler.ServeHTTP(w, r)
		case Headendv6ServiceHeadendv6GetProcedure:
			headendv6ServiceHeadendv6GetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHeadendv6ServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHeadendv6ServiceHandler struct{}

func (UnimplementedHeadendv6ServiceHandler) Headendv6Create(context.Context, *connect.Request[v1.Headendv6CreateRequest]) (*connect.Response[v1.Headendv6CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Headendv6Service.Headendv6Create is not implemented"))
}

func (UnimplementedHeadendv6ServiceHandler) Headendv6Delete(context.Context, *connect.Request[v1.Headendv6DeleteRequest]) (*connect.Response[v1.Headendv6DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Headendv6Service.Headendv6Delete is not implemented"))
}

func (UnimplementedHeadendv6ServiceHandler) Headendv6List(context.Context, *connect.Request[v1.Headendv6ListRequest]) (*connect.Response[v1.Headendv6ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Headendv6Service.Headendv6List is not implemented"))
}

func (UnimplementedHeadendv6ServiceHandler) Headendv6Get(context.Context, *connect.Request[v1.Headendv6GetRequest]) (*connect.Response[v1.Headendv6GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.Headendv6Service.Headendv6Get is not implemented"))
}

// DmacServiceClient is a client for the vinbero.v1.DmacService service.
type DmacServiceClient interface {
	DmacList(context.Context, *connect.Request[v1.DmacListRequest]) (*connect.Response[v1.DmacListResponse], error)
}

// NewDmacServiceClient constructs a client for the vinbero.v1.DmacService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDmacServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DmacServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &dmacServiceClient{
		dmacList: connect.NewClient[v1.DmacListRequest, v1.DmacListResponse](
			httpClient,
			baseURL+DmacServiceDmacListProcedure,
			connect.WithSchema(dmacServiceDmacListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// dmacServiceClient implements DmacServiceClient.
type dmacServiceClient struct {
	dmacList *connect.Client[v1.DmacListRequest, v1.DmacListResponse]
}

// DmacList calls vinbero.v1.DmacService.DmacList.
func (c *dmacServiceClient) DmacList(ctx context.Context, req *connect.Request[v1.DmacListRequest]) (*connect.Response[v1.DmacListResponse], error) {
	return c.dmacList.CallUnary(ctx, req)
}

// DmacServiceHandler is an implementation of the vinbero.v1.DmacService service.
type DmacServiceHandler interface {
	DmacList(context.Context, *connect.Request[v1.DmacListRequest]) (*connect.Response[v1.DmacListResponse], error)
}

// NewDmacServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDmacServiceHandler(svc DmacServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dmacServiceDmacListHandler := connect.NewUnaryHandler(
		DmacServiceDmacListProcedure,
		svc.DmacList,
		connect.WithSchema(dmacServiceDmacListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vinbero.v1.DmacService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DmacServiceDmacListProcedure:
			dmacServiceDmacListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDmacServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDmacServiceHandler struct{}

func (UnimplementedDmacServiceHandler) DmacList(context.Context, *connect.Request[v1.DmacListRequest]) (*connect.Response[v1.DmacListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.DmacService.DmacList is not implemented"))
}

// BdPeerServiceClient is a client for the vinbero.v1.BdPeerService service.
type BdPeerServiceClient interface {
	BdPeerCreate(context.Context, *connect.Request[v1.BdPeerCreateRequest]) (*connect.Response[v1.BdPeerCreateResponse], error)
	BdPeerDelete(context.Context, *connect.Request[v1.BdPeerDeleteRequest]) (*connect.Response[v1.BdPeerDeleteResponse], error)
	BdPeerList(context.Context, *connect.Request[v1.BdPeerListRequest]) (*connect.Response[v1.BdPeerListResponse], error)
}

// NewBdPeerServiceClient constructs a client for the vinbero.v1.BdPeerService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBdPeerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BdPeerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &bdPeerServiceClient{
		bdPeerCreate: connect.NewClient[v1.BdPeerCreateRequest, v1.BdPeerCreateResponse](
			httpClient,
			baseURL+BdPeerServiceBdPeerCreateProcedure,
			connect.WithSchema(bdPeerServiceBdPeerCreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		bdPeerDelete: connect.NewClient[v1.BdPeerDeleteRequest, v1.BdPeerDeleteResponse](
			httpClient,
			baseURL+BdPeerServiceBdPeerDeleteProcedure,
			connect.WithSchema(bdPeerServiceBdPeerDeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		bdPeerList: connect.NewClient[v1.BdPeerListRequest, v1.BdPeerListResponse](
			httpClient,
			baseURL+BdPeerServiceBdPeerListProcedure,
			connect.WithSchema(bdPeerServiceBdPeerListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// bdPeerServiceClient implements BdPeerServiceClient.
type bdPeerServiceClient struct {
	bdPeerCreate *connect.Client[v1.BdPeerCreateRequest, v1.BdPeerCreateResponse]
	bdPeerDelete *connect.Client[v1.BdPeerDeleteRequest, v1.BdPeerDeleteResponse]
	bdPeerList   *connect.Client[v1.BdPeerListRequest, v1.BdPeerListResponse]
}

// BdPeerCreate calls vinbero.v1.BdPeerService.BdPeerCreate.
func (c *bdPeerServiceClient) BdPeerCreate(ctx context.Context, req *connect.Request[v1.BdPeerCreateRequest]) (*connect.Response[v1.BdPeerCreateResponse], error) {
	return c.bdPeerCreate.CallUnary(ctx, req)
}

// BdPeerDelete calls vinbero.v1.BdPeerService.BdPeerDelete.
func (c *bdPeerServiceClient) BdPeerDelete(ctx context.Context, req *connect.Request[v1.BdPeerDeleteRequest]) (*connect.Response[v1.BdPeerDeleteResponse], error) {
	return c.bdPeerDelete.CallUnary(ctx, req)
}

// BdPeerList calls vinbero.v1.BdPeerService.BdPeerList.
func (c *bdPeerServiceClient) BdPeerList(ctx context.Context, req *connect.Request[v1.BdPeerListRequest]) (*connect.Response[v1.BdPeerListResponse], error) {
	return c.bdPeerList.CallUnary(ctx, req)
}

// BdPeerServiceHandler is an implementation of the vinbero.v1.BdPeerService service.
type BdPeerServiceHandler interface {
	BdPeerCreate(context.Context, *connect.Request[v1.BdPeerCreateRequest]) (*connect.Response[v1.BdPeerCreateResponse], error)
	BdPeerDelete(context.Context, *connect.Request[v1.BdPeerDeleteRequest]) (*connect.Response[v1.BdPeerDeleteResponse], error)
	BdPeerList(context.Context, *connect.Request[v1.BdPeerListRequest]) (*connect.Response[v1.BdPeerListResponse], error)
}

// NewBdPeerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBdPeerServiceHandler(svc BdPeerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	bdPeerServiceBdPeerCreateHandler := connect.NewUnaryHandler(
		BdPeerServiceBdPeerCreateProcedure,
		svc.BdPeerCreate,
		connect.WithSchema(bdPeerServiceBdPeerCreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	bdPeerServiceBdPeerDeleteHandler := connect.NewUnaryHandler(
		BdPeerServiceBdPeerDeleteProcedure,
		svc.BdPeerDelete,
		connect.WithSchema(bdPeerServiceBdPeerDeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	bdPeerServiceBdPeerListHandler := connect.NewUnaryHandler(
		BdPeerServiceBdPeerListProcedure,
		svc.BdPeerList,
		connect.WithSchema(bdPeerServiceBdPeerListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vinbero.v1.BdPeerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BdPeerServiceBdPeerCreateProcedure:
			bdPeerServiceBdPeerCreateHandler.ServeHTTP(w, r)
		case BdPeerServiceBdPeerDeleteProcedure:
			bdPeerServiceBdPeerDeleteHandler.ServeHTTP(w, r)
		case BdPeerServiceBdPeerListProcedure:
			bdPeerServiceBdPeerListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBdPeerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBdPeerServiceHandler struct{}

func (UnimplementedBdPeerServiceHandler) BdPeerCreate(context.Context, *connect.Request[v1.BdPeerCreateRequest]) (*connect.Response[v1.BdPeerCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.BdPeerService.BdPeerCreate is not implemented"))
}

func (UnimplementedBdPeerServiceHandler) BdPeerDelete(context.Context, *connect.Request[v1.BdPeerDeleteRequest]) (*connect.Response[v1.BdPeerDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.BdPeerService.BdPeerDelete is not implemented"))
}

func (UnimplementedBdPeerServiceHandler) BdPeerList(context.Context, *connect.Request[v1.BdPeerListRequest]) (*connect.Response[v1.BdPeerListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.BdPeerService.BdPeerList is not implemented"))
}

// NetworkResourceServiceClient is a client for the vinbero.v1.NetworkResourceService service.
type NetworkResourceServiceClient interface {
	VrfCreate(context.Context, *connect.Request[v1.VrfCreateRequest]) (*connect.Response[v1.VrfCreateResponse], error)
	VrfDelete(context.Context, *connect.Request[v1.VrfDeleteRequest]) (*connect.Response[v1.VrfDeleteResponse], error)
	VrfList(context.Context, *connect.Request[v1.VrfListRequest]) (*connect.Response[v1.VrfListResponse], error)
	BridgeCreate(context.Context, *connect.Request[v1.BridgeCreateRequest]) (*connect.Response[v1.BridgeCreateResponse], error)
	BridgeDelete(context.Context, *connect.Request[v1.BridgeDeleteRequest]) (*connect.Response[v1.BridgeDeleteResponse], error)
	BridgeList(context.Context, *connect.Request[v1.BridgeListRequest]) (*connect.Response[v1.BridgeListResponse], error)
}

// NewNetworkResourceServiceClient constructs a client for the vinbero.v1.NetworkResourceService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNetworkResourceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NetworkResourceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &networkResourceServiceClient{
		vrfCreate: connect.NewClient[v1.VrfCreateRequest, v1.VrfCreateResponse](
			httpClient,
			baseURL+NetworkResourceServiceVrfCreateProcedure,
			connect.WithSchema(networkResourceServiceVrfCreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		vrfDelete: connect.NewClient[v1.VrfDeleteRequest, v1.VrfDeleteResponse](
			httpClient,
			baseURL+NetworkResourceServiceVrfDeleteProcedure,
			connect.WithSchema(networkResourceServiceVrfDeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		vrfList: connect.NewClient[v1.VrfListRequest, v1.VrfListResponse](
			httpClient,
			baseURL+NetworkResourceServiceVrfListProcedure,
			connect.WithSchema(networkResourceServiceVrfListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		bridgeCreate: connect.NewClient[v1.BridgeCreateRequest, v1.BridgeCreateResponse](
			httpClient,
			baseURL+NetworkResourceServiceBridgeCreateProcedure,
			connect.WithSchema(networkResourceServiceBridgeCreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		bridgeDelete: connect.NewClient[v1.BridgeDeleteRequest, v1.BridgeDeleteResponse](
			httpClient,
			baseURL+NetworkResourceServiceBridgeDeleteProcedure,
			connect.WithSchema(networkResourceServiceBridgeDeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		bridgeList: connect.NewClient[v1.BridgeListRequest, v1.BridgeListResponse](
			httpClient,
			baseURL+NetworkResourceServiceBridgeListProcedure,
			connect.WithSchema(networkResourceServiceBridgeListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// networkResourceServiceClient implements NetworkResourceServiceClient.
type networkResourceServiceClient struct {
	vrfCreate    *connect.Client[v1.VrfCreateRequest, v1.VrfCreateResponse]
	vrfDelete    *connect.Client[v1.VrfDeleteRequest, v1.VrfDeleteResponse]
	vrfList      *connect.Client[v1.VrfListRequest, v1.VrfListResponse]
	bridgeCreate *connect.Client[v1.BridgeCreateRequest, v1.BridgeCreateResponse]
	bridgeDelete *connect.Client[v1.BridgeDeleteRequest, v1.BridgeDeleteResponse]
	bridgeList   *connect.Client[v1.BridgeListRequest, v1.BridgeListResponse]
}

// VrfCreate calls vinbero.v1.NetworkResourceService.VrfCreate.
func (c *networkResourceServiceClient) VrfCreate(ctx context.Context, req *connect.Request[v1.VrfCreateRequest]) (*connect.Response[v1.VrfCreateResponse], error) {
	return c.vrfCreate.CallUnary(ctx, req)
}

// VrfDelete calls vinbero.v1.NetworkResourceService.VrfDelete.
func (c *networkResourceServiceClient) VrfDelete(ctx context.Context, req *connect.Request[v1.VrfDeleteRequest]) (*connect.Response[v1.VrfDeleteResponse], error) {
	return c.vrfDelete.CallUnary(ctx, req)
}

// VrfList calls vinbero.v1.NetworkResourceService.VrfList.
func (c *networkResourceServiceClient) VrfList(ctx context.Context, req *connect.Request[v1.VrfListRequest]) (*connect.Response[v1.VrfListResponse], error) {
	return c.vrfList.CallUnary(ctx, req)
}

// BridgeCreate calls vinbero.v1.NetworkResourceService.BridgeCreate.
func (c *networkResourceServiceClient) BridgeCreate(ctx context.Context, req *connect.Request[v1.BridgeCreateRequest]) (*connect.Response[v1.BridgeCreateResponse], error) {
	return c.bridgeCreate.CallUnary(ctx, req)
}

// BridgeDelete calls vinbero.v1.NetworkResourceService.BridgeDelete.
func (c *networkResourceServiceClient) BridgeDelete(ctx context.Context, req *connect.Request[v1.BridgeDeleteRequest]) (*connect.Response[v1.BridgeDeleteResponse], error) {
	return c.bridgeDelete.CallUnary(ctx, req)
}

// BridgeList calls vinbero.v1.NetworkResourceService.BridgeList.
func (c *networkResourceServiceClient) BridgeList(ctx context.Context, req *connect.Request[v1.BridgeListRequest]) (*connect.Response[v1.BridgeListResponse], error) {
	return c.bridgeList.CallUnary(ctx, req)
}

// NetworkResourceServiceHandler is an implementation of the vinbero.v1.NetworkResourceService
// service.
type NetworkResourceServiceHandler interface {
	VrfCreate(context.Context, *connect.Request[v1.VrfCreateRequest]) (*connect.Response[v1.VrfCreateResponse], error)
	VrfDelete(context.Context, *connect.Request[v1.VrfDeleteRequest]) (*connect.Response[v1.VrfDeleteResponse], error)
	VrfList(context.Context, *connect.Request[v1.VrfListRequest]) (*connect.Response[v1.VrfListResponse], error)
	BridgeCreate(context.Context, *connect.Request[v1.BridgeCreateRequest]) (*connect.Response[v1.BridgeCreateResponse], error)
	BridgeDelete(context.Context, *connect.Request[v1.BridgeDeleteRequest]) (*connect.Response[v1.BridgeDeleteResponse], error)
	BridgeList(context.Context, *connect.Request[v1.BridgeListRequest]) (*connect.Response[v1.BridgeListResponse], error)
}

// NewNetworkResourceServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNetworkResourceServiceHandler(svc NetworkResourceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	networkResourceServiceVrfCreateHandler := connect.NewUnaryHandler(
		NetworkResourceServiceVrfCreateProcedure,
		svc.VrfCreate,
		connect.WithSchema(networkResourceServiceVrfCreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	networkResourceServiceVrfDeleteHandler := connect.NewUnaryHandler(
		NetworkResourceServiceVrfDeleteProcedure,
		svc.VrfDelete,
		connect.WithSchema(networkResourceServiceVrfDeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	networkResourceServiceVrfListHandler := connect.NewUnaryHandler(
		NetworkResourceServiceVrfListProcedure,
		svc.VrfList,
		connect.WithSchema(networkResourceServiceVrfListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	networkResourceServiceBridgeCreateHandler := connect.NewUnaryHandler(
		NetworkResourceServiceBridgeCreateProcedure,
		svc.BridgeCreate,
		connect.WithSchema(networkResourceServiceBridgeCreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	networkResourceServiceBridgeDeleteHandler := connect.NewUnaryHandler(
		NetworkResourceServiceBridgeDeleteProcedure,
		svc.BridgeDelete,
		connect.WithSchema(networkResourceServiceBridgeDeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	networkResourceServiceBridgeListHandler := connect.NewUnaryHandler(
		NetworkResourceServiceBridgeListProcedure,
		svc.BridgeList,
		connect.WithSchema(networkResourceServiceBridgeListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vinbero.v1.NetworkResourceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NetworkResourceServiceVrfCreateProcedure:
			networkResourceServiceVrfCreateHandler.ServeHTTP(w, r)
		case NetworkResourceServiceVrfDeleteProcedure:
			networkResourceServiceVrfDeleteHandler.ServeHTTP(w, r)
		case NetworkResourceServiceVrfListProcedure:
			networkResourceServiceVrfListHandler.ServeHTTP(w, r)
		case NetworkResourceServiceBridgeCreateProcedure:
			networkResourceServiceBridgeCreateHandler.ServeHTTP(w, r)
		case NetworkResourceServiceBridgeDeleteProcedure:
			networkResourceServiceBridgeDeleteHandler.ServeHTTP(w, r)
		case NetworkResourceServiceBridgeListProcedure:
			networkResourceServiceBridgeListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNetworkResourceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNetworkResourceServiceHandler struct{}

func (UnimplementedNetworkResourceServiceHandler) VrfCreate(context.Context, *connect.Request[v1.VrfCreateRequest]) (*connect.Response[v1.VrfCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.NetworkResourceService.VrfCreate is not implemented"))
}

func (UnimplementedNetworkResourceServiceHandler) VrfDelete(context.Context, *connect.Request[v1.VrfDeleteRequest]) (*connect.Response[v1.VrfDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.NetworkResourceService.VrfDelete is not implemented"))
}

func (UnimplementedNetworkResourceServiceHandler) VrfList(context.Context, *connect.Request[v1.VrfListRequest]) (*connect.Response[v1.VrfListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.NetworkResourceService.VrfList is not implemented"))
}

func (UnimplementedNetworkResourceServiceHandler) BridgeCreate(context.Context, *connect.Request[v1.BridgeCreateRequest]) (*connect.Response[v1.BridgeCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.NetworkResourceService.BridgeCreate is not implemented"))
}

func (UnimplementedNetworkResourceServiceHandler) BridgeDelete(context.Context, *connect.Request[v1.BridgeDeleteRequest]) (*connect.Response[v1.BridgeDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.NetworkResourceService.BridgeDelete is not implemented"))
}

func (UnimplementedNetworkResourceServiceHandler) BridgeList(context.Context, *connect.Request[v1.BridgeListRequest]) (*connect.Response[v1.BridgeListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.NetworkResourceService.BridgeList is not implemented"))
}

// HeadendL2ServiceClient is a client for the vinbero.v1.HeadendL2Service service.
type HeadendL2ServiceClient interface {
	HeadendL2Create(context.Context, *connect.Request[v1.HeadendL2CreateRequest]) (*connect.Response[v1.HeadendL2CreateResponse], error)
	HeadendL2Delete(context.Context, *connect.Request[v1.HeadendL2DeleteRequest]) (*connect.Response[v1.HeadendL2DeleteResponse], error)
	HeadendL2List(context.Context, *connect.Request[v1.HeadendL2ListRequest]) (*connect.Response[v1.HeadendL2ListResponse], error)
	HeadendL2Get(context.Context, *connect.Request[v1.HeadendL2GetRequest]) (*connect.Response[v1.HeadendL2GetResponse], error)
}

// NewHeadendL2ServiceClient constructs a client for the vinbero.v1.HeadendL2Service service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHeadendL2ServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HeadendL2ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &headendL2ServiceClient{
		headendL2Create: connect.NewClient[v1.HeadendL2CreateRequest, v1.HeadendL2CreateResponse](
			httpClient,
			baseURL+HeadendL2ServiceHeadendL2CreateProcedure,
			connect.WithSchema(headendL2ServiceHeadendL2CreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		headendL2Delete: connect.NewClient[v1.HeadendL2DeleteRequest, v1.HeadendL2DeleteResponse](
			httpClient,
			baseURL+HeadendL2ServiceHeadendL2DeleteProcedure,
			connect.WithSchema(headendL2ServiceHeadendL2DeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		headendL2List: connect.NewClient[v1.HeadendL2ListRequest, v1.HeadendL2ListResponse](
			httpClient,
			baseURL+HeadendL2ServiceHeadendL2ListProcedure,
			connect.WithSchema(headendL2ServiceHeadendL2ListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		headendL2Get: connect.NewClient[v1.HeadendL2GetRequest, v1.HeadendL2GetResponse](
			httpClient,
			baseURL+HeadendL2ServiceHeadendL2GetProcedure,
			connect.WithSchema(headendL2ServiceHeadendL2GetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// headendL2ServiceClient implements HeadendL2ServiceClient.
type headendL2ServiceClient struct {
	headendL2Create *connect.Client[v1.HeadendL2CreateRequest, v1.HeadendL2CreateResponse]
	headendL2Delete *connect.Client[v1.HeadendL2DeleteRequest, v1.HeadendL2DeleteResponse]
	headendL2List   *connect.Client[v1.HeadendL2ListRequest, v1.HeadendL2ListResponse]
	headendL2Get    *connect.Client[v1.HeadendL2GetRequest, v1.HeadendL2GetResponse]
}

// HeadendL2Create calls vinbero.v1.HeadendL2Service.HeadendL2Create.
func (c *headendL2ServiceClient) HeadendL2Create(ctx context.Context, req *connect.Request[v1.HeadendL2CreateRequest]) (*connect.Response[v1.HeadendL2CreateResponse], error) {
	return c.headendL2Create.CallUnary(ctx, req)
}

// HeadendL2Delete calls vinbero.v1.HeadendL2Service.HeadendL2Delete.
func (c *headendL2ServiceClient) HeadendL2Delete(ctx context.Context, req *connect.Request[v1.HeadendL2DeleteRequest]) (*connect.Response[v1.HeadendL2DeleteResponse], error) {
	return c.headendL2Delete.CallUnary(ctx, req)
}

// HeadendL2List calls vinbero.v1.HeadendL2Service.HeadendL2List.
func (c *headendL2ServiceClient) HeadendL2List(ctx context.Context, req *connect.Request[v1.HeadendL2ListRequest]) (*connect.Response[v1.HeadendL2ListResponse], error) {
	return c.headendL2List.CallUnary(ctx, req)
}

// HeadendL2Get calls vinbero.v1.HeadendL2Service.HeadendL2Get.
func (c *headendL2ServiceClient) HeadendL2Get(ctx context.Context, req *connect.Request[v1.HeadendL2GetRequest]) (*connect.Response[v1.HeadendL2GetResponse], error) {
	return c.headendL2Get.CallUnary(ctx, req)
}

// HeadendL2ServiceHandler is an implementation of the vinbero.v1.HeadendL2Service service.
type HeadendL2ServiceHandler interface {
	HeadendL2Create(context.Context, *connect.Request[v1.HeadendL2CreateRequest]) (*connect.Response[v1.HeadendL2CreateResponse], error)
	HeadendL2Delete(context.Context, *connect.Request[v1.HeadendL2DeleteRequest]) (*connect.Response[v1.HeadendL2DeleteResponse], error)
	HeadendL2List(context.Context, *connect.Request[v1.HeadendL2ListRequest]) (*connect.Response[v1.HeadendL2ListResponse], error)
	HeadendL2Get(context.Context, *connect.Request[v1.HeadendL2GetRequest]) (*connect.Response[v1.HeadendL2GetResponse], error)
}

// NewHeadendL2ServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHeadendL2ServiceHandler(svc HeadendL2ServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	headendL2ServiceHeadendL2CreateHandler := connect.NewUnaryHandler(
		HeadendL2ServiceHeadendL2CreateProcedure,
		svc.HeadendL2Create,
		connect.WithSchema(headendL2ServiceHeadendL2CreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	headendL2ServiceHeadendL2DeleteHandler := connect.NewUnaryHandler(
		HeadendL2ServiceHeadendL2DeleteProcedure,
		svc.HeadendL2Delete,
		connect.WithSchema(headendL2ServiceHeadendL2DeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	headendL2ServiceHeadendL2ListHandler := connect.NewUnaryHandler(
		HeadendL2ServiceHeadendL2ListProcedure,
		svc.HeadendL2List,
		connect.WithSchema(headendL2ServiceHeadendL2ListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	headendL2ServiceHeadendL2GetHandler := connect.NewUnaryHandler(
		HeadendL2ServiceHeadendL2GetProcedure,
		svc.HeadendL2Get,
		connect.WithSchema(headendL2ServiceHeadendL2GetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vinbero.v1.HeadendL2Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HeadendL2ServiceHeadendL2CreateProcedure:
			headendL2ServiceHeadendL2CreateHandler.ServeHTTP(w, r)
		case HeadendL2ServiceHeadendL2DeleteProcedure:
			headendL2ServiceHeadendL2DeleteHandler.ServeHTTP(w, r)
		case HeadendL2ServiceHeadendL2ListProcedure:
			headendL2ServiceHeadendL2ListHandler.ServeHTTP(w, r)
		case HeadendL2ServiceHeadendL2GetProcedure:
			headendL2ServiceHeadendL2GetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHeadendL2ServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHeadendL2ServiceHandler struct{}

func (UnimplementedHeadendL2ServiceHandler) HeadendL2Create(context.Context, *connect.Request[v1.HeadendL2CreateRequest]) (*connect.Response[v1.HeadendL2CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.HeadendL2Service.HeadendL2Create is not implemented"))
}

func (UnimplementedHeadendL2ServiceHandler) HeadendL2Delete(context.Context, *connect.Request[v1.HeadendL2DeleteRequest]) (*connect.Response[v1.HeadendL2DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.HeadendL2Service.HeadendL2Delete is not implemented"))
}

func (UnimplementedHeadendL2ServiceHandler) HeadendL2List(context.Context, *connect.Request[v1.HeadendL2ListRequest]) (*connect.Response[v1.HeadendL2ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.HeadendL2Service.HeadendL2List is not implemented"))
}

func (UnimplementedHeadendL2ServiceHandler) HeadendL2Get(context.Context, *connect.Request[v1.HeadendL2GetRequest]) (*connect.Response[v1.HeadendL2GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.HeadendL2Service.HeadendL2Get is not implemented"))
}

// StatsServiceClient is a client for the vinbero.v1.StatsService service.
type StatsServiceClient interface {
	StatsShow(context.Context, *connect.Request[v1.StatsShowRequest]) (*connect.Response[v1.StatsShowResponse], error)
	StatsReset(context.Context, *connect.Request[v1.StatsResetRequest]) (*connect.Response[v1.StatsResetResponse], error)
}

// NewStatsServiceClient constructs a client for the vinbero.v1.StatsService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStatsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StatsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &statsServiceClient{
		statsShow: connect.NewClient[v1.StatsShowRequest, v1.StatsShowResponse](
			httpClient,
			baseURL+StatsServiceStatsShowProcedure,
			connect.WithSchema(statsServiceStatsShowMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		statsReset: connect.NewClient[v1.StatsResetRequest, v1.StatsResetResponse](
			httpClient,
			baseURL+StatsServiceStatsResetProcedure,
			connect.WithSchema(statsServiceStatsResetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// statsServiceClient implements StatsServiceClient.
type statsServiceClient struct {
	statsShow  *connect.Client[v1.StatsShowRequest, v1.StatsShowResponse]
	statsReset *connect.Client[v1.StatsResetRequest, v1.StatsResetResponse]
}

// StatsShow calls vinbero.v1.StatsService.StatsShow.
func (c *statsServiceClient) StatsShow(ctx context.Context, req *connect.Request[v1.StatsShowRequest]) (*connect.Response[v1.StatsShowResponse], error) {
	return c.statsShow.CallUnary(ctx, req)
}

// StatsReset calls vinbero.v1.StatsService.StatsReset.
func (c *statsServiceClient) StatsReset(ctx context.Context, req *connect.Request[v1.StatsResetRequest]) (*connect.Response[v1.StatsResetResponse], error) {
	return c.statsReset.CallUnary(ctx, req)
}

// StatsServiceHandler is an implementation of the vinbero.v1.StatsService service.
type StatsServiceHandler interface {
	StatsShow(context.Context, *connect.Request[v1.StatsShowRequest]) (*connect.Response[v1.StatsShowResponse], error)
	StatsReset(context.Context, *connect.Request[v1.StatsResetRequest]) (*connect.Response[v1.StatsResetResponse], error)
}

// NewStatsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStatsServiceHandler(svc StatsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	statsServiceStatsShowHandler := connect.NewUnaryHandler(
		StatsServiceStatsShowProcedure,
		svc.StatsShow,
		connect.WithSchema(statsServiceStatsShowMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	statsServiceStatsResetHandler := connect.NewUnaryHandler(
		StatsServiceStatsResetProcedure,
		svc.StatsReset,
		connect.WithSchema(statsServiceStatsResetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vinbero.v1.StatsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StatsServiceStatsShowProcedure:
			statsServiceStatsShowHandler.ServeHTTP(w, r)
		case StatsServiceStatsResetProcedure:
			statsServiceStatsResetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStatsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStatsServiceHandler struct{}

func (UnimplementedStatsServiceHandler) StatsShow(context.Context, *connect.Request[v1.StatsShowRequest]) (*connect.Response[v1.StatsShowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.StatsService.StatsShow is not implemented"))
}

func (UnimplementedStatsServiceHandler) StatsReset(context.Context, *connect.Request[v1.StatsResetRequest]) (*connect.Response[v1.StatsResetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vinbero.v1.StatsService.StatsReset is not implemented"))
}
