// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfLpmKeyV4 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [4]uint8
}

type BpfLpmKeyV6 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

type BpfSidFunctionEntry struct {
	_            structs.HostLayout
	Action       uint8
	Flavor       uint8
	SrcAddr      [16]uint8
	DstAddr      [16]uint8
	Nexthop      [16]uint8
	ArgSrcOffset uint8
	ArgDstOffset uint8
	Pad          [2]uint8
}

type BpfTransitEntry struct {
	_           structs.HostLayout
	Mode        uint8
	NumSegments uint8
	Pad         [2]uint8
	SrcAddr     [16]uint8
	DstAddr     [16]uint8
	Segments    [10][16]uint8
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	VinberoMain *ebpf.ProgramSpec `ebpf:"vinbero_main"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	SidFunctionMap *ebpf.MapSpec `ebpf:"sid_function_map"`
	TransitV4Map   *ebpf.MapSpec `ebpf:"transit_v4_map"`
	TransitV6Map   *ebpf.MapSpec `ebpf:"transit_v6_map"`
	XdpcapHook     *ebpf.MapSpec `ebpf:"xdpcap_hook"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	SidFunctionMap *ebpf.Map `ebpf:"sid_function_map"`
	TransitV4Map   *ebpf.Map `ebpf:"transit_v4_map"`
	TransitV6Map   *ebpf.Map `ebpf:"transit_v6_map"`
	XdpcapHook     *ebpf.Map `ebpf:"xdpcap_hook"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.SidFunctionMap,
		m.TransitV4Map,
		m.TransitV6Map,
		m.XdpcapHook,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	VinberoMain *ebpf.Program `ebpf:"vinbero_main"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.VinberoMain,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
