// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfBdPeerKey struct {
	_     structs.HostLayout
	BdId  uint16
	Index uint16
}

type BpfBdPeerReverseKey struct {
	_       structs.HostLayout
	BdId    uint16
	SrcAddr [16]uint8
	Pad     [2]uint8
}

type BpfBdPeerReverseVal struct {
	_     structs.HostLayout
	Index uint16
}

type BpfDx2vEntry struct {
	_   structs.HostLayout
	Oif uint32
}

type BpfDx2vKey struct {
	_       structs.HostLayout
	TableId uint16
	VlanId  uint16
}

type BpfFdbEntry struct {
	_         structs.HostLayout
	Oif       uint32
	IsRemote  uint8
	IsStatic  uint8
	PeerIndex uint16
	BdId      uint16
	Pad       [2]uint8
	LastSeen  uint64
}

type BpfFdbKey struct {
	_    structs.HostLayout
	BdId uint16
	Mac  [6]uint8
}

type BpfHeadendEntry struct {
	_           structs.HostLayout
	Mode        uint8
	NumSegments uint8
	Pad         [2]uint8
	SrcAddr     [16]uint8
	DstAddr     [16]uint8
	Segments    [10][16]uint8
	BdId        uint16
	ArgsOffset  uint8
	PadGtp      uint8
}

type BpfHeadendL2Key struct {
	_       structs.HostLayout
	Ifindex uint32
	VlanId  uint16
	Pad     [2]uint8
}

type BpfLpmKeyV4 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [4]uint8
}

type BpfLpmKeyV6 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

type BpfScratchBuf struct {
	_    structs.HostLayout
	Data [224]uint8
}

type BpfSidAuxEntry struct {
	_       structs.HostLayout
	Nexthop struct {
		_       structs.HostLayout
		Nexthop [16]uint8
	}
	_ [184]byte
}

type BpfSidFunctionEntry struct {
	_          structs.HostLayout
	Action     uint8
	Flavor     uint8
	HasAux     uint8
	Pad        uint8
	VrfIfindex uint32
	AuxIndex   uint32
}

type BpfStatsEntry struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
}

type BpfTailcallCtx struct {
	_            structs.HostLayout
	L3Offset     uint16
	DispatchType uint8
	InnerProto   uint8
	SidEntry     BpfSidFunctionEntry
	_            [188]byte
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	TailcallEndpointEnd           *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end"`
	TailcallEndpointEndB6         *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_b6"`
	TailcallEndpointEndB6Encaps   *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_b6_encaps"`
	TailcallEndpointEndDt2        *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_dt2"`
	TailcallEndpointEndDt4        *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_dt4"`
	TailcallEndpointEndDt46       *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_dt46"`
	TailcallEndpointEndDt6        *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_dt6"`
	TailcallEndpointEndDx2        *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_dx2"`
	TailcallEndpointEndDx2v       *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_dx2v"`
	TailcallEndpointEndDx4        *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_dx4"`
	TailcallEndpointEndDx6        *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_dx6"`
	TailcallEndpointEndM_gtp4E    *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_m_gtp4_e"`
	TailcallEndpointEndM_gtp6D    *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_m_gtp6_d"`
	TailcallEndpointEndM_gtp6D_di *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_m_gtp6_d_di"`
	TailcallEndpointEndM_gtp6E    *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_m_gtp6_e"`
	TailcallEndpointEndT          *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_t"`
	TailcallEndpointEndX          *ebpf.ProgramSpec `ebpf:"tailcall_endpoint_end_x"`
	TailcallHeadendV4H_encaps     *ebpf.ProgramSpec `ebpf:"tailcall_headend_v4_h_encaps"`
	TailcallHeadendV4H_encapsRed  *ebpf.ProgramSpec `ebpf:"tailcall_headend_v4_h_encaps_red"`
	TailcallHeadendV4H_mGtp4D     *ebpf.ProgramSpec `ebpf:"tailcall_headend_v4_h_m_gtp4_d"`
	TailcallHeadendV6H_encaps     *ebpf.ProgramSpec `ebpf:"tailcall_headend_v6_h_encaps"`
	TailcallHeadendV6H_encapsRed  *ebpf.ProgramSpec `ebpf:"tailcall_headend_v6_h_encaps_red"`
	TailcallHeadendV6H_insert     *ebpf.ProgramSpec `ebpf:"tailcall_headend_v6_h_insert"`
	TailcallHeadendV6H_insertRed  *ebpf.ProgramSpec `ebpf:"tailcall_headend_v6_h_insert_red"`
	VinberoMain                   *ebpf.ProgramSpec `ebpf:"vinbero_main"`
	VinberoTcIngress              *ebpf.ProgramSpec `ebpf:"vinbero_tc_ingress"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	BdPeerMap        *ebpf.MapSpec `ebpf:"bd_peer_map"`
	BdPeerReverseMap *ebpf.MapSpec `ebpf:"bd_peer_reverse_map"`
	Dx2vMap          *ebpf.MapSpec `ebpf:"dx2v_map"`
	FdbMap           *ebpf.MapSpec `ebpf:"fdb_map"`
	HeadendL2Map     *ebpf.MapSpec `ebpf:"headend_l2_map"`
	HeadendV4Map     *ebpf.MapSpec `ebpf:"headend_v4_map"`
	HeadendV4Progs   *ebpf.MapSpec `ebpf:"headend_v4_progs"`
	HeadendV6Map     *ebpf.MapSpec `ebpf:"headend_v6_map"`
	HeadendV6Progs   *ebpf.MapSpec `ebpf:"headend_v6_progs"`
	ScratchMap       *ebpf.MapSpec `ebpf:"scratch_map"`
	SidAuxMap        *ebpf.MapSpec `ebpf:"sid_aux_map"`
	SidEndpointProgs *ebpf.MapSpec `ebpf:"sid_endpoint_progs"`
	SidFunctionMap   *ebpf.MapSpec `ebpf:"sid_function_map"`
	StatsMap         *ebpf.MapSpec `ebpf:"stats_map"`
	TailcallCtxMap   *ebpf.MapSpec `ebpf:"tailcall_ctx_map"`
	XdpcapHook       *ebpf.MapSpec `ebpf:"xdpcap_hook"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
	EnableStats  *ebpf.VariableSpec `ebpf:"enable_stats"`
	EnableXdpcap *ebpf.VariableSpec `ebpf:"enable_xdpcap"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	BdPeerMap        *ebpf.Map `ebpf:"bd_peer_map"`
	BdPeerReverseMap *ebpf.Map `ebpf:"bd_peer_reverse_map"`
	Dx2vMap          *ebpf.Map `ebpf:"dx2v_map"`
	FdbMap           *ebpf.Map `ebpf:"fdb_map"`
	HeadendL2Map     *ebpf.Map `ebpf:"headend_l2_map"`
	HeadendV4Map     *ebpf.Map `ebpf:"headend_v4_map"`
	HeadendV4Progs   *ebpf.Map `ebpf:"headend_v4_progs"`
	HeadendV6Map     *ebpf.Map `ebpf:"headend_v6_map"`
	HeadendV6Progs   *ebpf.Map `ebpf:"headend_v6_progs"`
	ScratchMap       *ebpf.Map `ebpf:"scratch_map"`
	SidAuxMap        *ebpf.Map `ebpf:"sid_aux_map"`
	SidEndpointProgs *ebpf.Map `ebpf:"sid_endpoint_progs"`
	SidFunctionMap   *ebpf.Map `ebpf:"sid_function_map"`
	StatsMap         *ebpf.Map `ebpf:"stats_map"`
	TailcallCtxMap   *ebpf.Map `ebpf:"tailcall_ctx_map"`
	XdpcapHook       *ebpf.Map `ebpf:"xdpcap_hook"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.BdPeerMap,
		m.BdPeerReverseMap,
		m.Dx2vMap,
		m.FdbMap,
		m.HeadendL2Map,
		m.HeadendV4Map,
		m.HeadendV4Progs,
		m.HeadendV6Map,
		m.HeadendV6Progs,
		m.ScratchMap,
		m.SidAuxMap,
		m.SidEndpointProgs,
		m.SidFunctionMap,
		m.StatsMap,
		m.TailcallCtxMap,
		m.XdpcapHook,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
	EnableStats  *ebpf.Variable `ebpf:"enable_stats"`
	EnableXdpcap *ebpf.Variable `ebpf:"enable_xdpcap"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	TailcallEndpointEnd           *ebpf.Program `ebpf:"tailcall_endpoint_end"`
	TailcallEndpointEndB6         *ebpf.Program `ebpf:"tailcall_endpoint_end_b6"`
	TailcallEndpointEndB6Encaps   *ebpf.Program `ebpf:"tailcall_endpoint_end_b6_encaps"`
	TailcallEndpointEndDt2        *ebpf.Program `ebpf:"tailcall_endpoint_end_dt2"`
	TailcallEndpointEndDt4        *ebpf.Program `ebpf:"tailcall_endpoint_end_dt4"`
	TailcallEndpointEndDt46       *ebpf.Program `ebpf:"tailcall_endpoint_end_dt46"`
	TailcallEndpointEndDt6        *ebpf.Program `ebpf:"tailcall_endpoint_end_dt6"`
	TailcallEndpointEndDx2        *ebpf.Program `ebpf:"tailcall_endpoint_end_dx2"`
	TailcallEndpointEndDx2v       *ebpf.Program `ebpf:"tailcall_endpoint_end_dx2v"`
	TailcallEndpointEndDx4        *ebpf.Program `ebpf:"tailcall_endpoint_end_dx4"`
	TailcallEndpointEndDx6        *ebpf.Program `ebpf:"tailcall_endpoint_end_dx6"`
	TailcallEndpointEndM_gtp4E    *ebpf.Program `ebpf:"tailcall_endpoint_end_m_gtp4_e"`
	TailcallEndpointEndM_gtp6D    *ebpf.Program `ebpf:"tailcall_endpoint_end_m_gtp6_d"`
	TailcallEndpointEndM_gtp6D_di *ebpf.Program `ebpf:"tailcall_endpoint_end_m_gtp6_d_di"`
	TailcallEndpointEndM_gtp6E    *ebpf.Program `ebpf:"tailcall_endpoint_end_m_gtp6_e"`
	TailcallEndpointEndT          *ebpf.Program `ebpf:"tailcall_endpoint_end_t"`
	TailcallEndpointEndX          *ebpf.Program `ebpf:"tailcall_endpoint_end_x"`
	TailcallHeadendV4H_encaps     *ebpf.Program `ebpf:"tailcall_headend_v4_h_encaps"`
	TailcallHeadendV4H_encapsRed  *ebpf.Program `ebpf:"tailcall_headend_v4_h_encaps_red"`
	TailcallHeadendV4H_mGtp4D     *ebpf.Program `ebpf:"tailcall_headend_v4_h_m_gtp4_d"`
	TailcallHeadendV6H_encaps     *ebpf.Program `ebpf:"tailcall_headend_v6_h_encaps"`
	TailcallHeadendV6H_encapsRed  *ebpf.Program `ebpf:"tailcall_headend_v6_h_encaps_red"`
	TailcallHeadendV6H_insert     *ebpf.Program `ebpf:"tailcall_headend_v6_h_insert"`
	TailcallHeadendV6H_insertRed  *ebpf.Program `ebpf:"tailcall_headend_v6_h_insert_red"`
	VinberoMain                   *ebpf.Program `ebpf:"vinbero_main"`
	VinberoTcIngress              *ebpf.Program `ebpf:"vinbero_tc_ingress"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.TailcallEndpointEnd,
		p.TailcallEndpointEndB6,
		p.TailcallEndpointEndB6Encaps,
		p.TailcallEndpointEndDt2,
		p.TailcallEndpointEndDt4,
		p.TailcallEndpointEndDt46,
		p.TailcallEndpointEndDt6,
		p.TailcallEndpointEndDx2,
		p.TailcallEndpointEndDx2v,
		p.TailcallEndpointEndDx4,
		p.TailcallEndpointEndDx6,
		p.TailcallEndpointEndM_gtp4E,
		p.TailcallEndpointEndM_gtp6D,
		p.TailcallEndpointEndM_gtp6D_di,
		p.TailcallEndpointEndM_gtp6E,
		p.TailcallEndpointEndT,
		p.TailcallEndpointEndX,
		p.TailcallHeadendV4H_encaps,
		p.TailcallHeadendV4H_encapsRed,
		p.TailcallHeadendV4H_mGtp4D,
		p.TailcallHeadendV6H_encaps,
		p.TailcallHeadendV6H_encapsRed,
		p.TailcallHeadendV6H_insert,
		p.TailcallHeadendV6H_insertRed,
		p.VinberoMain,
		p.VinberoTcIngress,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
