// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfBdPeerKey struct {
	_     structs.HostLayout
	BdId  uint16
	Index uint16
}

type BpfBdPeerReverseKey struct {
	_       structs.HostLayout
	BdId    uint16
	SrcAddr [16]uint8
	Pad     [2]uint8
}

type BpfBdPeerReverseVal struct {
	_     structs.HostLayout
	Index uint16
}

type BpfFdbEntry struct {
	_         structs.HostLayout
	Oif       uint32
	IsRemote  uint8
	Pad       uint8
	PeerIndex uint16
	BdId      uint16
	Pad2      [2]uint8
}

type BpfFdbKey struct {
	_    structs.HostLayout
	BdId uint16
	Mac  [6]uint8
}

type BpfHeadendEntry struct {
	_           structs.HostLayout
	Mode        uint8
	NumSegments uint8
	Pad         [2]uint8
	SrcAddr     [16]uint8
	DstAddr     [16]uint8
	Segments    [10][16]uint8
	BdId        uint16
}

type BpfHeadendL2Key struct {
	_       structs.HostLayout
	Ifindex uint32
	VlanId  uint16
	Pad     [2]uint8
}

type BpfLpmKeyV4 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [4]uint8
}

type BpfLpmKeyV6 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

type BpfSidFunctionEntry struct {
	_             structs.HostLayout
	Action        uint8
	Flavor        uint8
	SrcAddr       [16]uint8
	DstAddr       [16]uint8
	Nexthop       [16]uint8
	ArgSrcOffset  uint8
	ArgDstOffset  uint8
	VrfIfindex    uint32
	BdId          uint16
	PadSid        uint16
	BridgeIfindex uint32
}

type BpfStatsEntry struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	VinberoMain      *ebpf.ProgramSpec `ebpf:"vinbero_main"`
	VinberoTcIngress *ebpf.ProgramSpec `ebpf:"vinbero_tc_ingress"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	BdPeerMap        *ebpf.MapSpec `ebpf:"bd_peer_map"`
	BdPeerReverseMap *ebpf.MapSpec `ebpf:"bd_peer_reverse_map"`
	EndB6PolicyMap   *ebpf.MapSpec `ebpf:"end_b6_policy_map"`
	FdbMap           *ebpf.MapSpec `ebpf:"fdb_map"`
	HeadendL2Map     *ebpf.MapSpec `ebpf:"headend_l2_map"`
	HeadendV4Map     *ebpf.MapSpec `ebpf:"headend_v4_map"`
	HeadendV6Map     *ebpf.MapSpec `ebpf:"headend_v6_map"`
	SidFunctionMap   *ebpf.MapSpec `ebpf:"sid_function_map"`
	StatsMap         *ebpf.MapSpec `ebpf:"stats_map"`
	XdpcapHook       *ebpf.MapSpec `ebpf:"xdpcap_hook"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
	EnableStats  *ebpf.VariableSpec `ebpf:"enable_stats"`
	EnableXdpcap *ebpf.VariableSpec `ebpf:"enable_xdpcap"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	BdPeerMap        *ebpf.Map `ebpf:"bd_peer_map"`
	BdPeerReverseMap *ebpf.Map `ebpf:"bd_peer_reverse_map"`
	EndB6PolicyMap   *ebpf.Map `ebpf:"end_b6_policy_map"`
	FdbMap           *ebpf.Map `ebpf:"fdb_map"`
	HeadendL2Map     *ebpf.Map `ebpf:"headend_l2_map"`
	HeadendV4Map     *ebpf.Map `ebpf:"headend_v4_map"`
	HeadendV6Map     *ebpf.Map `ebpf:"headend_v6_map"`
	SidFunctionMap   *ebpf.Map `ebpf:"sid_function_map"`
	StatsMap         *ebpf.Map `ebpf:"stats_map"`
	XdpcapHook       *ebpf.Map `ebpf:"xdpcap_hook"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.BdPeerMap,
		m.BdPeerReverseMap,
		m.EndB6PolicyMap,
		m.FdbMap,
		m.HeadendL2Map,
		m.HeadendV4Map,
		m.HeadendV6Map,
		m.SidFunctionMap,
		m.StatsMap,
		m.XdpcapHook,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
	EnableStats  *ebpf.Variable `ebpf:"enable_stats"`
	EnableXdpcap *ebpf.Variable `ebpf:"enable_xdpcap"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	VinberoMain      *ebpf.Program `ebpf:"vinbero_main"`
	VinberoTcIngress *ebpf.Program `ebpf:"vinbero_tc_ingress"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.VinberoMain,
		p.VinberoTcIngress,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
