// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: vinbero/v1/bgp_route.proto

package vinberov1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BgpRouteService_BgpAdvertiseVpn_FullMethodName      = "/vinbero.v1.BgpRouteService/BgpAdvertiseVpn"
	BgpRouteService_BgpAdvertiseUnicast_FullMethodName  = "/vinbero.v1.BgpRouteService/BgpAdvertiseUnicast"
	BgpRouteService_BgpWithdraw_FullMethodName          = "/vinbero.v1.BgpRouteService/BgpWithdraw"
	BgpRouteService_BgpAdvertiseSrPolicy_FullMethodName = "/vinbero.v1.BgpRouteService/BgpAdvertiseSrPolicy"
	BgpRouteService_BgpWithdrawSrPolicy_FullMethodName  = "/vinbero.v1.BgpRouteService/BgpWithdrawSrPolicy"
	BgpRouteService_BgpAdvertiseEvpnMac_FullMethodName  = "/vinbero.v1.BgpRouteService/BgpAdvertiseEvpnMac"
	BgpRouteService_BgpWithdrawEvpnMac_FullMethodName   = "/vinbero.v1.BgpRouteService/BgpWithdrawEvpnMac"
	BgpRouteService_BgpAdvertiseEvpnImet_FullMethodName = "/vinbero.v1.BgpRouteService/BgpAdvertiseEvpnImet"
	BgpRouteService_BgpWithdrawEvpnImet_FullMethodName  = "/vinbero.v1.BgpRouteService/BgpWithdrawEvpnImet"
	BgpRouteService_BgpAdvertiseEvpnEs_FullMethodName   = "/vinbero.v1.BgpRouteService/BgpAdvertiseEvpnEs"
	BgpRouteService_BgpWithdrawEvpnEs_FullMethodName    = "/vinbero.v1.BgpRouteService/BgpWithdrawEvpnEs"
	BgpRouteService_BgpAdvertiseMup_FullMethodName      = "/vinbero.v1.BgpRouteService/BgpAdvertiseMup"
	BgpRouteService_BgpWithdrawMup_FullMethodName       = "/vinbero.v1.BgpRouteService/BgpWithdrawMup"
)

// BgpRouteServiceClient is the client API for BgpRouteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BgpRouteServiceClient interface {
	BgpAdvertiseVpn(ctx context.Context, in *BgpAdvertiseVpnRequest, opts ...grpc.CallOption) (*BgpAdvertiseVpnResponse, error)
	BgpAdvertiseUnicast(ctx context.Context, in *BgpAdvertiseUnicastRequest, opts ...grpc.CallOption) (*BgpAdvertiseUnicastResponse, error)
	BgpWithdraw(ctx context.Context, in *BgpWithdrawRequest, opts ...grpc.CallOption) (*BgpWithdrawResponse, error)
	BgpAdvertiseSrPolicy(ctx context.Context, in *BgpAdvertiseSrPolicyRequest, opts ...grpc.CallOption) (*BgpAdvertiseSrPolicyResponse, error)
	BgpWithdrawSrPolicy(ctx context.Context, in *BgpWithdrawSrPolicyRequest, opts ...grpc.CallOption) (*BgpWithdrawSrPolicyResponse, error)
	BgpAdvertiseEvpnMac(ctx context.Context, in *BgpAdvertiseEvpnMacRequest, opts ...grpc.CallOption) (*BgpAdvertiseEvpnMacResponse, error)
	BgpWithdrawEvpnMac(ctx context.Context, in *BgpWithdrawEvpnMacRequest, opts ...grpc.CallOption) (*BgpWithdrawEvpnMacResponse, error)
	BgpAdvertiseEvpnImet(ctx context.Context, in *BgpAdvertiseEvpnImetRequest, opts ...grpc.CallOption) (*BgpAdvertiseEvpnImetResponse, error)
	BgpWithdrawEvpnImet(ctx context.Context, in *BgpWithdrawEvpnImetRequest, opts ...grpc.CallOption) (*BgpWithdrawEvpnImetResponse, error)
	BgpAdvertiseEvpnEs(ctx context.Context, in *BgpAdvertiseEvpnEsRequest, opts ...grpc.CallOption) (*BgpAdvertiseEvpnEsResponse, error)
	BgpWithdrawEvpnEs(ctx context.Context, in *BgpWithdrawEvpnEsRequest, opts ...grpc.CallOption) (*BgpWithdrawEvpnEsResponse, error)
	BgpAdvertiseMup(ctx context.Context, in *BgpAdvertiseMupRequest, opts ...grpc.CallOption) (*BgpAdvertiseMupResponse, error)
	BgpWithdrawMup(ctx context.Context, in *BgpWithdrawMupRequest, opts ...grpc.CallOption) (*BgpWithdrawMupResponse, error)
}

type bgpRouteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBgpRouteServiceClient(cc grpc.ClientConnInterface) BgpRouteServiceClient {
	return &bgpRouteServiceClient{cc}
}

func (c *bgpRouteServiceClient) BgpAdvertiseVpn(ctx context.Context, in *BgpAdvertiseVpnRequest, opts ...grpc.CallOption) (*BgpAdvertiseVpnResponse, error) {
	out := new(BgpAdvertiseVpnResponse)
	err := c.cc.Invoke(ctx, BgpRouteService_BgpAdvertiseVpn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpRouteServiceClient) BgpAdvertiseUnicast(ctx context.Context, in *BgpAdvertiseUnicastRequest, opts ...grpc.CallOption) (*BgpAdvertiseUnicastResponse, error) {
	out := new(BgpAdvertiseUnicastResponse)
	err := c.cc.Invoke(ctx, BgpRouteService_BgpAdvertiseUnicast_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpRouteServiceClient) BgpWithdraw(ctx context.Context, in *BgpWithdrawRequest, opts ...grpc.CallOption) (*BgpWithdrawResponse, error) {
	out := new(BgpWithdrawResponse)
	err := c.cc.Invoke(ctx, BgpRouteService_BgpWithdraw_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpRouteServiceClient) BgpAdvertiseSrPolicy(ctx context.Context, in *BgpAdvertiseSrPolicyRequest, opts ...grpc.CallOption) (*BgpAdvertiseSrPolicyResponse, error) {
	out := new(BgpAdvertiseSrPolicyResponse)
	err := c.cc.Invoke(ctx, BgpRouteService_BgpAdvertiseSrPolicy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpRouteServiceClient) BgpWithdrawSrPolicy(ctx context.Context, in *BgpWithdrawSrPolicyRequest, opts ...grpc.CallOption) (*BgpWithdrawSrPolicyResponse, error) {
	out := new(BgpWithdrawSrPolicyResponse)
	err := c.cc.Invoke(ctx, BgpRouteService_BgpWithdrawSrPolicy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpRouteServiceClient) BgpAdvertiseEvpnMac(ctx context.Context, in *BgpAdvertiseEvpnMacRequest, opts ...grpc.CallOption) (*BgpAdvertiseEvpnMacResponse, error) {
	out := new(BgpAdvertiseEvpnMacResponse)
	err := c.cc.Invoke(ctx, BgpRouteService_BgpAdvertiseEvpnMac_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpRouteServiceClient) BgpWithdrawEvpnMac(ctx context.Context, in *BgpWithdrawEvpnMacRequest, opts ...grpc.CallOption) (*BgpWithdrawEvpnMacResponse, error) {
	out := new(BgpWithdrawEvpnMacResponse)
	err := c.cc.Invoke(ctx, BgpRouteService_BgpWithdrawEvpnMac_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpRouteServiceClient) BgpAdvertiseEvpnImet(ctx context.Context, in *BgpAdvertiseEvpnImetRequest, opts ...grpc.CallOption) (*BgpAdvertiseEvpnImetResponse, error) {
	out := new(BgpAdvertiseEvpnImetResponse)
	err := c.cc.Invoke(ctx, BgpRouteService_BgpAdvertiseEvpnImet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpRouteServiceClient) BgpWithdrawEvpnImet(ctx context.Context, in *BgpWithdrawEvpnImetRequest, opts ...grpc.CallOption) (*BgpWithdrawEvpnImetResponse, error) {
	out := new(BgpWithdrawEvpnImetResponse)
	err := c.cc.Invoke(ctx, BgpRouteService_BgpWithdrawEvpnImet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpRouteServiceClient) BgpAdvertiseEvpnEs(ctx context.Context, in *BgpAdvertiseEvpnEsRequest, opts ...grpc.CallOption) (*BgpAdvertiseEvpnEsResponse, error) {
	out := new(BgpAdvertiseEvpnEsResponse)
	err := c.cc.Invoke(ctx, BgpRouteService_BgpAdvertiseEvpnEs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpRouteServiceClient) BgpWithdrawEvpnEs(ctx context.Context, in *BgpWithdrawEvpnEsRequest, opts ...grpc.CallOption) (*BgpWithdrawEvpnEsResponse, error) {
	out := new(BgpWithdrawEvpnEsResponse)
	err := c.cc.Invoke(ctx, BgpRouteService_BgpWithdrawEvpnEs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpRouteServiceClient) BgpAdvertiseMup(ctx context.Context, in *BgpAdvertiseMupRequest, opts ...grpc.CallOption) (*BgpAdvertiseMupResponse, error) {
	out := new(BgpAdvertiseMupResponse)
	err := c.cc.Invoke(ctx, BgpRouteService_BgpAdvertiseMup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpRouteServiceClient) BgpWithdrawMup(ctx context.Context, in *BgpWithdrawMupRequest, opts ...grpc.CallOption) (*BgpWithdrawMupResponse, error) {
	out := new(BgpWithdrawMupResponse)
	err := c.cc.Invoke(ctx, BgpRouteService_BgpWithdrawMup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BgpRouteServiceServer is the server API for BgpRouteService service.
// All implementations should embed UnimplementedBgpRouteServiceServer
// for forward compatibility
type BgpRouteServiceServer interface {
	BgpAdvertiseVpn(context.Context, *BgpAdvertiseVpnRequest) (*BgpAdvertiseVpnResponse, error)
	BgpAdvertiseUnicast(context.Context, *BgpAdvertiseUnicastRequest) (*BgpAdvertiseUnicastResponse, error)
	BgpWithdraw(context.Context, *BgpWithdrawRequest) (*BgpWithdrawResponse, error)
	BgpAdvertiseSrPolicy(context.Context, *BgpAdvertiseSrPolicyRequest) (*BgpAdvertiseSrPolicyResponse, error)
	BgpWithdrawSrPolicy(context.Context, *BgpWithdrawSrPolicyRequest) (*BgpWithdrawSrPolicyResponse, error)
	BgpAdvertiseEvpnMac(context.Context, *BgpAdvertiseEvpnMacRequest) (*BgpAdvertiseEvpnMacResponse, error)
	BgpWithdrawEvpnMac(context.Context, *BgpWithdrawEvpnMacRequest) (*BgpWithdrawEvpnMacResponse, error)
	BgpAdvertiseEvpnImet(context.Context, *BgpAdvertiseEvpnImetRequest) (*BgpAdvertiseEvpnImetResponse, error)
	BgpWithdrawEvpnImet(context.Context, *BgpWithdrawEvpnImetRequest) (*BgpWithdrawEvpnImetResponse, error)
	BgpAdvertiseEvpnEs(context.Context, *BgpAdvertiseEvpnEsRequest) (*BgpAdvertiseEvpnEsResponse, error)
	BgpWithdrawEvpnEs(context.Context, *BgpWithdrawEvpnEsRequest) (*BgpWithdrawEvpnEsResponse, error)
	BgpAdvertiseMup(context.Context, *BgpAdvertiseMupRequest) (*BgpAdvertiseMupResponse, error)
	BgpWithdrawMup(context.Context, *BgpWithdrawMupRequest) (*BgpWithdrawMupResponse, error)
}

// UnimplementedBgpRouteServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBgpRouteServiceServer struct {
}

func (UnimplementedBgpRouteServiceServer) BgpAdvertiseVpn(context.Context, *BgpAdvertiseVpnRequest) (*BgpAdvertiseVpnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgpAdvertiseVpn not implemented")
}
func (UnimplementedBgpRouteServiceServer) BgpAdvertiseUnicast(context.Context, *BgpAdvertiseUnicastRequest) (*BgpAdvertiseUnicastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgpAdvertiseUnicast not implemented")
}
func (UnimplementedBgpRouteServiceServer) BgpWithdraw(context.Context, *BgpWithdrawRequest) (*BgpWithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgpWithdraw not implemented")
}
func (UnimplementedBgpRouteServiceServer) BgpAdvertiseSrPolicy(context.Context, *BgpAdvertiseSrPolicyRequest) (*BgpAdvertiseSrPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgpAdvertiseSrPolicy not implemented")
}
func (UnimplementedBgpRouteServiceServer) BgpWithdrawSrPolicy(context.Context, *BgpWithdrawSrPolicyRequest) (*BgpWithdrawSrPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgpWithdrawSrPolicy not implemented")
}
func (UnimplementedBgpRouteServiceServer) BgpAdvertiseEvpnMac(context.Context, *BgpAdvertiseEvpnMacRequest) (*BgpAdvertiseEvpnMacResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgpAdvertiseEvpnMac not implemented")
}
func (UnimplementedBgpRouteServiceServer) BgpWithdrawEvpnMac(context.Context, *BgpWithdrawEvpnMacRequest) (*BgpWithdrawEvpnMacResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgpWithdrawEvpnMac not implemented")
}
func (UnimplementedBgpRouteServiceServer) BgpAdvertiseEvpnImet(context.Context, *BgpAdvertiseEvpnImetRequest) (*BgpAdvertiseEvpnImetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgpAdvertiseEvpnImet not implemented")
}
func (UnimplementedBgpRouteServiceServer) BgpWithdrawEvpnImet(context.Context, *BgpWithdrawEvpnImetRequest) (*BgpWithdrawEvpnImetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgpWithdrawEvpnImet not implemented")
}
func (UnimplementedBgpRouteServiceServer) BgpAdvertiseEvpnEs(context.Context, *BgpAdvertiseEvpnEsRequest) (*BgpAdvertiseEvpnEsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgpAdvertiseEvpnEs not implemented")
}
func (UnimplementedBgpRouteServiceServer) BgpWithdrawEvpnEs(context.Context, *BgpWithdrawEvpnEsRequest) (*BgpWithdrawEvpnEsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgpWithdrawEvpnEs not implemented")
}
func (UnimplementedBgpRouteServiceServer) BgpAdvertiseMup(context.Context, *BgpAdvertiseMupRequest) (*BgpAdvertiseMupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgpAdvertiseMup not implemented")
}
func (UnimplementedBgpRouteServiceServer) BgpWithdrawMup(context.Context, *BgpWithdrawMupRequest) (*BgpWithdrawMupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgpWithdrawMup not implemented")
}

// UnsafeBgpRouteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BgpRouteServiceServer will
// result in compilation errors.
type UnsafeBgpRouteServiceServer interface {
	mustEmbedUnimplementedBgpRouteServiceServer()
}

func RegisterBgpRouteServiceServer(s grpc.ServiceRegistrar, srv BgpRouteServiceServer) {
	s.RegisterService(&BgpRouteService_ServiceDesc, srv)
}

func _BgpRouteService_BgpAdvertiseVpn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgpAdvertiseVpnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpRouteServiceServer).BgpAdvertiseVpn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpRouteService_BgpAdvertiseVpn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpRouteServiceServer).BgpAdvertiseVpn(ctx, req.(*BgpAdvertiseVpnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpRouteService_BgpAdvertiseUnicast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgpAdvertiseUnicastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpRouteServiceServer).BgpAdvertiseUnicast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpRouteService_BgpAdvertiseUnicast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpRouteServiceServer).BgpAdvertiseUnicast(ctx, req.(*BgpAdvertiseUnicastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpRouteService_BgpWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgpWithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpRouteServiceServer).BgpWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpRouteService_BgpWithdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpRouteServiceServer).BgpWithdraw(ctx, req.(*BgpWithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpRouteService_BgpAdvertiseSrPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgpAdvertiseSrPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpRouteServiceServer).BgpAdvertiseSrPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpRouteService_BgpAdvertiseSrPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpRouteServiceServer).BgpAdvertiseSrPolicy(ctx, req.(*BgpAdvertiseSrPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpRouteService_BgpWithdrawSrPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgpWithdrawSrPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpRouteServiceServer).BgpWithdrawSrPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpRouteService_BgpWithdrawSrPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpRouteServiceServer).BgpWithdrawSrPolicy(ctx, req.(*BgpWithdrawSrPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpRouteService_BgpAdvertiseEvpnMac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgpAdvertiseEvpnMacRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpRouteServiceServer).BgpAdvertiseEvpnMac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpRouteService_BgpAdvertiseEvpnMac_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpRouteServiceServer).BgpAdvertiseEvpnMac(ctx, req.(*BgpAdvertiseEvpnMacRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpRouteService_BgpWithdrawEvpnMac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgpWithdrawEvpnMacRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpRouteServiceServer).BgpWithdrawEvpnMac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpRouteService_BgpWithdrawEvpnMac_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpRouteServiceServer).BgpWithdrawEvpnMac(ctx, req.(*BgpWithdrawEvpnMacRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpRouteService_BgpAdvertiseEvpnImet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgpAdvertiseEvpnImetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpRouteServiceServer).BgpAdvertiseEvpnImet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpRouteService_BgpAdvertiseEvpnImet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpRouteServiceServer).BgpAdvertiseEvpnImet(ctx, req.(*BgpAdvertiseEvpnImetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpRouteService_BgpWithdrawEvpnImet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgpWithdrawEvpnImetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpRouteServiceServer).BgpWithdrawEvpnImet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpRouteService_BgpWithdrawEvpnImet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpRouteServiceServer).BgpWithdrawEvpnImet(ctx, req.(*BgpWithdrawEvpnImetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpRouteService_BgpAdvertiseEvpnEs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgpAdvertiseEvpnEsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpRouteServiceServer).BgpAdvertiseEvpnEs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpRouteService_BgpAdvertiseEvpnEs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpRouteServiceServer).BgpAdvertiseEvpnEs(ctx, req.(*BgpAdvertiseEvpnEsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpRouteService_BgpWithdrawEvpnEs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgpWithdrawEvpnEsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpRouteServiceServer).BgpWithdrawEvpnEs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpRouteService_BgpWithdrawEvpnEs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpRouteServiceServer).BgpWithdrawEvpnEs(ctx, req.(*BgpWithdrawEvpnEsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpRouteService_BgpAdvertiseMup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgpAdvertiseMupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpRouteServiceServer).BgpAdvertiseMup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpRouteService_BgpAdvertiseMup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpRouteServiceServer).BgpAdvertiseMup(ctx, req.(*BgpAdvertiseMupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpRouteService_BgpWithdrawMup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgpWithdrawMupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpRouteServiceServer).BgpWithdrawMup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpRouteService_BgpWithdrawMup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpRouteServiceServer).BgpWithdrawMup(ctx, req.(*BgpWithdrawMupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BgpRouteService_ServiceDesc is the grpc.ServiceDesc for BgpRouteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BgpRouteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vinbero.v1.BgpRouteService",
	HandlerType: (*BgpRouteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BgpAdvertiseVpn",
			Handler:    _BgpRouteService_BgpAdvertiseVpn_Handler,
		},
		{
			MethodName: "BgpAdvertiseUnicast",
			Handler:    _BgpRouteService_BgpAdvertiseUnicast_Handler,
		},
		{
			MethodName: "BgpWithdraw",
			Handler:    _BgpRouteService_BgpWithdraw_Handler,
		},
		{
			MethodName: "BgpAdvertiseSrPolicy",
			Handler:    _BgpRouteService_BgpAdvertiseSrPolicy_Handler,
		},
		{
			MethodName: "BgpWithdrawSrPolicy",
			Handler:    _BgpRouteService_BgpWithdrawSrPolicy_Handler,
		},
		{
			MethodName: "BgpAdvertiseEvpnMac",
			Handler:    _BgpRouteService_BgpAdvertiseEvpnMac_Handler,
		},
		{
			MethodName: "BgpWithdrawEvpnMac",
			Handler:    _BgpRouteService_BgpWithdrawEvpnMac_Handler,
		},
		{
			MethodName: "BgpAdvertiseEvpnImet",
			Handler:    _BgpRouteService_BgpAdvertiseEvpnImet_Handler,
		},
		{
			MethodName: "BgpWithdrawEvpnImet",
			Handler:    _BgpRouteService_BgpWithdrawEvpnImet_Handler,
		},
		{
			MethodName: "BgpAdvertiseEvpnEs",
			Handler:    _BgpRouteService_BgpAdvertiseEvpnEs_Handler,
		},
		{
			MethodName: "BgpWithdrawEvpnEs",
			Handler:    _BgpRouteService_BgpWithdrawEvpnEs_Handler,
		},
		{
			MethodName: "BgpAdvertiseMup",
			Handler:    _BgpRouteService_BgpAdvertiseMup_Handler,
		},
		{
			MethodName: "BgpWithdrawMup",
			Handler:    _BgpRouteService_BgpWithdrawMup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vinbero/v1/bgp_route.proto",
}
