// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: vinbero/v1/mup.proto

package vinberov1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create and Update both upsert the local MUP route keyed by its route type and
// the type's identifying fields (ISD: rd+prefix; DSD: rd+address; T1ST:
// rd+prefix+teid; T2ST: rd+endpoint+teid+teid_len). An empty next_hop defaults
// to bgp.global.next_hop.
type MupCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routes []*BgpMupRoute `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
}

func (x *MupCreateRequest) Reset() {
	*x = MupCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_mup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MupCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MupCreateRequest) ProtoMessage() {}

func (x *MupCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_mup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MupCreateRequest.ProtoReflect.Descriptor instead.
func (*MupCreateRequest) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_mup_proto_rawDescGZIP(), []int{0}
}

func (x *MupCreateRequest) GetRoutes() []*BgpMupRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

type MupCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []*OperationError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *MupCreateResponse) Reset() {
	*x = MupCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_mup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MupCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MupCreateResponse) ProtoMessage() {}

func (x *MupCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_mup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MupCreateResponse.ProtoReflect.Descriptor instead.
func (*MupCreateResponse) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_mup_proto_rawDescGZIP(), []int{1}
}

func (x *MupCreateResponse) GetErrors() []*OperationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type MupUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routes []*BgpMupRoute `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
}

func (x *MupUpdateRequest) Reset() {
	*x = MupUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_mup_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MupUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MupUpdateRequest) ProtoMessage() {}

func (x *MupUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_mup_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MupUpdateRequest.ProtoReflect.Descriptor instead.
func (*MupUpdateRequest) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_mup_proto_rawDescGZIP(), []int{2}
}

func (x *MupUpdateRequest) GetRoutes() []*BgpMupRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

type MupUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []*OperationError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *MupUpdateResponse) Reset() {
	*x = MupUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_mup_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MupUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MupUpdateResponse) ProtoMessage() {}

func (x *MupUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_mup_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MupUpdateResponse.ProtoReflect.Descriptor instead.
func (*MupUpdateResponse) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_mup_proto_rawDescGZIP(), []int{3}
}

func (x *MupUpdateResponse) GetErrors() []*OperationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Delete reuses BgpMupRoute (like BgpWithdrawMup): only the route type and its
// identifying fields are read; the rest are ignored.
type MupDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routes []*BgpMupRoute `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
}

func (x *MupDeleteRequest) Reset() {
	*x = MupDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_mup_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MupDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MupDeleteRequest) ProtoMessage() {}

func (x *MupDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_mup_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MupDeleteRequest.ProtoReflect.Descriptor instead.
func (*MupDeleteRequest) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_mup_proto_rawDescGZIP(), []int{4}
}

func (x *MupDeleteRequest) GetRoutes() []*BgpMupRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

type MupDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []*OperationError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *MupDeleteResponse) Reset() {
	*x = MupDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_mup_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MupDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MupDeleteResponse) ProtoMessage() {}

func (x *MupDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_mup_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MupDeleteResponse.ProtoReflect.Descriptor instead.
func (*MupDeleteResponse) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_mup_proto_rawDescGZIP(), []int{5}
}

func (x *MupDeleteResponse) GetErrors() []*OperationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type MupListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MupListRequest) Reset() {
	*x = MupListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_mup_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MupListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MupListRequest) ProtoMessage() {}

func (x *MupListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_mup_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MupListRequest.ProtoReflect.Descriptor instead.
func (*MupListRequest) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_mup_proto_rawDescGZIP(), []int{6}
}

// MupList returns the MUP routes this node currently originates (local table);
// BGP-learned MUP routes are not included.
type MupListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routes []*BgpMupRoute `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
}

func (x *MupListResponse) Reset() {
	*x = MupListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_mup_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MupListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MupListResponse) ProtoMessage() {}

func (x *MupListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_mup_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MupListResponse.ProtoReflect.Descriptor instead.
func (*MupListResponse) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_mup_proto_rawDescGZIP(), []int{7}
}

func (x *MupListResponse) GetRoutes() []*BgpMupRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_vinbero_v1_mup_proto protoreflect.FileDescriptor

var file_vinbero_v1_mup_proto_rawDesc = []byte{
	0x0a, 0x14, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x75, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e,
	0x76, 0x31, 0x1a, 0x16, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x65,
	0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x76, 0x69, 0x6e, 0x62,
	0x65, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x67, 0x70, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x10, 0x4d, 0x75, 0x70, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x69, 0x6e,
	0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x67, 0x70, 0x4d, 0x75, 0x70, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x11, 0x4d,
	0x75, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x22, 0x43, 0x0a, 0x10, 0x4d, 0x75, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65,
	0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x67, 0x70, 0x4d, 0x75, 0x70, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x11, 0x4d, 0x75, 0x70,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32,
	0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x22, 0x43, 0x0a, 0x10, 0x4d, 0x75, 0x70, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x67, 0x70, 0x4d, 0x75, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52,
	0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x11, 0x4d, 0x75, 0x70, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76,
	0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x22, 0x10, 0x0a, 0x0e, 0x4d, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x42, 0x0a, 0x0f, 0x4d, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x67, 0x70, 0x4d, 0x75, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x06,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x32, 0xae, 0x02, 0x0a, 0x0a, 0x4d, 0x75, 0x70, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x4d, 0x75, 0x70, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x1c, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x75, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x75,
	0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x48, 0x0a, 0x09, 0x4d, 0x75, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x76,
	0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x75, 0x70, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x76, 0x69, 0x6e,
	0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x75, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x4d, 0x75, 0x70,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x75, 0x70, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x75, 0x70, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x4d, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a,
	0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x75, 0x70, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x76, 0x69, 0x6e,
	0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x99, 0x01, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e,
	0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x42, 0x08, 0x4d, 0x75, 0x70, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x6b, 0x65, 0x68, 0x61, 0x79, 0x61, 0x2f, 0x76, 0x69, 0x6e, 0x62,
	0x65, 0x72, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x56,
	0x58, 0x58, 0xaa, 0x02, 0x0a, 0x56, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x56, 0x31, 0xca,
	0x02, 0x0a, 0x56, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x16, 0x56,
	0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0b, 0x56, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x3a,
	0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vinbero_v1_mup_proto_rawDescOnce sync.Once
	file_vinbero_v1_mup_proto_rawDescData = file_vinbero_v1_mup_proto_rawDesc
)

func file_vinbero_v1_mup_proto_rawDescGZIP() []byte {
	file_vinbero_v1_mup_proto_rawDescOnce.Do(func() {
		file_vinbero_v1_mup_proto_rawDescData = protoimpl.X.CompressGZIP(file_vinbero_v1_mup_proto_rawDescData)
	})
	return file_vinbero_v1_mup_proto_rawDescData
}

var file_vinbero_v1_mup_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_vinbero_v1_mup_proto_goTypes = []interface{}{
	(*MupCreateRequest)(nil),  // 0: vinbero.v1.MupCreateRequest
	(*MupCreateResponse)(nil), // 1: vinbero.v1.MupCreateResponse
	(*MupUpdateRequest)(nil),  // 2: vinbero.v1.MupUpdateRequest
	(*MupUpdateResponse)(nil), // 3: vinbero.v1.MupUpdateResponse
	(*MupDeleteRequest)(nil),  // 4: vinbero.v1.MupDeleteRequest
	(*MupDeleteResponse)(nil), // 5: vinbero.v1.MupDeleteResponse
	(*MupListRequest)(nil),    // 6: vinbero.v1.MupListRequest
	(*MupListResponse)(nil),   // 7: vinbero.v1.MupListResponse
	(*BgpMupRoute)(nil),       // 8: vinbero.v1.BgpMupRoute
	(*OperationError)(nil),    // 9: vinbero.v1.OperationError
}
var file_vinbero_v1_mup_proto_depIdxs = []int32{
	8,  // 0: vinbero.v1.MupCreateRequest.routes:type_name -> vinbero.v1.BgpMupRoute
	9,  // 1: vinbero.v1.MupCreateResponse.errors:type_name -> vinbero.v1.OperationError
	8,  // 2: vinbero.v1.MupUpdateRequest.routes:type_name -> vinbero.v1.BgpMupRoute
	9,  // 3: vinbero.v1.MupUpdateResponse.errors:type_name -> vinbero.v1.OperationError
	8,  // 4: vinbero.v1.MupDeleteRequest.routes:type_name -> vinbero.v1.BgpMupRoute
	9,  // 5: vinbero.v1.MupDeleteResponse.errors:type_name -> vinbero.v1.OperationError
	8,  // 6: vinbero.v1.MupListResponse.routes:type_name -> vinbero.v1.BgpMupRoute
	0,  // 7: vinbero.v1.MupService.MupCreate:input_type -> vinbero.v1.MupCreateRequest
	2,  // 8: vinbero.v1.MupService.MupUpdate:input_type -> vinbero.v1.MupUpdateRequest
	4,  // 9: vinbero.v1.MupService.MupDelete:input_type -> vinbero.v1.MupDeleteRequest
	6,  // 10: vinbero.v1.MupService.MupList:input_type -> vinbero.v1.MupListRequest
	1,  // 11: vinbero.v1.MupService.MupCreate:output_type -> vinbero.v1.MupCreateResponse
	3,  // 12: vinbero.v1.MupService.MupUpdate:output_type -> vinbero.v1.MupUpdateResponse
	5,  // 13: vinbero.v1.MupService.MupDelete:output_type -> vinbero.v1.MupDeleteResponse
	7,  // 14: vinbero.v1.MupService.MupList:output_type -> vinbero.v1.MupListResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_vinbero_v1_mup_proto_init() }
func file_vinbero_v1_mup_proto_init() {
	if File_vinbero_v1_mup_proto != nil {
		return
	}
	file_vinbero_v1_enums_proto_init()
	file_vinbero_v1_bgp_route_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_vinbero_v1_mup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MupCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_mup_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MupCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_mup_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MupUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_mup_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MupUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_mup_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MupDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_mup_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MupDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_mup_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MupListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_mup_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MupListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vinbero_v1_mup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vinbero_v1_mup_proto_goTypes,
		DependencyIndexes: file_vinbero_v1_mup_proto_depIdxs,
		MessageInfos:      file_vinbero_v1_mup_proto_msgTypes,
	}.Build()
	File_vinbero_v1_mup_proto = out.File
	file_vinbero_v1_mup_proto_rawDesc = nil
	file_vinbero_v1_mup_proto_goTypes = nil
	file_vinbero_v1_mup_proto_depIdxs = nil
}
