// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: vinbero/v1/plugin.proto

package vinberov1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapType string `protobuf:"bytes,1,opt,name=map_type,json=mapType,proto3" json:"map_type,omitempty"` // PROG_ARRAY target: "endpoint", "headend_v4", "headend_v6"
	Index   uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`                   // Plugin slot index (endpoint: 32-63, headend: 16-31)
	BpfElf  []byte `protobuf:"bytes,3,opt,name=bpf_elf,json=bpfElf,proto3" json:"bpf_elf,omitempty"`    // Compiled BPF ELF object file bytes
	Section string `protobuf:"bytes,4,opt,name=section,proto3" json:"section,omitempty"`                // BPF program section name within the ELF (e.g., "xdp")
}

func (x *PluginRegisterRequest) Reset() {
	*x = PluginRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRegisterRequest) ProtoMessage() {}

func (x *PluginRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRegisterRequest.ProtoReflect.Descriptor instead.
func (*PluginRegisterRequest) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginRegisterRequest) GetMapType() string {
	if x != nil {
		return x.MapType
	}
	return ""
}

func (x *PluginRegisterRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PluginRegisterRequest) GetBpfElf() []byte {
	if x != nil {
		return x.BpfElf
	}
	return nil
}

func (x *PluginRegisterRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

type PluginRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PluginRegisterResponse) Reset() {
	*x = PluginRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_plugin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRegisterResponse) ProtoMessage() {}

func (x *PluginRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_plugin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRegisterResponse.ProtoReflect.Descriptor instead.
func (*PluginRegisterResponse) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_plugin_proto_rawDescGZIP(), []int{1}
}

type PluginUnregisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapType string `protobuf:"bytes,1,opt,name=map_type,json=mapType,proto3" json:"map_type,omitempty"` // PROG_ARRAY target: "endpoint", "headend_v4", "headend_v6"
	Index   uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`                   // Plugin slot index to clear
}

func (x *PluginUnregisterRequest) Reset() {
	*x = PluginUnregisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_plugin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginUnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginUnregisterRequest) ProtoMessage() {}

func (x *PluginUnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_plugin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginUnregisterRequest.ProtoReflect.Descriptor instead.
func (*PluginUnregisterRequest) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginUnregisterRequest) GetMapType() string {
	if x != nil {
		return x.MapType
	}
	return ""
}

func (x *PluginUnregisterRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type PluginUnregisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PluginUnregisterResponse) Reset() {
	*x = PluginUnregisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_plugin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginUnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginUnregisterResponse) ProtoMessage() {}

func (x *PluginUnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_plugin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginUnregisterResponse.ProtoReflect.Descriptor instead.
func (*PluginUnregisterResponse) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_plugin_proto_rawDescGZIP(), []int{3}
}

var File_vinbero_v1_plugin_proto protoreflect.FileDescriptor

var file_vinbero_v1_plugin_proto_rawDesc = []byte{
	0x0a, 0x17, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x76, 0x69, 0x6e, 0x62, 0x65,
	0x72, 0x6f, 0x2e, 0x76, 0x31, 0x22, 0x7b, 0x0a, 0x15, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x6d, 0x61, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x61, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x17, 0x0a, 0x07, 0x62, 0x70, 0x66, 0x5f, 0x65, 0x6c, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x62, 0x70, 0x66, 0x45, 0x6c, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x18, 0x0a, 0x16, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4a, 0x0a, 0x17,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x70, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x1a, 0x0a, 0x18, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc7, 0x01, 0x0a, 0x0d, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x0e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65,
	0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x76, 0x69,
	0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5d, 0x0a, 0x10, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65,
	0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x55, 0x6e, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x9c,
	0x01, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76,
	0x31, 0x42, 0x0b, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x6b,
	0x65, 0x68, 0x61, 0x79, 0x61, 0x2f, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x69, 0x6e,
	0x62, 0x65, 0x72, 0x6f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x56, 0x58, 0x58, 0xaa, 0x02, 0x0a, 0x56,
	0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0a, 0x56, 0x69, 0x6e, 0x62,
	0x65, 0x72, 0x6f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x16, 0x56, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f,
	0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x0b, 0x56, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vinbero_v1_plugin_proto_rawDescOnce sync.Once
	file_vinbero_v1_plugin_proto_rawDescData = file_vinbero_v1_plugin_proto_rawDesc
)

func file_vinbero_v1_plugin_proto_rawDescGZIP() []byte {
	file_vinbero_v1_plugin_proto_rawDescOnce.Do(func() {
		file_vinbero_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_vinbero_v1_plugin_proto_rawDescData)
	})
	return file_vinbero_v1_plugin_proto_rawDescData
}

var file_vinbero_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vinbero_v1_plugin_proto_goTypes = []interface{}{
	(*PluginRegisterRequest)(nil),    // 0: vinbero.v1.PluginRegisterRequest
	(*PluginRegisterResponse)(nil),   // 1: vinbero.v1.PluginRegisterResponse
	(*PluginUnregisterRequest)(nil),  // 2: vinbero.v1.PluginUnregisterRequest
	(*PluginUnregisterResponse)(nil), // 3: vinbero.v1.PluginUnregisterResponse
}
var file_vinbero_v1_plugin_proto_depIdxs = []int32{
	0, // 0: vinbero.v1.PluginService.PluginRegister:input_type -> vinbero.v1.PluginRegisterRequest
	2, // 1: vinbero.v1.PluginService.PluginUnregister:input_type -> vinbero.v1.PluginUnregisterRequest
	1, // 2: vinbero.v1.PluginService.PluginRegister:output_type -> vinbero.v1.PluginRegisterResponse
	3, // 3: vinbero.v1.PluginService.PluginUnregister:output_type -> vinbero.v1.PluginUnregisterResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vinbero_v1_plugin_proto_init() }
func file_vinbero_v1_plugin_proto_init() {
	if File_vinbero_v1_plugin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vinbero_v1_plugin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_plugin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_plugin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginUnregisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_plugin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginUnregisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vinbero_v1_plugin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vinbero_v1_plugin_proto_goTypes,
		DependencyIndexes: file_vinbero_v1_plugin_proto_depIdxs,
		MessageInfos:      file_vinbero_v1_plugin_proto_msgTypes,
	}.Build()
	File_vinbero_v1_plugin_proto = out.File
	file_vinbero_v1_plugin_proto_rawDesc = nil
	file_vinbero_v1_plugin_proto_goTypes = nil
	file_vinbero_v1_plugin_proto_depIdxs = nil
}
