// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: vinbero/v1/plugin.proto

package vinberov1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PluginService_PluginRegister_FullMethodName         = "/vinbero.v1.PluginService/PluginRegister"
	PluginService_PluginUnregister_FullMethodName       = "/vinbero.v1.PluginService/PluginUnregister"
	PluginService_PluginList_FullMethodName             = "/vinbero.v1.PluginService/PluginList"
	PluginService_PluginAuxAlloc_FullMethodName         = "/vinbero.v1.PluginService/PluginAuxAlloc"
	PluginService_PluginAuxUpdate_FullMethodName        = "/vinbero.v1.PluginService/PluginAuxUpdate"
	PluginService_PluginAuxGet_FullMethodName           = "/vinbero.v1.PluginService/PluginAuxGet"
	PluginService_PluginAuxFree_FullMethodName          = "/vinbero.v1.PluginService/PluginAuxFree"
	PluginService_PluginAuxPurge_FullMethodName         = "/vinbero.v1.PluginService/PluginAuxPurge"
	PluginService_PluginAuxList_FullMethodName          = "/vinbero.v1.PluginService/PluginAuxList"
	PluginService_CplanePluginRegister_FullMethodName   = "/vinbero.v1.PluginService/CplanePluginRegister"
	PluginService_CplanePluginUnregister_FullMethodName = "/vinbero.v1.PluginService/CplanePluginUnregister"
	PluginService_CplanePluginList_FullMethodName       = "/vinbero.v1.PluginService/CplanePluginList"
	PluginService_CplanePluginStats_FullMethodName      = "/vinbero.v1.PluginService/CplanePluginStats"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginServiceClient interface {
	PluginRegister(ctx context.Context, in *PluginRegisterRequest, opts ...grpc.CallOption) (*PluginRegisterResponse, error)
	PluginUnregister(ctx context.Context, in *PluginUnregisterRequest, opts ...grpc.CallOption) (*PluginUnregisterResponse, error)
	PluginList(ctx context.Context, in *PluginListRequest, opts ...grpc.CallOption) (*PluginListResponse, error)
	// Allocate a fresh aux index, write the given payload, and return the
	// index. Owner tag is derived from (map_type, slot) so later Update /
	// Get / Free calls must come through the same (map_type, slot) pair.
	PluginAuxAlloc(ctx context.Context, in *PluginAuxAllocRequest, opts ...grpc.CallOption) (*PluginAuxAllocResponse, error)
	// Overwrite the payload at an index already owned by (map_type, slot).
	PluginAuxUpdate(ctx context.Context, in *PluginAuxUpdateRequest, opts ...grpc.CallOption) (*PluginAuxUpdateResponse, error)
	// Read the on-wire bytes stored at an index. Caller decodes via its own
	// BTF / Go struct layout; the server returns raw bytes + the owner tag.
	PluginAuxGet(ctx context.Context, in *PluginAuxGetRequest, opts ...grpc.CallOption) (*PluginAuxGetResponse, error)
	// Zero the entry and release the index back to the allocator.
	PluginAuxFree(ctx context.Context, in *PluginAuxFreeRequest, opts ...grpc.CallOption) (*PluginAuxFreeResponse, error)
	// Free every aux index owned by (map_type, slot). Use after
	// PluginUnregister to release indices that were not freed by
	// PluginAuxFree before the slot was retired.
	PluginAuxPurge(ctx context.Context, in *PluginAuxPurgeRequest, opts ...grpc.CallOption) (*PluginAuxPurgeResponse, error)
	// Enumerate aux indices currently owned by the given filter. Empty
	// filter returns all live indices.
	PluginAuxList(ctx context.Context, in *PluginAuxListRequest, opts ...grpc.CallOption) (*PluginAuxListResponse, error)
	// Control-plane plugins are registered separately from data-plane ones.
	// The two halves of a plugin are different artifacts with different
	// lifecycles -- an eBPF object occupies a PROG_ARRAY slot, a WebAssembly
	// module runs in the daemon -- so they get their own calls rather than
	// one overloaded request whose fields are half-ignored either way.
	//
	// Registering a name that is already running replaces it in place: the
	// state the old instance wrote is kept and the new module reconciles
	// over it, so an upgrade does not empty the data plane in between.
	CplanePluginRegister(ctx context.Context, in *CplanePluginRegisterRequest, opts ...grpc.CallOption) (*CplanePluginRegisterResponse, error)
	// Stop a control-plane plugin and remove the state it owns. This is the
	// deliberate removal; a plugin that merely crashes is restarted and
	// keeps its entries.
	CplanePluginUnregister(ctx context.Context, in *CplanePluginUnregisterRequest, opts ...grpc.CallOption) (*CplanePluginUnregisterResponse, error)
	// Enumerate running control-plane plugins.
	CplanePluginList(ctx context.Context, in *CplanePluginListRequest, opts ...grpc.CallOption) (*CplanePluginListResponse, error)
	// Report what each running plugin is doing and holding.
	//
	// A sandboxed plugin is otherwise unobservable: one that has fallen
	// behind, one restarting in a loop and one with nothing to do all look
	// the same from outside. These counters are what tell them apart.
	CplanePluginStats(ctx context.Context, in *CplanePluginStatsRequest, opts ...grpc.CallOption) (*CplanePluginStatsResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) PluginRegister(ctx context.Context, in *PluginRegisterRequest, opts ...grpc.CallOption) (*PluginRegisterResponse, error) {
	out := new(PluginRegisterResponse)
	err := c.cc.Invoke(ctx, PluginService_PluginRegister_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) PluginUnregister(ctx context.Context, in *PluginUnregisterRequest, opts ...grpc.CallOption) (*PluginUnregisterResponse, error) {
	out := new(PluginUnregisterResponse)
	err := c.cc.Invoke(ctx, PluginService_PluginUnregister_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) PluginList(ctx context.Context, in *PluginListRequest, opts ...grpc.CallOption) (*PluginListResponse, error) {
	out := new(PluginListResponse)
	err := c.cc.Invoke(ctx, PluginService_PluginList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) PluginAuxAlloc(ctx context.Context, in *PluginAuxAllocRequest, opts ...grpc.CallOption) (*PluginAuxAllocResponse, error) {
	out := new(PluginAuxAllocResponse)
	err := c.cc.Invoke(ctx, PluginService_PluginAuxAlloc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) PluginAuxUpdate(ctx context.Context, in *PluginAuxUpdateRequest, opts ...grpc.CallOption) (*PluginAuxUpdateResponse, error) {
	out := new(PluginAuxUpdateResponse)
	err := c.cc.Invoke(ctx, PluginService_PluginAuxUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) PluginAuxGet(ctx context.Context, in *PluginAuxGetRequest, opts ...grpc.CallOption) (*PluginAuxGetResponse, error) {
	out := new(PluginAuxGetResponse)
	err := c.cc.Invoke(ctx, PluginService_PluginAuxGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) PluginAuxFree(ctx context.Context, in *PluginAuxFreeRequest, opts ...grpc.CallOption) (*PluginAuxFreeResponse, error) {
	out := new(PluginAuxFreeResponse)
	err := c.cc.Invoke(ctx, PluginService_PluginAuxFree_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) PluginAuxPurge(ctx context.Context, in *PluginAuxPurgeRequest, opts ...grpc.CallOption) (*PluginAuxPurgeResponse, error) {
	out := new(PluginAuxPurgeResponse)
	err := c.cc.Invoke(ctx, PluginService_PluginAuxPurge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) PluginAuxList(ctx context.Context, in *PluginAuxListRequest, opts ...grpc.CallOption) (*PluginAuxListResponse, error) {
	out := new(PluginAuxListResponse)
	err := c.cc.Invoke(ctx, PluginService_PluginAuxList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) CplanePluginRegister(ctx context.Context, in *CplanePluginRegisterRequest, opts ...grpc.CallOption) (*CplanePluginRegisterResponse, error) {
	out := new(CplanePluginRegisterResponse)
	err := c.cc.Invoke(ctx, PluginService_CplanePluginRegister_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) CplanePluginUnregister(ctx context.Context, in *CplanePluginUnregisterRequest, opts ...grpc.CallOption) (*CplanePluginUnregisterResponse, error) {
	out := new(CplanePluginUnregisterResponse)
	err := c.cc.Invoke(ctx, PluginService_CplanePluginUnregister_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) CplanePluginList(ctx context.Context, in *CplanePluginListRequest, opts ...grpc.CallOption) (*CplanePluginListResponse, error) {
	out := new(CplanePluginListResponse)
	err := c.cc.Invoke(ctx, PluginService_CplanePluginList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) CplanePluginStats(ctx context.Context, in *CplanePluginStatsRequest, opts ...grpc.CallOption) (*CplanePluginStatsResponse, error) {
	out := new(CplanePluginStatsResponse)
	err := c.cc.Invoke(ctx, PluginService_CplanePluginStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations should embed UnimplementedPluginServiceServer
// for forward compatibility
type PluginServiceServer interface {
	PluginRegister(context.Context, *PluginRegisterRequest) (*PluginRegisterResponse, error)
	PluginUnregister(context.Context, *PluginUnregisterRequest) (*PluginUnregisterResponse, error)
	PluginList(context.Context, *PluginListRequest) (*PluginListResponse, error)
	// Allocate a fresh aux index, write the given payload, and return the
	// index. Owner tag is derived from (map_type, slot) so later Update /
	// Get / Free calls must come through the same (map_type, slot) pair.
	PluginAuxAlloc(context.Context, *PluginAuxAllocRequest) (*PluginAuxAllocResponse, error)
	// Overwrite the payload at an index already owned by (map_type, slot).
	PluginAuxUpdate(context.Context, *PluginAuxUpdateRequest) (*PluginAuxUpdateResponse, error)
	// Read the on-wire bytes stored at an index. Caller decodes via its own
	// BTF / Go struct layout; the server returns raw bytes + the owner tag.
	PluginAuxGet(context.Context, *PluginAuxGetRequest) (*PluginAuxGetResponse, error)
	// Zero the entry and release the index back to the allocator.
	PluginAuxFree(context.Context, *PluginAuxFreeRequest) (*PluginAuxFreeResponse, error)
	// Free every aux index owned by (map_type, slot). Use after
	// PluginUnregister to release indices that were not freed by
	// PluginAuxFree before the slot was retired.
	PluginAuxPurge(context.Context, *PluginAuxPurgeRequest) (*PluginAuxPurgeResponse, error)
	// Enumerate aux indices currently owned by the given filter. Empty
	// filter returns all live indices.
	PluginAuxList(context.Context, *PluginAuxListRequest) (*PluginAuxListResponse, error)
	// Control-plane plugins are registered separately from data-plane ones.
	// The two halves of a plugin are different artifacts with different
	// lifecycles -- an eBPF object occupies a PROG_ARRAY slot, a WebAssembly
	// module runs in the daemon -- so they get their own calls rather than
	// one overloaded request whose fields are half-ignored either way.
	//
	// Registering a name that is already running replaces it in place: the
	// state the old instance wrote is kept and the new module reconciles
	// over it, so an upgrade does not empty the data plane in between.
	CplanePluginRegister(context.Context, *CplanePluginRegisterRequest) (*CplanePluginRegisterResponse, error)
	// Stop a control-plane plugin and remove the state it owns. This is the
	// deliberate removal; a plugin that merely crashes is restarted and
	// keeps its entries.
	CplanePluginUnregister(context.Context, *CplanePluginUnregisterRequest) (*CplanePluginUnregisterResponse, error)
	// Enumerate running control-plane plugins.
	CplanePluginList(context.Context, *CplanePluginListRequest) (*CplanePluginListResponse, error)
	// Report what each running plugin is doing and holding.
	//
	// A sandboxed plugin is otherwise unobservable: one that has fallen
	// behind, one restarting in a loop and one with nothing to do all look
	// the same from outside. These counters are what tell them apart.
	CplanePluginStats(context.Context, *CplanePluginStatsRequest) (*CplanePluginStatsResponse, error)
}

// UnimplementedPluginServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPluginServiceServer struct {
}

func (UnimplementedPluginServiceServer) PluginRegister(context.Context, *PluginRegisterRequest) (*PluginRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginRegister not implemented")
}
func (UnimplementedPluginServiceServer) PluginUnregister(context.Context, *PluginUnregisterRequest) (*PluginUnregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginUnregister not implemented")
}
func (UnimplementedPluginServiceServer) PluginList(context.Context, *PluginListRequest) (*PluginListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginList not implemented")
}
func (UnimplementedPluginServiceServer) PluginAuxAlloc(context.Context, *PluginAuxAllocRequest) (*PluginAuxAllocResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginAuxAlloc not implemented")
}
func (UnimplementedPluginServiceServer) PluginAuxUpdate(context.Context, *PluginAuxUpdateRequest) (*PluginAuxUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginAuxUpdate not implemented")
}
func (UnimplementedPluginServiceServer) PluginAuxGet(context.Context, *PluginAuxGetRequest) (*PluginAuxGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginAuxGet not implemented")
}
func (UnimplementedPluginServiceServer) PluginAuxFree(context.Context, *PluginAuxFreeRequest) (*PluginAuxFreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginAuxFree not implemented")
}
func (UnimplementedPluginServiceServer) PluginAuxPurge(context.Context, *PluginAuxPurgeRequest) (*PluginAuxPurgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginAuxPurge not implemented")
}
func (UnimplementedPluginServiceServer) PluginAuxList(context.Context, *PluginAuxListRequest) (*PluginAuxListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginAuxList not implemented")
}
func (UnimplementedPluginServiceServer) CplanePluginRegister(context.Context, *CplanePluginRegisterRequest) (*CplanePluginRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CplanePluginRegister not implemented")
}
func (UnimplementedPluginServiceServer) CplanePluginUnregister(context.Context, *CplanePluginUnregisterRequest) (*CplanePluginUnregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CplanePluginUnregister not implemented")
}
func (UnimplementedPluginServiceServer) CplanePluginList(context.Context, *CplanePluginListRequest) (*CplanePluginListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CplanePluginList not implemented")
}
func (UnimplementedPluginServiceServer) CplanePluginStats(context.Context, *CplanePluginStatsRequest) (*CplanePluginStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CplanePluginStats not implemented")
}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_PluginRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).PluginRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_PluginRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).PluginRegister(ctx, req.(*PluginRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_PluginUnregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginUnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).PluginUnregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_PluginUnregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).PluginUnregister(ctx, req.(*PluginUnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_PluginList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).PluginList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_PluginList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).PluginList(ctx, req.(*PluginListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_PluginAuxAlloc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginAuxAllocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).PluginAuxAlloc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_PluginAuxAlloc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).PluginAuxAlloc(ctx, req.(*PluginAuxAllocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_PluginAuxUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginAuxUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).PluginAuxUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_PluginAuxUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).PluginAuxUpdate(ctx, req.(*PluginAuxUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_PluginAuxGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginAuxGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).PluginAuxGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_PluginAuxGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).PluginAuxGet(ctx, req.(*PluginAuxGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_PluginAuxFree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginAuxFreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).PluginAuxFree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_PluginAuxFree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).PluginAuxFree(ctx, req.(*PluginAuxFreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_PluginAuxPurge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginAuxPurgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).PluginAuxPurge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_PluginAuxPurge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).PluginAuxPurge(ctx, req.(*PluginAuxPurgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_PluginAuxList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginAuxListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).PluginAuxList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_PluginAuxList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).PluginAuxList(ctx, req.(*PluginAuxListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_CplanePluginRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CplanePluginRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).CplanePluginRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_CplanePluginRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).CplanePluginRegister(ctx, req.(*CplanePluginRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_CplanePluginUnregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CplanePluginUnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).CplanePluginUnregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_CplanePluginUnregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).CplanePluginUnregister(ctx, req.(*CplanePluginUnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_CplanePluginList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CplanePluginListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).CplanePluginList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_CplanePluginList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).CplanePluginList(ctx, req.(*CplanePluginListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_CplanePluginStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CplanePluginStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).CplanePluginStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_CplanePluginStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).CplanePluginStats(ctx, req.(*CplanePluginStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vinbero.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PluginRegister",
			Handler:    _PluginService_PluginRegister_Handler,
		},
		{
			MethodName: "PluginUnregister",
			Handler:    _PluginService_PluginUnregister_Handler,
		},
		{
			MethodName: "PluginList",
			Handler:    _PluginService_PluginList_Handler,
		},
		{
			MethodName: "PluginAuxAlloc",
			Handler:    _PluginService_PluginAuxAlloc_Handler,
		},
		{
			MethodName: "PluginAuxUpdate",
			Handler:    _PluginService_PluginAuxUpdate_Handler,
		},
		{
			MethodName: "PluginAuxGet",
			Handler:    _PluginService_PluginAuxGet_Handler,
		},
		{
			MethodName: "PluginAuxFree",
			Handler:    _PluginService_PluginAuxFree_Handler,
		},
		{
			MethodName: "PluginAuxPurge",
			Handler:    _PluginService_PluginAuxPurge_Handler,
		},
		{
			MethodName: "PluginAuxList",
			Handler:    _PluginService_PluginAuxList_Handler,
		},
		{
			MethodName: "CplanePluginRegister",
			Handler:    _PluginService_CplanePluginRegister_Handler,
		},
		{
			MethodName: "CplanePluginUnregister",
			Handler:    _PluginService_CplanePluginUnregister_Handler,
		},
		{
			MethodName: "CplanePluginList",
			Handler:    _PluginService_CplanePluginList_Handler,
		},
		{
			MethodName: "CplanePluginStats",
			Handler:    _PluginService_CplanePluginStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vinbero/v1/plugin.proto",
}
