// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: vinbero/v1/prober.proto

package vinberov1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProberService_ProberStatus_FullMethodName = "/vinbero.v1.ProberService/ProberStatus"
)

// ProberServiceClient is the client API for ProberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProberServiceClient interface {
	ProberStatus(ctx context.Context, in *ProberStatusRequest, opts ...grpc.CallOption) (*ProberStatusResponse, error)
}

type proberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProberServiceClient(cc grpc.ClientConnInterface) ProberServiceClient {
	return &proberServiceClient{cc}
}

func (c *proberServiceClient) ProberStatus(ctx context.Context, in *ProberStatusRequest, opts ...grpc.CallOption) (*ProberStatusResponse, error) {
	out := new(ProberStatusResponse)
	err := c.cc.Invoke(ctx, ProberService_ProberStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProberServiceServer is the server API for ProberService service.
// All implementations should embed UnimplementedProberServiceServer
// for forward compatibility
type ProberServiceServer interface {
	ProberStatus(context.Context, *ProberStatusRequest) (*ProberStatusResponse, error)
}

// UnimplementedProberServiceServer should be embedded to have forward compatible implementations.
type UnimplementedProberServiceServer struct {
}

func (UnimplementedProberServiceServer) ProberStatus(context.Context, *ProberStatusRequest) (*ProberStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProberStatus not implemented")
}

// UnsafeProberServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProberServiceServer will
// result in compilation errors.
type UnsafeProberServiceServer interface {
	mustEmbedUnimplementedProberServiceServer()
}

func RegisterProberServiceServer(s grpc.ServiceRegistrar, srv ProberServiceServer) {
	s.RegisterService(&ProberService_ServiceDesc, srv)
}

func _ProberService_ProberStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProberStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProberServiceServer).ProberStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProberService_ProberStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProberServiceServer).ProberStatus(ctx, req.(*ProberStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProberService_ServiceDesc is the grpc.ServiceDesc for ProberService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProberService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vinbero.v1.ProberService",
	HandlerType: (*ProberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProberStatus",
			Handler:    _ProberService_ProberStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vinbero/v1/prober.proto",
}
