// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: vinbero/v1/sr_policy.proto

package vinberov1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SrPolicyOrigin records what signaled a candidate path (RFC 9256 §2.4
// Protocol-Origin). On equal preference, local outranks bgp.
type SrPolicyOrigin int32

const (
	SrPolicyOrigin_SR_POLICY_ORIGIN_UNSPECIFIED SrPolicyOrigin = 0
	SrPolicyOrigin_SR_POLICY_ORIGIN_LOCAL       SrPolicyOrigin = 1
	SrPolicyOrigin_SR_POLICY_ORIGIN_BGP         SrPolicyOrigin = 2
)

// Enum value maps for SrPolicyOrigin.
var (
	SrPolicyOrigin_name = map[int32]string{
		0: "SR_POLICY_ORIGIN_UNSPECIFIED",
		1: "SR_POLICY_ORIGIN_LOCAL",
		2: "SR_POLICY_ORIGIN_BGP",
	}
	SrPolicyOrigin_value = map[string]int32{
		"SR_POLICY_ORIGIN_UNSPECIFIED": 0,
		"SR_POLICY_ORIGIN_LOCAL":       1,
		"SR_POLICY_ORIGIN_BGP":         2,
	}
)

func (x SrPolicyOrigin) Enum() *SrPolicyOrigin {
	p := new(SrPolicyOrigin)
	*p = x
	return p
}

func (x SrPolicyOrigin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SrPolicyOrigin) Descriptor() protoreflect.EnumDescriptor {
	return file_vinbero_v1_sr_policy_proto_enumTypes[0].Descriptor()
}

func (SrPolicyOrigin) Type() protoreflect.EnumType {
	return &file_vinbero_v1_sr_policy_proto_enumTypes[0]
}

func (x SrPolicyOrigin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SrPolicyOrigin.Descriptor instead.
func (SrPolicyOrigin) EnumDescriptor() ([]byte, []int) {
	return file_vinbero_v1_sr_policy_proto_rawDescGZIP(), []int{0}
}

// SrPolicyDef is an operator-defined SR Policy candidate path, keyed by
// {color, endpoint}. Create and Update both upsert it.
type SrPolicyDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color      uint32   `protobuf:"varint,1,opt,name=color,proto3" json:"color,omitempty"`           // Color matched by the Color Extended Community.
	Endpoint   string   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`      // SR Policy endpoint (IPv6), = the egress PE's BGP next hop.
	Segments   []string `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`      // Transport SRv6 SIDs (the route's service SID is appended in the data plane).
	Preference uint32   `protobuf:"varint,4,opt,name=preference,proto3" json:"preference,omitempty"` // Candidate path preference; 0 means the RFC default of 100.
	Advertise  bool     `protobuf:"varint,5,opt,name=advertise,proto3" json:"advertise,omitempty"`   // When true, also advertise this policy into BGP (SAFI 73, origin local) using bgp.global.next_hop; default false = local steering only.
}

func (x *SrPolicyDef) Reset() {
	*x = SrPolicyDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_sr_policy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrPolicyDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrPolicyDef) ProtoMessage() {}

func (x *SrPolicyDef) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_sr_policy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrPolicyDef.ProtoReflect.Descriptor instead.
func (*SrPolicyDef) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_sr_policy_proto_rawDescGZIP(), []int{0}
}

func (x *SrPolicyDef) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *SrPolicyDef) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *SrPolicyDef) GetSegments() []string {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *SrPolicyDef) GetPreference() uint32 {
	if x != nil {
		return x.Preference
	}
	return 0
}

func (x *SrPolicyDef) GetAdvertise() bool {
	if x != nil {
		return x.Advertise
	}
	return false
}

// SrPolicyKey identifies a policy for deletion / lookup.
type SrPolicyKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color    uint32 `protobuf:"varint,1,opt,name=color,proto3" json:"color,omitempty"`
	Endpoint string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
}

func (x *SrPolicyKey) Reset() {
	*x = SrPolicyKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_sr_policy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrPolicyKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrPolicyKey) ProtoMessage() {}

func (x *SrPolicyKey) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_sr_policy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrPolicyKey.ProtoReflect.Descriptor instead.
func (*SrPolicyKey) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_sr_policy_proto_rawDescGZIP(), []int{1}
}

func (x *SrPolicyKey) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *SrPolicyKey) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// SrPolicyCandidate is one candidate path of a policy as held in the table.
type SrPolicyCandidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin        SrPolicyOrigin `protobuf:"varint,1,opt,name=origin,proto3,enum=vinbero.v1.SrPolicyOrigin" json:"origin,omitempty"`
	Distinguisher uint32         `protobuf:"varint,2,opt,name=distinguisher,proto3" json:"distinguisher,omitempty"`
	Preference    uint32         `protobuf:"varint,3,opt,name=preference,proto3" json:"preference,omitempty"`
	Segments      []string       `protobuf:"bytes,4,rep,name=segments,proto3" json:"segments,omitempty"`
	Active        bool           `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"` // True for the currently selected best path.
}

func (x *SrPolicyCandidate) Reset() {
	*x = SrPolicyCandidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_sr_policy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrPolicyCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrPolicyCandidate) ProtoMessage() {}

func (x *SrPolicyCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_sr_policy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrPolicyCandidate.ProtoReflect.Descriptor instead.
func (*SrPolicyCandidate) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_sr_policy_proto_rawDescGZIP(), []int{2}
}

func (x *SrPolicyCandidate) GetOrigin() SrPolicyOrigin {
	if x != nil {
		return x.Origin
	}
	return SrPolicyOrigin_SR_POLICY_ORIGIN_UNSPECIFIED
}

func (x *SrPolicyCandidate) GetDistinguisher() uint32 {
	if x != nil {
		return x.Distinguisher
	}
	return 0
}

func (x *SrPolicyCandidate) GetPreference() uint32 {
	if x != nil {
		return x.Preference
	}
	return 0
}

func (x *SrPolicyCandidate) GetSegments() []string {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *SrPolicyCandidate) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// SrPolicyEntry is the full state of one {color, endpoint} policy.
type SrPolicyEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color      uint32               `protobuf:"varint,1,opt,name=color,proto3" json:"color,omitempty"`
	Endpoint   string               `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	PolicyId   uint32               `protobuf:"varint,3,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"` // Opaque data-plane handle (sr_policy_map key).
	Candidates []*SrPolicyCandidate `protobuf:"bytes,4,rep,name=candidates,proto3" json:"candidates,omitempty"`
}

func (x *SrPolicyEntry) Reset() {
	*x = SrPolicyEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_sr_policy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrPolicyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrPolicyEntry) ProtoMessage() {}

func (x *SrPolicyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_sr_policy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrPolicyEntry.ProtoReflect.Descriptor instead.
func (*SrPolicyEntry) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_sr_policy_proto_rawDescGZIP(), []int{3}
}

func (x *SrPolicyEntry) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *SrPolicyEntry) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *SrPolicyEntry) GetPolicyId() uint32 {
	if x != nil {
		return x.PolicyId
	}
	return 0
}

func (x *SrPolicyEntry) GetCandidates() []*SrPolicyCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type SrPolicyCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Policies []*SrPolicyDef `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
}

func (x *SrPolicyCreateRequest) Reset() {
	*x = SrPolicyCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_sr_policy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrPolicyCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrPolicyCreateRequest) ProtoMessage() {}

func (x *SrPolicyCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_sr_policy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrPolicyCreateRequest.ProtoReflect.Descriptor instead.
func (*SrPolicyCreateRequest) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_sr_policy_proto_rawDescGZIP(), []int{4}
}

func (x *SrPolicyCreateRequest) GetPolicies() []*SrPolicyDef {
	if x != nil {
		return x.Policies
	}
	return nil
}

type SrPolicyCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []*OperationError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *SrPolicyCreateResponse) Reset() {
	*x = SrPolicyCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_sr_policy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrPolicyCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrPolicyCreateResponse) ProtoMessage() {}

func (x *SrPolicyCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_sr_policy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrPolicyCreateResponse.ProtoReflect.Descriptor instead.
func (*SrPolicyCreateResponse) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_sr_policy_proto_rawDescGZIP(), []int{5}
}

func (x *SrPolicyCreateResponse) GetErrors() []*OperationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type SrPolicyUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Policies []*SrPolicyDef `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
}

func (x *SrPolicyUpdateRequest) Reset() {
	*x = SrPolicyUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_sr_policy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrPolicyUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrPolicyUpdateRequest) ProtoMessage() {}

func (x *SrPolicyUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_sr_policy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrPolicyUpdateRequest.ProtoReflect.Descriptor instead.
func (*SrPolicyUpdateRequest) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_sr_policy_proto_rawDescGZIP(), []int{6}
}

func (x *SrPolicyUpdateRequest) GetPolicies() []*SrPolicyDef {
	if x != nil {
		return x.Policies
	}
	return nil
}

type SrPolicyUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []*OperationError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *SrPolicyUpdateResponse) Reset() {
	*x = SrPolicyUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_sr_policy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrPolicyUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrPolicyUpdateResponse) ProtoMessage() {}

func (x *SrPolicyUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_sr_policy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrPolicyUpdateResponse.ProtoReflect.Descriptor instead.
func (*SrPolicyUpdateResponse) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_sr_policy_proto_rawDescGZIP(), []int{7}
}

func (x *SrPolicyUpdateResponse) GetErrors() []*OperationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type SrPolicyDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []*SrPolicyKey `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *SrPolicyDeleteRequest) Reset() {
	*x = SrPolicyDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_sr_policy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrPolicyDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrPolicyDeleteRequest) ProtoMessage() {}

func (x *SrPolicyDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_sr_policy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrPolicyDeleteRequest.ProtoReflect.Descriptor instead.
func (*SrPolicyDeleteRequest) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_sr_policy_proto_rawDescGZIP(), []int{8}
}

func (x *SrPolicyDeleteRequest) GetKeys() []*SrPolicyKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type SrPolicyDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []*OperationError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *SrPolicyDeleteResponse) Reset() {
	*x = SrPolicyDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_sr_policy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrPolicyDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrPolicyDeleteResponse) ProtoMessage() {}

func (x *SrPolicyDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_sr_policy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrPolicyDeleteResponse.ProtoReflect.Descriptor instead.
func (*SrPolicyDeleteResponse) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_sr_policy_proto_rawDescGZIP(), []int{9}
}

func (x *SrPolicyDeleteResponse) GetErrors() []*OperationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type SrPolicyListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SrPolicyListRequest) Reset() {
	*x = SrPolicyListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_sr_policy_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrPolicyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrPolicyListRequest) ProtoMessage() {}

func (x *SrPolicyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_sr_policy_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrPolicyListRequest.ProtoReflect.Descriptor instead.
func (*SrPolicyListRequest) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_sr_policy_proto_rawDescGZIP(), []int{10}
}

type SrPolicyListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*SrPolicyEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *SrPolicyListResponse) Reset() {
	*x = SrPolicyListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_sr_policy_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrPolicyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrPolicyListResponse) ProtoMessage() {}

func (x *SrPolicyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_sr_policy_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrPolicyListResponse.ProtoReflect.Descriptor instead.
func (*SrPolicyListResponse) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_sr_policy_proto_rawDescGZIP(), []int{11}
}

func (x *SrPolicyListResponse) GetEntries() []*SrPolicyEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_vinbero_v1_sr_policy_proto protoreflect.FileDescriptor

var file_vinbero_v1_sr_policy_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x72, 0x5f,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x76, 0x69,
	0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x16, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72,
	0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x99, 0x01, 0x0a, 0x0b, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x66,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x22, 0x3f, 0x0a, 0x0b,
	0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0xc1, 0x01,
	0x0a, 0x11, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52,
	0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x75, 0x69, 0x73, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d,
	0x64, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x75, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12, 0x1e, 0x0a,
	0x0a, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x22, 0x9d, 0x01, 0x0a, 0x0d, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0a, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x73, 0x22, 0x4c, 0x0a, 0x15, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x08, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76,
	0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x44, 0x65, 0x66, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x22,
	0x4c, 0x0a, 0x16, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x69, 0x6e, 0x62,
	0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x4c, 0x0a,
	0x15, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65,
	0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65,
	0x66, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x22, 0x4c, 0x0a, 0x16, 0x53,
	0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x44, 0x0a, 0x15, 0x53, 0x72, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x72,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22,
	0x4c, 0x0a, 0x16, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x69, 0x6e, 0x62,
	0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x15, 0x0a,
	0x13, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x14, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x07,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x72, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x2a, 0x68, 0x0a, 0x0e, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x1c, 0x53, 0x52, 0x5f, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59,
	0x5f, 0x4f, 0x52, 0x49, 0x47, 0x49, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x52, 0x5f, 0x50, 0x4f, 0x4c, 0x49,
	0x43, 0x59, 0x5f, 0x4f, 0x52, 0x49, 0x47, 0x49, 0x4e, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10,
	0x01, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x52, 0x5f, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59, 0x5f, 0x4f,
	0x52, 0x49, 0x47, 0x49, 0x4e, 0x5f, 0x42, 0x47, 0x50, 0x10, 0x02, 0x32, 0xef, 0x02, 0x0a, 0x0f,
	0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x57, 0x0a, 0x0e, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x21, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x0e, 0x53, 0x72, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x76, 0x69, 0x6e,
	0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x72, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x57, 0x0a, 0x0e, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x53, 0x72,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x76, 0x69, 0x6e,
	0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x76, 0x69,
	0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x9e, 0x01,
	0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31,
	0x42, 0x0d, 0x53, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61,
	0x6b, 0x65, 0x68, 0x61, 0x79, 0x61, 0x2f, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x69,
	0x6e, 0x62, 0x65, 0x72, 0x6f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x56, 0x58, 0x58, 0xaa, 0x02, 0x0a,
	0x56, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0a, 0x56, 0x69, 0x6e,
	0x62, 0x65, 0x72, 0x6f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x16, 0x56, 0x69, 0x6e, 0x62, 0x65, 0x72,
	0x6f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x0b, 0x56, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vinbero_v1_sr_policy_proto_rawDescOnce sync.Once
	file_vinbero_v1_sr_policy_proto_rawDescData = file_vinbero_v1_sr_policy_proto_rawDesc
)

func file_vinbero_v1_sr_policy_proto_rawDescGZIP() []byte {
	file_vinbero_v1_sr_policy_proto_rawDescOnce.Do(func() {
		file_vinbero_v1_sr_policy_proto_rawDescData = protoimpl.X.CompressGZIP(file_vinbero_v1_sr_policy_proto_rawDescData)
	})
	return file_vinbero_v1_sr_policy_proto_rawDescData
}

var file_vinbero_v1_sr_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vinbero_v1_sr_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_vinbero_v1_sr_policy_proto_goTypes = []interface{}{
	(SrPolicyOrigin)(0),            // 0: vinbero.v1.SrPolicyOrigin
	(*SrPolicyDef)(nil),            // 1: vinbero.v1.SrPolicyDef
	(*SrPolicyKey)(nil),            // 2: vinbero.v1.SrPolicyKey
	(*SrPolicyCandidate)(nil),      // 3: vinbero.v1.SrPolicyCandidate
	(*SrPolicyEntry)(nil),          // 4: vinbero.v1.SrPolicyEntry
	(*SrPolicyCreateRequest)(nil),  // 5: vinbero.v1.SrPolicyCreateRequest
	(*SrPolicyCreateResponse)(nil), // 6: vinbero.v1.SrPolicyCreateResponse
	(*SrPolicyUpdateRequest)(nil),  // 7: vinbero.v1.SrPolicyUpdateRequest
	(*SrPolicyUpdateResponse)(nil), // 8: vinbero.v1.SrPolicyUpdateResponse
	(*SrPolicyDeleteRequest)(nil),  // 9: vinbero.v1.SrPolicyDeleteRequest
	(*SrPolicyDeleteResponse)(nil), // 10: vinbero.v1.SrPolicyDeleteResponse
	(*SrPolicyListRequest)(nil),    // 11: vinbero.v1.SrPolicyListRequest
	(*SrPolicyListResponse)(nil),   // 12: vinbero.v1.SrPolicyListResponse
	(*OperationError)(nil),         // 13: vinbero.v1.OperationError
}
var file_vinbero_v1_sr_policy_proto_depIdxs = []int32{
	0,  // 0: vinbero.v1.SrPolicyCandidate.origin:type_name -> vinbero.v1.SrPolicyOrigin
	3,  // 1: vinbero.v1.SrPolicyEntry.candidates:type_name -> vinbero.v1.SrPolicyCandidate
	1,  // 2: vinbero.v1.SrPolicyCreateRequest.policies:type_name -> vinbero.v1.SrPolicyDef
	13, // 3: vinbero.v1.SrPolicyCreateResponse.errors:type_name -> vinbero.v1.OperationError
	1,  // 4: vinbero.v1.SrPolicyUpdateRequest.policies:type_name -> vinbero.v1.SrPolicyDef
	13, // 5: vinbero.v1.SrPolicyUpdateResponse.errors:type_name -> vinbero.v1.OperationError
	2,  // 6: vinbero.v1.SrPolicyDeleteRequest.keys:type_name -> vinbero.v1.SrPolicyKey
	13, // 7: vinbero.v1.SrPolicyDeleteResponse.errors:type_name -> vinbero.v1.OperationError
	4,  // 8: vinbero.v1.SrPolicyListResponse.entries:type_name -> vinbero.v1.SrPolicyEntry
	5,  // 9: vinbero.v1.SrPolicyService.SrPolicyCreate:input_type -> vinbero.v1.SrPolicyCreateRequest
	7,  // 10: vinbero.v1.SrPolicyService.SrPolicyUpdate:input_type -> vinbero.v1.SrPolicyUpdateRequest
	9,  // 11: vinbero.v1.SrPolicyService.SrPolicyDelete:input_type -> vinbero.v1.SrPolicyDeleteRequest
	11, // 12: vinbero.v1.SrPolicyService.SrPolicyList:input_type -> vinbero.v1.SrPolicyListRequest
	6,  // 13: vinbero.v1.SrPolicyService.SrPolicyCreate:output_type -> vinbero.v1.SrPolicyCreateResponse
	8,  // 14: vinbero.v1.SrPolicyService.SrPolicyUpdate:output_type -> vinbero.v1.SrPolicyUpdateResponse
	10, // 15: vinbero.v1.SrPolicyService.SrPolicyDelete:output_type -> vinbero.v1.SrPolicyDeleteResponse
	12, // 16: vinbero.v1.SrPolicyService.SrPolicyList:output_type -> vinbero.v1.SrPolicyListResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_vinbero_v1_sr_policy_proto_init() }
func file_vinbero_v1_sr_policy_proto_init() {
	if File_vinbero_v1_sr_policy_proto != nil {
		return
	}
	file_vinbero_v1_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_vinbero_v1_sr_policy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrPolicyDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_sr_policy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrPolicyKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_sr_policy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrPolicyCandidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_sr_policy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrPolicyEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_sr_policy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrPolicyCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_sr_policy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrPolicyCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_sr_policy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrPolicyUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_sr_policy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrPolicyUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_sr_policy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrPolicyDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_sr_policy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrPolicyDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_sr_policy_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrPolicyListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_sr_policy_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrPolicyListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vinbero_v1_sr_policy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vinbero_v1_sr_policy_proto_goTypes,
		DependencyIndexes: file_vinbero_v1_sr_policy_proto_depIdxs,
		EnumInfos:         file_vinbero_v1_sr_policy_proto_enumTypes,
		MessageInfos:      file_vinbero_v1_sr_policy_proto_msgTypes,
	}.Build()
	File_vinbero_v1_sr_policy_proto = out.File
	file_vinbero_v1_sr_policy_proto_rawDesc = nil
	file_vinbero_v1_sr_policy_proto_goTypes = nil
	file_vinbero_v1_sr_policy_proto_depIdxs = nil
}
