// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: vinbero/v1/sr_policy.proto

package vinberov1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SrPolicyService_SrPolicyCreate_FullMethodName = "/vinbero.v1.SrPolicyService/SrPolicyCreate"
	SrPolicyService_SrPolicyUpdate_FullMethodName = "/vinbero.v1.SrPolicyService/SrPolicyUpdate"
	SrPolicyService_SrPolicyDelete_FullMethodName = "/vinbero.v1.SrPolicyService/SrPolicyDelete"
	SrPolicyService_SrPolicyList_FullMethodName   = "/vinbero.v1.SrPolicyService/SrPolicyList"
)

// SrPolicyServiceClient is the client API for SrPolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrPolicyServiceClient interface {
	SrPolicyCreate(ctx context.Context, in *SrPolicyCreateRequest, opts ...grpc.CallOption) (*SrPolicyCreateResponse, error)
	SrPolicyUpdate(ctx context.Context, in *SrPolicyUpdateRequest, opts ...grpc.CallOption) (*SrPolicyUpdateResponse, error)
	SrPolicyDelete(ctx context.Context, in *SrPolicyDeleteRequest, opts ...grpc.CallOption) (*SrPolicyDeleteResponse, error)
	SrPolicyList(ctx context.Context, in *SrPolicyListRequest, opts ...grpc.CallOption) (*SrPolicyListResponse, error)
}

type srPolicyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSrPolicyServiceClient(cc grpc.ClientConnInterface) SrPolicyServiceClient {
	return &srPolicyServiceClient{cc}
}

func (c *srPolicyServiceClient) SrPolicyCreate(ctx context.Context, in *SrPolicyCreateRequest, opts ...grpc.CallOption) (*SrPolicyCreateResponse, error) {
	out := new(SrPolicyCreateResponse)
	err := c.cc.Invoke(ctx, SrPolicyService_SrPolicyCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srPolicyServiceClient) SrPolicyUpdate(ctx context.Context, in *SrPolicyUpdateRequest, opts ...grpc.CallOption) (*SrPolicyUpdateResponse, error) {
	out := new(SrPolicyUpdateResponse)
	err := c.cc.Invoke(ctx, SrPolicyService_SrPolicyUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srPolicyServiceClient) SrPolicyDelete(ctx context.Context, in *SrPolicyDeleteRequest, opts ...grpc.CallOption) (*SrPolicyDeleteResponse, error) {
	out := new(SrPolicyDeleteResponse)
	err := c.cc.Invoke(ctx, SrPolicyService_SrPolicyDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srPolicyServiceClient) SrPolicyList(ctx context.Context, in *SrPolicyListRequest, opts ...grpc.CallOption) (*SrPolicyListResponse, error) {
	out := new(SrPolicyListResponse)
	err := c.cc.Invoke(ctx, SrPolicyService_SrPolicyList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrPolicyServiceServer is the server API for SrPolicyService service.
// All implementations should embed UnimplementedSrPolicyServiceServer
// for forward compatibility
type SrPolicyServiceServer interface {
	SrPolicyCreate(context.Context, *SrPolicyCreateRequest) (*SrPolicyCreateResponse, error)
	SrPolicyUpdate(context.Context, *SrPolicyUpdateRequest) (*SrPolicyUpdateResponse, error)
	SrPolicyDelete(context.Context, *SrPolicyDeleteRequest) (*SrPolicyDeleteResponse, error)
	SrPolicyList(context.Context, *SrPolicyListRequest) (*SrPolicyListResponse, error)
}

// UnimplementedSrPolicyServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSrPolicyServiceServer struct {
}

func (UnimplementedSrPolicyServiceServer) SrPolicyCreate(context.Context, *SrPolicyCreateRequest) (*SrPolicyCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SrPolicyCreate not implemented")
}
func (UnimplementedSrPolicyServiceServer) SrPolicyUpdate(context.Context, *SrPolicyUpdateRequest) (*SrPolicyUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SrPolicyUpdate not implemented")
}
func (UnimplementedSrPolicyServiceServer) SrPolicyDelete(context.Context, *SrPolicyDeleteRequest) (*SrPolicyDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SrPolicyDelete not implemented")
}
func (UnimplementedSrPolicyServiceServer) SrPolicyList(context.Context, *SrPolicyListRequest) (*SrPolicyListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SrPolicyList not implemented")
}

// UnsafeSrPolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrPolicyServiceServer will
// result in compilation errors.
type UnsafeSrPolicyServiceServer interface {
	mustEmbedUnimplementedSrPolicyServiceServer()
}

func RegisterSrPolicyServiceServer(s grpc.ServiceRegistrar, srv SrPolicyServiceServer) {
	s.RegisterService(&SrPolicyService_ServiceDesc, srv)
}

func _SrPolicyService_SrPolicyCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SrPolicyCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrPolicyServiceServer).SrPolicyCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SrPolicyService_SrPolicyCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrPolicyServiceServer).SrPolicyCreate(ctx, req.(*SrPolicyCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrPolicyService_SrPolicyUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SrPolicyUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrPolicyServiceServer).SrPolicyUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SrPolicyService_SrPolicyUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrPolicyServiceServer).SrPolicyUpdate(ctx, req.(*SrPolicyUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrPolicyService_SrPolicyDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SrPolicyDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrPolicyServiceServer).SrPolicyDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SrPolicyService_SrPolicyDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrPolicyServiceServer).SrPolicyDelete(ctx, req.(*SrPolicyDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrPolicyService_SrPolicyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SrPolicyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrPolicyServiceServer).SrPolicyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SrPolicyService_SrPolicyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrPolicyServiceServer).SrPolicyList(ctx, req.(*SrPolicyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SrPolicyService_ServiceDesc is the grpc.ServiceDesc for SrPolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrPolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vinbero.v1.SrPolicyService",
	HandlerType: (*SrPolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SrPolicyCreate",
			Handler:    _SrPolicyService_SrPolicyCreate_Handler,
		},
		{
			MethodName: "SrPolicyUpdate",
			Handler:    _SrPolicyService_SrPolicyUpdate_Handler,
		},
		{
			MethodName: "SrPolicyDelete",
			Handler:    _SrPolicyService_SrPolicyDelete_Handler,
		},
		{
			MethodName: "SrPolicyList",
			Handler:    _SrPolicyService_SrPolicyList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vinbero/v1/sr_policy.proto",
}
