// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: vinbero/v1/vinbero.proto

package vinberov1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SidFunctionService_SidFunctionCreate_FullMethodName = "/vinbero.v1.SidFunctionService/SidFunctionCreate"
	SidFunctionService_SidFunctionDelete_FullMethodName = "/vinbero.v1.SidFunctionService/SidFunctionDelete"
	SidFunctionService_SidFunctionList_FullMethodName   = "/vinbero.v1.SidFunctionService/SidFunctionList"
	SidFunctionService_SidFunctionGet_FullMethodName    = "/vinbero.v1.SidFunctionService/SidFunctionGet"
)

// SidFunctionServiceClient is the client API for SidFunctionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SidFunctionServiceClient interface {
	SidFunctionCreate(ctx context.Context, in *SidFunctionCreateRequest, opts ...grpc.CallOption) (*SidFunctionCreateResponse, error)
	SidFunctionDelete(ctx context.Context, in *SidFunctionDeleteRequest, opts ...grpc.CallOption) (*SidFunctionDeleteResponse, error)
	SidFunctionList(ctx context.Context, in *SidFunctionListRequest, opts ...grpc.CallOption) (*SidFunctionListResponse, error)
	SidFunctionGet(ctx context.Context, in *SidFunctionGetRequest, opts ...grpc.CallOption) (*SidFunctionGetResponse, error)
}

type sidFunctionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSidFunctionServiceClient(cc grpc.ClientConnInterface) SidFunctionServiceClient {
	return &sidFunctionServiceClient{cc}
}

func (c *sidFunctionServiceClient) SidFunctionCreate(ctx context.Context, in *SidFunctionCreateRequest, opts ...grpc.CallOption) (*SidFunctionCreateResponse, error) {
	out := new(SidFunctionCreateResponse)
	err := c.cc.Invoke(ctx, SidFunctionService_SidFunctionCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidFunctionServiceClient) SidFunctionDelete(ctx context.Context, in *SidFunctionDeleteRequest, opts ...grpc.CallOption) (*SidFunctionDeleteResponse, error) {
	out := new(SidFunctionDeleteResponse)
	err := c.cc.Invoke(ctx, SidFunctionService_SidFunctionDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidFunctionServiceClient) SidFunctionList(ctx context.Context, in *SidFunctionListRequest, opts ...grpc.CallOption) (*SidFunctionListResponse, error) {
	out := new(SidFunctionListResponse)
	err := c.cc.Invoke(ctx, SidFunctionService_SidFunctionList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidFunctionServiceClient) SidFunctionGet(ctx context.Context, in *SidFunctionGetRequest, opts ...grpc.CallOption) (*SidFunctionGetResponse, error) {
	out := new(SidFunctionGetResponse)
	err := c.cc.Invoke(ctx, SidFunctionService_SidFunctionGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SidFunctionServiceServer is the server API for SidFunctionService service.
// All implementations should embed UnimplementedSidFunctionServiceServer
// for forward compatibility
type SidFunctionServiceServer interface {
	SidFunctionCreate(context.Context, *SidFunctionCreateRequest) (*SidFunctionCreateResponse, error)
	SidFunctionDelete(context.Context, *SidFunctionDeleteRequest) (*SidFunctionDeleteResponse, error)
	SidFunctionList(context.Context, *SidFunctionListRequest) (*SidFunctionListResponse, error)
	SidFunctionGet(context.Context, *SidFunctionGetRequest) (*SidFunctionGetResponse, error)
}

// UnimplementedSidFunctionServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSidFunctionServiceServer struct {
}

func (UnimplementedSidFunctionServiceServer) SidFunctionCreate(context.Context, *SidFunctionCreateRequest) (*SidFunctionCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SidFunctionCreate not implemented")
}
func (UnimplementedSidFunctionServiceServer) SidFunctionDelete(context.Context, *SidFunctionDeleteRequest) (*SidFunctionDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SidFunctionDelete not implemented")
}
func (UnimplementedSidFunctionServiceServer) SidFunctionList(context.Context, *SidFunctionListRequest) (*SidFunctionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SidFunctionList not implemented")
}
func (UnimplementedSidFunctionServiceServer) SidFunctionGet(context.Context, *SidFunctionGetRequest) (*SidFunctionGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SidFunctionGet not implemented")
}

// UnsafeSidFunctionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SidFunctionServiceServer will
// result in compilation errors.
type UnsafeSidFunctionServiceServer interface {
	mustEmbedUnimplementedSidFunctionServiceServer()
}

func RegisterSidFunctionServiceServer(s grpc.ServiceRegistrar, srv SidFunctionServiceServer) {
	s.RegisterService(&SidFunctionService_ServiceDesc, srv)
}

func _SidFunctionService_SidFunctionCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SidFunctionCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidFunctionServiceServer).SidFunctionCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidFunctionService_SidFunctionCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidFunctionServiceServer).SidFunctionCreate(ctx, req.(*SidFunctionCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidFunctionService_SidFunctionDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SidFunctionDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidFunctionServiceServer).SidFunctionDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidFunctionService_SidFunctionDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidFunctionServiceServer).SidFunctionDelete(ctx, req.(*SidFunctionDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidFunctionService_SidFunctionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SidFunctionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidFunctionServiceServer).SidFunctionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidFunctionService_SidFunctionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidFunctionServiceServer).SidFunctionList(ctx, req.(*SidFunctionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidFunctionService_SidFunctionGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SidFunctionGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidFunctionServiceServer).SidFunctionGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidFunctionService_SidFunctionGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidFunctionServiceServer).SidFunctionGet(ctx, req.(*SidFunctionGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SidFunctionService_ServiceDesc is the grpc.ServiceDesc for SidFunctionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SidFunctionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vinbero.v1.SidFunctionService",
	HandlerType: (*SidFunctionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SidFunctionCreate",
			Handler:    _SidFunctionService_SidFunctionCreate_Handler,
		},
		{
			MethodName: "SidFunctionDelete",
			Handler:    _SidFunctionService_SidFunctionDelete_Handler,
		},
		{
			MethodName: "SidFunctionList",
			Handler:    _SidFunctionService_SidFunctionList_Handler,
		},
		{
			MethodName: "SidFunctionGet",
			Handler:    _SidFunctionService_SidFunctionGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vinbero/v1/vinbero.proto",
}

const (
	Headendv4Service_Headendv4Create_FullMethodName = "/vinbero.v1.Headendv4Service/Headendv4Create"
	Headendv4Service_Headendv4Delete_FullMethodName = "/vinbero.v1.Headendv4Service/Headendv4Delete"
	Headendv4Service_Headendv4List_FullMethodName   = "/vinbero.v1.Headendv4Service/Headendv4List"
	Headendv4Service_Headendv4Get_FullMethodName    = "/vinbero.v1.Headendv4Service/Headendv4Get"
)

// Headendv4ServiceClient is the client API for Headendv4Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Headendv4ServiceClient interface {
	Headendv4Create(ctx context.Context, in *Headendv4CreateRequest, opts ...grpc.CallOption) (*Headendv4CreateResponse, error)
	Headendv4Delete(ctx context.Context, in *Headendv4DeleteRequest, opts ...grpc.CallOption) (*Headendv4DeleteResponse, error)
	Headendv4List(ctx context.Context, in *Headendv4ListRequest, opts ...grpc.CallOption) (*Headendv4ListResponse, error)
	Headendv4Get(ctx context.Context, in *Headendv4GetRequest, opts ...grpc.CallOption) (*Headendv4GetResponse, error)
}

type headendv4ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeadendv4ServiceClient(cc grpc.ClientConnInterface) Headendv4ServiceClient {
	return &headendv4ServiceClient{cc}
}

func (c *headendv4ServiceClient) Headendv4Create(ctx context.Context, in *Headendv4CreateRequest, opts ...grpc.CallOption) (*Headendv4CreateResponse, error) {
	out := new(Headendv4CreateResponse)
	err := c.cc.Invoke(ctx, Headendv4Service_Headendv4Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *headendv4ServiceClient) Headendv4Delete(ctx context.Context, in *Headendv4DeleteRequest, opts ...grpc.CallOption) (*Headendv4DeleteResponse, error) {
	out := new(Headendv4DeleteResponse)
	err := c.cc.Invoke(ctx, Headendv4Service_Headendv4Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *headendv4ServiceClient) Headendv4List(ctx context.Context, in *Headendv4ListRequest, opts ...grpc.CallOption) (*Headendv4ListResponse, error) {
	out := new(Headendv4ListResponse)
	err := c.cc.Invoke(ctx, Headendv4Service_Headendv4List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *headendv4ServiceClient) Headendv4Get(ctx context.Context, in *Headendv4GetRequest, opts ...grpc.CallOption) (*Headendv4GetResponse, error) {
	out := new(Headendv4GetResponse)
	err := c.cc.Invoke(ctx, Headendv4Service_Headendv4Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Headendv4ServiceServer is the server API for Headendv4Service service.
// All implementations should embed UnimplementedHeadendv4ServiceServer
// for forward compatibility
type Headendv4ServiceServer interface {
	Headendv4Create(context.Context, *Headendv4CreateRequest) (*Headendv4CreateResponse, error)
	Headendv4Delete(context.Context, *Headendv4DeleteRequest) (*Headendv4DeleteResponse, error)
	Headendv4List(context.Context, *Headendv4ListRequest) (*Headendv4ListResponse, error)
	Headendv4Get(context.Context, *Headendv4GetRequest) (*Headendv4GetResponse, error)
}

// UnimplementedHeadendv4ServiceServer should be embedded to have forward compatible implementations.
type UnimplementedHeadendv4ServiceServer struct {
}

func (UnimplementedHeadendv4ServiceServer) Headendv4Create(context.Context, *Headendv4CreateRequest) (*Headendv4CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Headendv4Create not implemented")
}
func (UnimplementedHeadendv4ServiceServer) Headendv4Delete(context.Context, *Headendv4DeleteRequest) (*Headendv4DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Headendv4Delete not implemented")
}
func (UnimplementedHeadendv4ServiceServer) Headendv4List(context.Context, *Headendv4ListRequest) (*Headendv4ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Headendv4List not implemented")
}
func (UnimplementedHeadendv4ServiceServer) Headendv4Get(context.Context, *Headendv4GetRequest) (*Headendv4GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Headendv4Get not implemented")
}

// UnsafeHeadendv4ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Headendv4ServiceServer will
// result in compilation errors.
type UnsafeHeadendv4ServiceServer interface {
	mustEmbedUnimplementedHeadendv4ServiceServer()
}

func RegisterHeadendv4ServiceServer(s grpc.ServiceRegistrar, srv Headendv4ServiceServer) {
	s.RegisterService(&Headendv4Service_ServiceDesc, srv)
}

func _Headendv4Service_Headendv4Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Headendv4CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Headendv4ServiceServer).Headendv4Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Headendv4Service_Headendv4Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Headendv4ServiceServer).Headendv4Create(ctx, req.(*Headendv4CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Headendv4Service_Headendv4Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Headendv4DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Headendv4ServiceServer).Headendv4Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Headendv4Service_Headendv4Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Headendv4ServiceServer).Headendv4Delete(ctx, req.(*Headendv4DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Headendv4Service_Headendv4List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Headendv4ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Headendv4ServiceServer).Headendv4List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Headendv4Service_Headendv4List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Headendv4ServiceServer).Headendv4List(ctx, req.(*Headendv4ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Headendv4Service_Headendv4Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Headendv4GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Headendv4ServiceServer).Headendv4Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Headendv4Service_Headendv4Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Headendv4ServiceServer).Headendv4Get(ctx, req.(*Headendv4GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Headendv4Service_ServiceDesc is the grpc.ServiceDesc for Headendv4Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Headendv4Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vinbero.v1.Headendv4Service",
	HandlerType: (*Headendv4ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Headendv4Create",
			Handler:    _Headendv4Service_Headendv4Create_Handler,
		},
		{
			MethodName: "Headendv4Delete",
			Handler:    _Headendv4Service_Headendv4Delete_Handler,
		},
		{
			MethodName: "Headendv4List",
			Handler:    _Headendv4Service_Headendv4List_Handler,
		},
		{
			MethodName: "Headendv4Get",
			Handler:    _Headendv4Service_Headendv4Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vinbero/v1/vinbero.proto",
}

const (
	Headendv6Service_Headendv6Create_FullMethodName = "/vinbero.v1.Headendv6Service/Headendv6Create"
	Headendv6Service_Headendv6Delete_FullMethodName = "/vinbero.v1.Headendv6Service/Headendv6Delete"
	Headendv6Service_Headendv6List_FullMethodName   = "/vinbero.v1.Headendv6Service/Headendv6List"
	Headendv6Service_Headendv6Get_FullMethodName    = "/vinbero.v1.Headendv6Service/Headendv6Get"
)

// Headendv6ServiceClient is the client API for Headendv6Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Headendv6ServiceClient interface {
	Headendv6Create(ctx context.Context, in *Headendv6CreateRequest, opts ...grpc.CallOption) (*Headendv6CreateResponse, error)
	Headendv6Delete(ctx context.Context, in *Headendv6DeleteRequest, opts ...grpc.CallOption) (*Headendv6DeleteResponse, error)
	Headendv6List(ctx context.Context, in *Headendv6ListRequest, opts ...grpc.CallOption) (*Headendv6ListResponse, error)
	Headendv6Get(ctx context.Context, in *Headendv6GetRequest, opts ...grpc.CallOption) (*Headendv6GetResponse, error)
}

type headendv6ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeadendv6ServiceClient(cc grpc.ClientConnInterface) Headendv6ServiceClient {
	return &headendv6ServiceClient{cc}
}

func (c *headendv6ServiceClient) Headendv6Create(ctx context.Context, in *Headendv6CreateRequest, opts ...grpc.CallOption) (*Headendv6CreateResponse, error) {
	out := new(Headendv6CreateResponse)
	err := c.cc.Invoke(ctx, Headendv6Service_Headendv6Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *headendv6ServiceClient) Headendv6Delete(ctx context.Context, in *Headendv6DeleteRequest, opts ...grpc.CallOption) (*Headendv6DeleteResponse, error) {
	out := new(Headendv6DeleteResponse)
	err := c.cc.Invoke(ctx, Headendv6Service_Headendv6Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *headendv6ServiceClient) Headendv6List(ctx context.Context, in *Headendv6ListRequest, opts ...grpc.CallOption) (*Headendv6ListResponse, error) {
	out := new(Headendv6ListResponse)
	err := c.cc.Invoke(ctx, Headendv6Service_Headendv6List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *headendv6ServiceClient) Headendv6Get(ctx context.Context, in *Headendv6GetRequest, opts ...grpc.CallOption) (*Headendv6GetResponse, error) {
	out := new(Headendv6GetResponse)
	err := c.cc.Invoke(ctx, Headendv6Service_Headendv6Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Headendv6ServiceServer is the server API for Headendv6Service service.
// All implementations should embed UnimplementedHeadendv6ServiceServer
// for forward compatibility
type Headendv6ServiceServer interface {
	Headendv6Create(context.Context, *Headendv6CreateRequest) (*Headendv6CreateResponse, error)
	Headendv6Delete(context.Context, *Headendv6DeleteRequest) (*Headendv6DeleteResponse, error)
	Headendv6List(context.Context, *Headendv6ListRequest) (*Headendv6ListResponse, error)
	Headendv6Get(context.Context, *Headendv6GetRequest) (*Headendv6GetResponse, error)
}

// UnimplementedHeadendv6ServiceServer should be embedded to have forward compatible implementations.
type UnimplementedHeadendv6ServiceServer struct {
}

func (UnimplementedHeadendv6ServiceServer) Headendv6Create(context.Context, *Headendv6CreateRequest) (*Headendv6CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Headendv6Create not implemented")
}
func (UnimplementedHeadendv6ServiceServer) Headendv6Delete(context.Context, *Headendv6DeleteRequest) (*Headendv6DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Headendv6Delete not implemented")
}
func (UnimplementedHeadendv6ServiceServer) Headendv6List(context.Context, *Headendv6ListRequest) (*Headendv6ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Headendv6List not implemented")
}
func (UnimplementedHeadendv6ServiceServer) Headendv6Get(context.Context, *Headendv6GetRequest) (*Headendv6GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Headendv6Get not implemented")
}

// UnsafeHeadendv6ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Headendv6ServiceServer will
// result in compilation errors.
type UnsafeHeadendv6ServiceServer interface {
	mustEmbedUnimplementedHeadendv6ServiceServer()
}

func RegisterHeadendv6ServiceServer(s grpc.ServiceRegistrar, srv Headendv6ServiceServer) {
	s.RegisterService(&Headendv6Service_ServiceDesc, srv)
}

func _Headendv6Service_Headendv6Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Headendv6CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Headendv6ServiceServer).Headendv6Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Headendv6Service_Headendv6Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Headendv6ServiceServer).Headendv6Create(ctx, req.(*Headendv6CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Headendv6Service_Headendv6Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Headendv6DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Headendv6ServiceServer).Headendv6Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Headendv6Service_Headendv6Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Headendv6ServiceServer).Headendv6Delete(ctx, req.(*Headendv6DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Headendv6Service_Headendv6List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Headendv6ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Headendv6ServiceServer).Headendv6List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Headendv6Service_Headendv6List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Headendv6ServiceServer).Headendv6List(ctx, req.(*Headendv6ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Headendv6Service_Headendv6Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Headendv6GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Headendv6ServiceServer).Headendv6Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Headendv6Service_Headendv6Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Headendv6ServiceServer).Headendv6Get(ctx, req.(*Headendv6GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Headendv6Service_ServiceDesc is the grpc.ServiceDesc for Headendv6Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Headendv6Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vinbero.v1.Headendv6Service",
	HandlerType: (*Headendv6ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Headendv6Create",
			Handler:    _Headendv6Service_Headendv6Create_Handler,
		},
		{
			MethodName: "Headendv6Delete",
			Handler:    _Headendv6Service_Headendv6Delete_Handler,
		},
		{
			MethodName: "Headendv6List",
			Handler:    _Headendv6Service_Headendv6List_Handler,
		},
		{
			MethodName: "Headendv6Get",
			Handler:    _Headendv6Service_Headendv6Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vinbero/v1/vinbero.proto",
}

const (
	DmacService_DmacList_FullMethodName = "/vinbero.v1.DmacService/DmacList"
)

// DmacServiceClient is the client API for DmacService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DmacServiceClient interface {
	DmacList(ctx context.Context, in *DmacListRequest, opts ...grpc.CallOption) (*DmacListResponse, error)
}

type dmacServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDmacServiceClient(cc grpc.ClientConnInterface) DmacServiceClient {
	return &dmacServiceClient{cc}
}

func (c *dmacServiceClient) DmacList(ctx context.Context, in *DmacListRequest, opts ...grpc.CallOption) (*DmacListResponse, error) {
	out := new(DmacListResponse)
	err := c.cc.Invoke(ctx, DmacService_DmacList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DmacServiceServer is the server API for DmacService service.
// All implementations should embed UnimplementedDmacServiceServer
// for forward compatibility
type DmacServiceServer interface {
	DmacList(context.Context, *DmacListRequest) (*DmacListResponse, error)
}

// UnimplementedDmacServiceServer should be embedded to have forward compatible implementations.
type UnimplementedDmacServiceServer struct {
}

func (UnimplementedDmacServiceServer) DmacList(context.Context, *DmacListRequest) (*DmacListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DmacList not implemented")
}

// UnsafeDmacServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DmacServiceServer will
// result in compilation errors.
type UnsafeDmacServiceServer interface {
	mustEmbedUnimplementedDmacServiceServer()
}

func RegisterDmacServiceServer(s grpc.ServiceRegistrar, srv DmacServiceServer) {
	s.RegisterService(&DmacService_ServiceDesc, srv)
}

func _DmacService_DmacList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DmacListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmacServiceServer).DmacList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DmacService_DmacList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmacServiceServer).DmacList(ctx, req.(*DmacListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DmacService_ServiceDesc is the grpc.ServiceDesc for DmacService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DmacService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vinbero.v1.DmacService",
	HandlerType: (*DmacServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DmacList",
			Handler:    _DmacService_DmacList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vinbero/v1/vinbero.proto",
}

const (
	BdPeerService_BdPeerCreate_FullMethodName = "/vinbero.v1.BdPeerService/BdPeerCreate"
	BdPeerService_BdPeerDelete_FullMethodName = "/vinbero.v1.BdPeerService/BdPeerDelete"
	BdPeerService_BdPeerList_FullMethodName   = "/vinbero.v1.BdPeerService/BdPeerList"
)

// BdPeerServiceClient is the client API for BdPeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BdPeerServiceClient interface {
	BdPeerCreate(ctx context.Context, in *BdPeerCreateRequest, opts ...grpc.CallOption) (*BdPeerCreateResponse, error)
	BdPeerDelete(ctx context.Context, in *BdPeerDeleteRequest, opts ...grpc.CallOption) (*BdPeerDeleteResponse, error)
	BdPeerList(ctx context.Context, in *BdPeerListRequest, opts ...grpc.CallOption) (*BdPeerListResponse, error)
}

type bdPeerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBdPeerServiceClient(cc grpc.ClientConnInterface) BdPeerServiceClient {
	return &bdPeerServiceClient{cc}
}

func (c *bdPeerServiceClient) BdPeerCreate(ctx context.Context, in *BdPeerCreateRequest, opts ...grpc.CallOption) (*BdPeerCreateResponse, error) {
	out := new(BdPeerCreateResponse)
	err := c.cc.Invoke(ctx, BdPeerService_BdPeerCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bdPeerServiceClient) BdPeerDelete(ctx context.Context, in *BdPeerDeleteRequest, opts ...grpc.CallOption) (*BdPeerDeleteResponse, error) {
	out := new(BdPeerDeleteResponse)
	err := c.cc.Invoke(ctx, BdPeerService_BdPeerDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bdPeerServiceClient) BdPeerList(ctx context.Context, in *BdPeerListRequest, opts ...grpc.CallOption) (*BdPeerListResponse, error) {
	out := new(BdPeerListResponse)
	err := c.cc.Invoke(ctx, BdPeerService_BdPeerList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BdPeerServiceServer is the server API for BdPeerService service.
// All implementations should embed UnimplementedBdPeerServiceServer
// for forward compatibility
type BdPeerServiceServer interface {
	BdPeerCreate(context.Context, *BdPeerCreateRequest) (*BdPeerCreateResponse, error)
	BdPeerDelete(context.Context, *BdPeerDeleteRequest) (*BdPeerDeleteResponse, error)
	BdPeerList(context.Context, *BdPeerListRequest) (*BdPeerListResponse, error)
}

// UnimplementedBdPeerServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBdPeerServiceServer struct {
}

func (UnimplementedBdPeerServiceServer) BdPeerCreate(context.Context, *BdPeerCreateRequest) (*BdPeerCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BdPeerCreate not implemented")
}
func (UnimplementedBdPeerServiceServer) BdPeerDelete(context.Context, *BdPeerDeleteRequest) (*BdPeerDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BdPeerDelete not implemented")
}
func (UnimplementedBdPeerServiceServer) BdPeerList(context.Context, *BdPeerListRequest) (*BdPeerListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BdPeerList not implemented")
}

// UnsafeBdPeerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BdPeerServiceServer will
// result in compilation errors.
type UnsafeBdPeerServiceServer interface {
	mustEmbedUnimplementedBdPeerServiceServer()
}

func RegisterBdPeerServiceServer(s grpc.ServiceRegistrar, srv BdPeerServiceServer) {
	s.RegisterService(&BdPeerService_ServiceDesc, srv)
}

func _BdPeerService_BdPeerCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BdPeerCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BdPeerServiceServer).BdPeerCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BdPeerService_BdPeerCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BdPeerServiceServer).BdPeerCreate(ctx, req.(*BdPeerCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BdPeerService_BdPeerDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BdPeerDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BdPeerServiceServer).BdPeerDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BdPeerService_BdPeerDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BdPeerServiceServer).BdPeerDelete(ctx, req.(*BdPeerDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BdPeerService_BdPeerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BdPeerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BdPeerServiceServer).BdPeerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BdPeerService_BdPeerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BdPeerServiceServer).BdPeerList(ctx, req.(*BdPeerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BdPeerService_ServiceDesc is the grpc.ServiceDesc for BdPeerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BdPeerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vinbero.v1.BdPeerService",
	HandlerType: (*BdPeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BdPeerCreate",
			Handler:    _BdPeerService_BdPeerCreate_Handler,
		},
		{
			MethodName: "BdPeerDelete",
			Handler:    _BdPeerService_BdPeerDelete_Handler,
		},
		{
			MethodName: "BdPeerList",
			Handler:    _BdPeerService_BdPeerList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vinbero/v1/vinbero.proto",
}

const (
	HeadendL2Service_HeadendL2Create_FullMethodName = "/vinbero.v1.HeadendL2Service/HeadendL2Create"
	HeadendL2Service_HeadendL2Delete_FullMethodName = "/vinbero.v1.HeadendL2Service/HeadendL2Delete"
	HeadendL2Service_HeadendL2List_FullMethodName   = "/vinbero.v1.HeadendL2Service/HeadendL2List"
	HeadendL2Service_HeadendL2Get_FullMethodName    = "/vinbero.v1.HeadendL2Service/HeadendL2Get"
)

// HeadendL2ServiceClient is the client API for HeadendL2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeadendL2ServiceClient interface {
	HeadendL2Create(ctx context.Context, in *HeadendL2CreateRequest, opts ...grpc.CallOption) (*HeadendL2CreateResponse, error)
	HeadendL2Delete(ctx context.Context, in *HeadendL2DeleteRequest, opts ...grpc.CallOption) (*HeadendL2DeleteResponse, error)
	HeadendL2List(ctx context.Context, in *HeadendL2ListRequest, opts ...grpc.CallOption) (*HeadendL2ListResponse, error)
	HeadendL2Get(ctx context.Context, in *HeadendL2GetRequest, opts ...grpc.CallOption) (*HeadendL2GetResponse, error)
}

type headendL2ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeadendL2ServiceClient(cc grpc.ClientConnInterface) HeadendL2ServiceClient {
	return &headendL2ServiceClient{cc}
}

func (c *headendL2ServiceClient) HeadendL2Create(ctx context.Context, in *HeadendL2CreateRequest, opts ...grpc.CallOption) (*HeadendL2CreateResponse, error) {
	out := new(HeadendL2CreateResponse)
	err := c.cc.Invoke(ctx, HeadendL2Service_HeadendL2Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *headendL2ServiceClient) HeadendL2Delete(ctx context.Context, in *HeadendL2DeleteRequest, opts ...grpc.CallOption) (*HeadendL2DeleteResponse, error) {
	out := new(HeadendL2DeleteResponse)
	err := c.cc.Invoke(ctx, HeadendL2Service_HeadendL2Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *headendL2ServiceClient) HeadendL2List(ctx context.Context, in *HeadendL2ListRequest, opts ...grpc.CallOption) (*HeadendL2ListResponse, error) {
	out := new(HeadendL2ListResponse)
	err := c.cc.Invoke(ctx, HeadendL2Service_HeadendL2List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *headendL2ServiceClient) HeadendL2Get(ctx context.Context, in *HeadendL2GetRequest, opts ...grpc.CallOption) (*HeadendL2GetResponse, error) {
	out := new(HeadendL2GetResponse)
	err := c.cc.Invoke(ctx, HeadendL2Service_HeadendL2Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeadendL2ServiceServer is the server API for HeadendL2Service service.
// All implementations should embed UnimplementedHeadendL2ServiceServer
// for forward compatibility
type HeadendL2ServiceServer interface {
	HeadendL2Create(context.Context, *HeadendL2CreateRequest) (*HeadendL2CreateResponse, error)
	HeadendL2Delete(context.Context, *HeadendL2DeleteRequest) (*HeadendL2DeleteResponse, error)
	HeadendL2List(context.Context, *HeadendL2ListRequest) (*HeadendL2ListResponse, error)
	HeadendL2Get(context.Context, *HeadendL2GetRequest) (*HeadendL2GetResponse, error)
}

// UnimplementedHeadendL2ServiceServer should be embedded to have forward compatible implementations.
type UnimplementedHeadendL2ServiceServer struct {
}

func (UnimplementedHeadendL2ServiceServer) HeadendL2Create(context.Context, *HeadendL2CreateRequest) (*HeadendL2CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeadendL2Create not implemented")
}
func (UnimplementedHeadendL2ServiceServer) HeadendL2Delete(context.Context, *HeadendL2DeleteRequest) (*HeadendL2DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeadendL2Delete not implemented")
}
func (UnimplementedHeadendL2ServiceServer) HeadendL2List(context.Context, *HeadendL2ListRequest) (*HeadendL2ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeadendL2List not implemented")
}
func (UnimplementedHeadendL2ServiceServer) HeadendL2Get(context.Context, *HeadendL2GetRequest) (*HeadendL2GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeadendL2Get not implemented")
}

// UnsafeHeadendL2ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeadendL2ServiceServer will
// result in compilation errors.
type UnsafeHeadendL2ServiceServer interface {
	mustEmbedUnimplementedHeadendL2ServiceServer()
}

func RegisterHeadendL2ServiceServer(s grpc.ServiceRegistrar, srv HeadendL2ServiceServer) {
	s.RegisterService(&HeadendL2Service_ServiceDesc, srv)
}

func _HeadendL2Service_HeadendL2Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeadendL2CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeadendL2ServiceServer).HeadendL2Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeadendL2Service_HeadendL2Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeadendL2ServiceServer).HeadendL2Create(ctx, req.(*HeadendL2CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeadendL2Service_HeadendL2Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeadendL2DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeadendL2ServiceServer).HeadendL2Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeadendL2Service_HeadendL2Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeadendL2ServiceServer).HeadendL2Delete(ctx, req.(*HeadendL2DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeadendL2Service_HeadendL2List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeadendL2ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeadendL2ServiceServer).HeadendL2List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeadendL2Service_HeadendL2List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeadendL2ServiceServer).HeadendL2List(ctx, req.(*HeadendL2ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeadendL2Service_HeadendL2Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeadendL2GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeadendL2ServiceServer).HeadendL2Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeadendL2Service_HeadendL2Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeadendL2ServiceServer).HeadendL2Get(ctx, req.(*HeadendL2GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HeadendL2Service_ServiceDesc is the grpc.ServiceDesc for HeadendL2Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeadendL2Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vinbero.v1.HeadendL2Service",
	HandlerType: (*HeadendL2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HeadendL2Create",
			Handler:    _HeadendL2Service_HeadendL2Create_Handler,
		},
		{
			MethodName: "HeadendL2Delete",
			Handler:    _HeadendL2Service_HeadendL2Delete_Handler,
		},
		{
			MethodName: "HeadendL2List",
			Handler:    _HeadendL2Service_HeadendL2List_Handler,
		},
		{
			MethodName: "HeadendL2Get",
			Handler:    _HeadendL2Service_HeadendL2Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vinbero/v1/vinbero.proto",
}
