// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: vinbero/v1/vrf_bgp.proto

package vinberov1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VrfBgpBinding is one VRF's BGP route-target policy.
type VrfBgpBinding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VrfName        string   `protobuf:"bytes,1,opt,name=vrf_name,json=vrfName,proto3" json:"vrf_name,omitempty"`
	ImportRts      []string `protobuf:"bytes,2,rep,name=import_rts,json=importRts,proto3" json:"import_rts,omitempty"`                // route targets accepted on receive, "65000:100" form
	ExportRts      []string `protobuf:"bytes,3,rep,name=export_rts,json=exportRts,proto3" json:"export_rts,omitempty"`                // route targets attached on advertise
	DefaultLocator string   `protobuf:"bytes,4,opt,name=default_locator,json=defaultLocator,proto3" json:"default_locator,omitempty"` // locator name for this VRF's local SIDs
}

func (x *VrfBgpBinding) Reset() {
	*x = VrfBgpBinding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfBgpBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfBgpBinding) ProtoMessage() {}

func (x *VrfBgpBinding) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VrfBgpBinding.ProtoReflect.Descriptor instead.
func (*VrfBgpBinding) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_vrf_bgp_proto_rawDescGZIP(), []int{0}
}

func (x *VrfBgpBinding) GetVrfName() string {
	if x != nil {
		return x.VrfName
	}
	return ""
}

func (x *VrfBgpBinding) GetImportRts() []string {
	if x != nil {
		return x.ImportRts
	}
	return nil
}

func (x *VrfBgpBinding) GetExportRts() []string {
	if x != nil {
		return x.ExportRts
	}
	return nil
}

func (x *VrfBgpBinding) GetDefaultLocator() string {
	if x != nil {
		return x.DefaultLocator
	}
	return ""
}

type VrfBgpBindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bindings []*VrfBgpBinding `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
}

func (x *VrfBgpBindRequest) Reset() {
	*x = VrfBgpBindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfBgpBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfBgpBindRequest) ProtoMessage() {}

func (x *VrfBgpBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VrfBgpBindRequest.ProtoReflect.Descriptor instead.
func (*VrfBgpBindRequest) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_vrf_bgp_proto_rawDescGZIP(), []int{1}
}

func (x *VrfBgpBindRequest) GetBindings() []*VrfBgpBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type VrfBgpBindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bound  []*VrfBgpBinding  `protobuf:"bytes,1,rep,name=bound,proto3" json:"bound,omitempty"`
	Errors []*OperationError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *VrfBgpBindResponse) Reset() {
	*x = VrfBgpBindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfBgpBindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfBgpBindResponse) ProtoMessage() {}

func (x *VrfBgpBindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VrfBgpBindResponse.ProtoReflect.Descriptor instead.
func (*VrfBgpBindResponse) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_vrf_bgp_proto_rawDescGZIP(), []int{2}
}

func (x *VrfBgpBindResponse) GetBound() []*VrfBgpBinding {
	if x != nil {
		return x.Bound
	}
	return nil
}

func (x *VrfBgpBindResponse) GetErrors() []*OperationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type VrfBgpUnbindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VrfNames []string `protobuf:"bytes,1,rep,name=vrf_names,json=vrfNames,proto3" json:"vrf_names,omitempty"`
}

func (x *VrfBgpUnbindRequest) Reset() {
	*x = VrfBgpUnbindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfBgpUnbindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfBgpUnbindRequest) ProtoMessage() {}

func (x *VrfBgpUnbindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VrfBgpUnbindRequest.ProtoReflect.Descriptor instead.
func (*VrfBgpUnbindRequest) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_vrf_bgp_proto_rawDescGZIP(), []int{3}
}

func (x *VrfBgpUnbindRequest) GetVrfNames() []string {
	if x != nil {
		return x.VrfNames
	}
	return nil
}

type VrfBgpUnbindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnboundVrfNames []string          `protobuf:"bytes,1,rep,name=unbound_vrf_names,json=unboundVrfNames,proto3" json:"unbound_vrf_names,omitempty"`
	Errors          []*OperationError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *VrfBgpUnbindResponse) Reset() {
	*x = VrfBgpUnbindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfBgpUnbindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfBgpUnbindResponse) ProtoMessage() {}

func (x *VrfBgpUnbindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VrfBgpUnbindResponse.ProtoReflect.Descriptor instead.
func (*VrfBgpUnbindResponse) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_vrf_bgp_proto_rawDescGZIP(), []int{4}
}

func (x *VrfBgpUnbindResponse) GetUnboundVrfNames() []string {
	if x != nil {
		return x.UnboundVrfNames
	}
	return nil
}

func (x *VrfBgpUnbindResponse) GetErrors() []*OperationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type VrfBgpListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VrfBgpListRequest) Reset() {
	*x = VrfBgpListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfBgpListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfBgpListRequest) ProtoMessage() {}

func (x *VrfBgpListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VrfBgpListRequest.ProtoReflect.Descriptor instead.
func (*VrfBgpListRequest) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_vrf_bgp_proto_rawDescGZIP(), []int{5}
}

type VrfBgpListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bindings []*VrfBgpBinding `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
}

func (x *VrfBgpListResponse) Reset() {
	*x = VrfBgpListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfBgpListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfBgpListResponse) ProtoMessage() {}

func (x *VrfBgpListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vinbero_v1_vrf_bgp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VrfBgpListResponse.ProtoReflect.Descriptor instead.
func (*VrfBgpListResponse) Descriptor() ([]byte, []int) {
	return file_vinbero_v1_vrf_bgp_proto_rawDescGZIP(), []int{6}
}

func (x *VrfBgpListResponse) GetBindings() []*VrfBgpBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

var File_vinbero_v1_vrf_bgp_proto protoreflect.FileDescriptor

var file_vinbero_v1_vrf_bgp_proto_rawDesc = []byte{
	0x0a, 0x18, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x72, 0x66,
	0x5f, 0x62, 0x67, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x76, 0x69, 0x6e, 0x62,
	0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x16, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2f,
	0x76, 0x31, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91,
	0x01, 0x0a, 0x0d, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x12, 0x19, 0x0a, 0x08, 0x76, 0x72, 0x66, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x72, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x22, 0x4a, 0x0a, 0x11, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x42, 0x69, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x08, 0x62, 0x69, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x69, 0x6e, 0x62,
	0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x42, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x79,
	0x0a, 0x12, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x05,
	0x62, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x32, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x32, 0x0a, 0x13, 0x56, 0x72, 0x66,
	0x42, 0x67, 0x70, 0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x76, 0x72, 0x66, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x76, 0x72, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x76, 0x0a,
	0x14, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x75, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64,
	0x5f, 0x76, 0x72, 0x66, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0f, 0x75, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x56, 0x72, 0x66, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x12, 0x32, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x12, 0x56, 0x72,
	0x66, 0x42, 0x67, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x35, 0x0a, 0x08, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x62,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x32, 0xfc, 0x01, 0x0a, 0x0d, 0x56, 0x72, 0x66, 0x42,
	0x67, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x56, 0x72, 0x66,
	0x42, 0x67, 0x70, 0x42, 0x69, 0x6e, 0x64, 0x12, 0x1d, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x42, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70,
	0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x12, 0x1f, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x55, 0x6e, 0x62, 0x69, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x56, 0x72, 0x66,
	0x42, 0x67, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x56, 0x72, 0x66, 0x42, 0x67, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x9c, 0x01, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x76,
	0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x56, 0x72, 0x66, 0x42, 0x67,
	0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x6b, 0x65, 0x68, 0x61, 0x79, 0x61, 0x2f, 0x76, 0x69,
	0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72,
	0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x76, 0x31, 0xa2, 0x02,
	0x03, 0x56, 0x58, 0x58, 0xaa, 0x02, 0x0a, 0x56, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x0a, 0x56, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x5c, 0x56, 0x31, 0xe2, 0x02,
	0x16, 0x56, 0x69, 0x6e, 0x62, 0x65, 0x72, 0x6f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0b, 0x56, 0x69, 0x6e, 0x62, 0x65, 0x72,
	0x6f, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vinbero_v1_vrf_bgp_proto_rawDescOnce sync.Once
	file_vinbero_v1_vrf_bgp_proto_rawDescData = file_vinbero_v1_vrf_bgp_proto_rawDesc
)

func file_vinbero_v1_vrf_bgp_proto_rawDescGZIP() []byte {
	file_vinbero_v1_vrf_bgp_proto_rawDescOnce.Do(func() {
		file_vinbero_v1_vrf_bgp_proto_rawDescData = protoimpl.X.CompressGZIP(file_vinbero_v1_vrf_bgp_proto_rawDescData)
	})
	return file_vinbero_v1_vrf_bgp_proto_rawDescData
}

var file_vinbero_v1_vrf_bgp_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_vinbero_v1_vrf_bgp_proto_goTypes = []interface{}{
	(*VrfBgpBinding)(nil),        // 0: vinbero.v1.VrfBgpBinding
	(*VrfBgpBindRequest)(nil),    // 1: vinbero.v1.VrfBgpBindRequest
	(*VrfBgpBindResponse)(nil),   // 2: vinbero.v1.VrfBgpBindResponse
	(*VrfBgpUnbindRequest)(nil),  // 3: vinbero.v1.VrfBgpUnbindRequest
	(*VrfBgpUnbindResponse)(nil), // 4: vinbero.v1.VrfBgpUnbindResponse
	(*VrfBgpListRequest)(nil),    // 5: vinbero.v1.VrfBgpListRequest
	(*VrfBgpListResponse)(nil),   // 6: vinbero.v1.VrfBgpListResponse
	(*OperationError)(nil),       // 7: vinbero.v1.OperationError
}
var file_vinbero_v1_vrf_bgp_proto_depIdxs = []int32{
	0, // 0: vinbero.v1.VrfBgpBindRequest.bindings:type_name -> vinbero.v1.VrfBgpBinding
	0, // 1: vinbero.v1.VrfBgpBindResponse.bound:type_name -> vinbero.v1.VrfBgpBinding
	7, // 2: vinbero.v1.VrfBgpBindResponse.errors:type_name -> vinbero.v1.OperationError
	7, // 3: vinbero.v1.VrfBgpUnbindResponse.errors:type_name -> vinbero.v1.OperationError
	0, // 4: vinbero.v1.VrfBgpListResponse.bindings:type_name -> vinbero.v1.VrfBgpBinding
	1, // 5: vinbero.v1.VrfBgpService.VrfBgpBind:input_type -> vinbero.v1.VrfBgpBindRequest
	3, // 6: vinbero.v1.VrfBgpService.VrfBgpUnbind:input_type -> vinbero.v1.VrfBgpUnbindRequest
	5, // 7: vinbero.v1.VrfBgpService.VrfBgpList:input_type -> vinbero.v1.VrfBgpListRequest
	2, // 8: vinbero.v1.VrfBgpService.VrfBgpBind:output_type -> vinbero.v1.VrfBgpBindResponse
	4, // 9: vinbero.v1.VrfBgpService.VrfBgpUnbind:output_type -> vinbero.v1.VrfBgpUnbindResponse
	6, // 10: vinbero.v1.VrfBgpService.VrfBgpList:output_type -> vinbero.v1.VrfBgpListResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_vinbero_v1_vrf_bgp_proto_init() }
func file_vinbero_v1_vrf_bgp_proto_init() {
	if File_vinbero_v1_vrf_bgp_proto != nil {
		return
	}
	file_vinbero_v1_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_vinbero_v1_vrf_bgp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfBgpBinding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_vrf_bgp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfBgpBindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_vrf_bgp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfBgpBindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_vrf_bgp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfBgpUnbindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_vrf_bgp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfBgpUnbindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_vrf_bgp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfBgpListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vinbero_v1_vrf_bgp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfBgpListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vinbero_v1_vrf_bgp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vinbero_v1_vrf_bgp_proto_goTypes,
		DependencyIndexes: file_vinbero_v1_vrf_bgp_proto_depIdxs,
		MessageInfos:      file_vinbero_v1_vrf_bgp_proto_msgTypes,
	}.Build()
	File_vinbero_v1_vrf_bgp_proto = out.File
	file_vinbero_v1_vrf_bgp_proto_rawDesc = nil
	file_vinbero_v1_vrf_bgp_proto_goTypes = nil
	file_vinbero_v1_vrf_bgp_proto_depIdxs = nil
}
